package catalog

import (
	"fmt"
	"strconv"
	"strings"
)

// GenerateSeed 为一组 entries 生成幂等 SQL：INSERT ... ON CONFLICT (code) DO UPDATE。
// 可重复执行（幂等）。列名显式写出，避免 02-seed.sql 那种脆弱的 positional VALUES。
// created_at/updated_at 用 now() 不写死，由 DB 维护。
//
// 调用方应先 ValidateSet(entries) 确认无非法值，再 GenerateSeed。
// GenerateSeed 本身只做转义，不做语义校验。
func GenerateSeed(entries []CatalogEntry) string {
	var b strings.Builder
	b.WriteString("-- Auto-generated by provider/catalog.GenerateSeed (GW-01).\n")
	b.WriteString("-- Idempotent: ON CONFLICT (code) DO UPDATE. Re-runnable.\n\n")
	for _, e := range entries {
		writeEntryInsert(&b, e)
	}
	return b.String()
}

// 列顺序与 provider_catalog.sql DDL 一致（去掉 created_at/updated_at，由 DB 默认）。
var seedColumns = []string{
	"code", "tier", "display_name", "display_name_en",
	"category", "kind", "protocol", "base_url_template",
	"docs_url", "default_egress_profile", "domestic", "discount_rate_default",
	"models_manifest_json", "discovery_strategy", "models_endpoint_template",
	"seed_pricing_plans_json", "price_sources_json", "hidden", "notes",
	"catalog_version", "header_profile_code", "capabilities", "vendor_name",
}

// ON CONFLICT (code) DO UPDATE 时刷新的列（不含 code 本身）。
var seedUpdateCols = seedColumns[1:]

func writeEntryInsert(b *strings.Builder, e CatalogEntry) {
	colList := strings.Join(seedColumns, ", ")
	b.WriteString("INSERT INTO public.provider_catalog (")
	b.WriteString(colList)
	b.WriteString(") VALUES (\n")
	vals := []string{
		sqlStr(e.Code), sqlStr(e.Tier), sqlStr(e.DisplayName), sqlStrOrNull(e.DisplayNameEN),
		sqlStr(e.Category), sqlStr(e.Kind), sqlStr(e.Protocol), sqlStr(e.BaseURLTemplate),
		sqlStrOrNull(e.DocsURL), sqlStr(e.DefaultEgressProfile), sqlBool(e.Domestic), sqlFloat(e.DiscountRateDefault),
		sqlJSON(e.ModelsManifestJSON), sqlStr(e.DiscoveryStrategy), sqlStrOrNull(e.ModelsEndpointTpl),
		sqlJSON(e.SeedPricingPlansJSON), sqlJSON(e.PriceSourcesJSON), sqlBool(e.Hidden), sqlStrOrNull(e.Notes),
		strconv.Itoa(e.CatalogVersion), sqlStrOrNull(e.HeaderProfileCode), sqlJSON(e.Capabilities), sqlStrOrNull(e.VendorName),
	}
	b.WriteString("  " + strings.Join(vals, ", "))
	b.WriteString("\n) ON CONFLICT (code) DO UPDATE SET\n")
	sets := make([]string, 0, len(seedUpdateCols))
	// 用 EXCLUDED.<col> 引用 VALUES 里的值。更新所有非主键列。
	for _, c := range seedUpdateCols {
		sets = append(sets, fmt.Sprintf("  %s = EXCLUDED.%s", c, c))
	}
	b.WriteString(strings.Join(sets, ",\n"))
	b.WriteString(",\n  updated_at = now();\n\n")
}

// sqlStr 输出 SQL 单引号字面量。空字符串→”（catalog 里空串合法）。
// 用 strconv.Quote 风格的转义不够（SQL 用 ” 而非 \'），手写 SQL 转义。
func sqlStr(s string) string {
	var b strings.Builder
	b.WriteByte('\'')
	for _, r := range s {
		switch r {
		case '\'':
			b.WriteString("''")
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('\'')
	return b.String()
}

// sqlStrOrNull：空串→NULL，非空→sqlStr。
func sqlStrOrNull(s string) string {
	if s == "" {
		return "NULL"
	}
	return sqlStr(s)
}

func sqlBool(b bool) string {
	if b {
		return "TRUE"
	}
	return "FALSE"
}

func sqlFloat(f float64) string {
	return strconv.FormatFloat(f, 'f', 4, 64)
}

// sqlJSON：nil 或空→'[]' / '{}' 取决于字段；这里要求调用方传合法 json.RawMessage。
// 空 RawMessage 视为 NULL（DB DEFAULT 兜底）。
func sqlJSON(raw []byte) string {
	t := strings.TrimSpace(string(raw))
	if t == "" || t == "null" {
		return "NULL"
	}
	return sqlStr(t)
}
