-- 003_tuning_params.sql — Dynamic tuning parameters for auto-route classifier.
--
-- This table stores runtime-overridable parameters for the heuristic
-- classifier, scoring weights, and LLM-fallback thresholds. The gateway
-- loads these at startup and refreshes every 5 minutes (aligned with
-- auto_index_refresher cadence).
--
-- When empty or missing keys, the gateway falls back to compiled defaults
-- (DefaultKeywords(), DefaultProfileWeights(), DefaultHeuristicThresholds()).
-- Admins and the feedback analyzer (Phase 4) insert rows here to override.
--
-- Idempotent: safe to run multiple times.

BEGIN;

CREATE TABLE IF NOT EXISTS tuning_params (
    key         TEXT PRIMARY KEY,
    value       JSONB NOT NULL,
    category    TEXT NOT NULL,
        -- 'keywords'   : keyword arrays for reasoning/code/creative channels
        -- 'thresholds' : scalar thresholds (llm_confidence_threshold, etc.)
        -- 'weights'    : profile weight matrix overrides
    source      TEXT NOT NULL DEFAULT 'default',
        -- 'default'  : seeded by this migration
        -- 'manual'   : set via admin API
        -- 'feedback' : generated by feedback_analyzer (Phase 4)
    confidence  NUMERIC(4,3) NOT NULL DEFAULT 1.0,
        -- 0-1 confidence in this parameter (from feedback evidence)
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    description TEXT,
    applied_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tuning_params_category
    ON tuning_params (category, enabled)
    WHERE enabled = TRUE;

COMMENT ON TABLE tuning_params IS
    'Runtime tuning parameters for auto-route classifier and scoring. Override-able by admin API and feedback analyzer.';

-- Seed default values so the system is fully functional on first boot.
-- These mirror the Go defaults (DefaultKeywords, DefaultProfileWeights,
-- DefaultHeuristicThresholds) and serve as the "ground truth" baseline.

INSERT INTO tuning_params (key, value, category, source, description) VALUES
(
    'keywords.reasoning',
    '["solve","prove","derive","calculate","compute","reason","reasoning","logic","theorem","proof","step by step","explain why","analyze","证明","推导","求解","计算","推理","逻辑","分析","证明题","推导过程","步骤"]'::jsonb,
    'keywords',
    'default',
    'Keyword list for the reasoning classification channel'
),
(
    'keywords.code',
    '["function","class","method","algorithm","implement","code","program","script","debug","refactor","compile","syntax","variable","代码","函数","方法","实现","编写","写代码","算法","重构","调试","bug","编程"]'::jsonb,
    'keywords',
    'default',
    'Keyword list for the code classification channel'
),
(
    'keywords.creative',
    '["write a","write an","compose","draft","story","blog post","essay","poem","creative","translate","summarize","summary","写一篇","撰写","创作","故事","小说","诗歌","翻译","总结","摘要","文案"]'::jsonb,
    'keywords',
    'default',
    'Keyword list for the creative classification channel'
),
(
    'thresholds.llm_confidence',
    '0.7'::jsonb,
    'thresholds',
    'default',
    'Heuristic confidence below this triggers LLM fallback classifier'
),
(
    'thresholds.long_context_tokens',
    '50000'::jsonb,
    'thresholds',
    'default',
    'Token count above this triggers TaskLongContext hard override'
),
(
    'weights.smart',
    '{"price":25,"speed":25,"stability":20,"match":25,"pressure":10,"context_fit":15}'::jsonb,
    'weights',
    'default',
    'Profile weight matrix for ProfileSmart (balanced)'
),
(
    'weights.speed_first',
    '{"price":10,"speed":50,"stability":20,"match":15,"pressure":5,"context_fit":10}'::jsonb,
    'weights',
    'default',
    'Profile weight matrix for ProfileSpeedFirst (low latency priority)'
),
(
    'weights.cost_first',
    '{"price":50,"speed":10,"stability":15,"match":20,"pressure":5,"context_fit":10}'::jsonb,
    'weights',
    'default',
    'Profile weight matrix for ProfileCostFirst (minimise cost)'
)
ON CONFLICT (key) DO NOTHING;

COMMIT;
