-- 005_tuning_proposals.sql — Tuning proposals generated by the feedback analyzer.
--
-- The feedback_analyzer worker (Phase 4) runs daily at 02:00 and analyzes
-- 7 days of tuning_signals to generate improvement proposals. Each proposal
-- is written here with status='pending' and requires admin approval before
-- it affects the hot path.
--
-- Lifecycle:
--   pending → approved → applied  (happy path)
--   pending → rejected            (admin disagrees)
--
-- Idempotent: safe to run multiple times.

BEGIN;

CREATE TABLE IF NOT EXISTS tuning_proposals (
    id              BIGSERIAL PRIMARY KEY,
    ts              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Classification of the proposal
    category        TEXT NOT NULL,
        -- 'keyword_add'     : suggest adding a new keyword to a channel
        -- 'weight_adjust'   : suggest changing a profile weight
        -- 'threshold_change': suggest changing a classifier threshold
    task_type       TEXT,
        -- Which task_type this proposal targets (NULL for global)

    -- The proposed change (machine-readable for apply logic)
    proposal        JSONB NOT NULL,
        -- keyword_add:    {"key": "keywords.reasoning", "add": ["新词1","新词2"], "channel": "reasoning"}
        -- weight_adjust:  {"key": "weights.smart", "dimension": "match", "old": 25, "new": 20, "profile": "smart"}
        -- threshold:      {"key": "thresholds.llm_confidence", "old": 0.7, "new": 0.6}

    -- Evidence supporting the proposal (for admin review)
    evidence        JSONB NOT NULL,
        -- {"sample_count": 150, "avg_quality": 0.42, "confidence": 0.85,
        --  "rationale": "150 reasoning requests with quality < 0.5 contain '求解方程式' 40 times"}

    -- Workflow state
    status          TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','approved','rejected','applied','expired')),
    reviewed_by     TEXT,
    reviewed_at     TIMESTAMPTZ,
    applied_at      TIMESTAMPTZ,
    review_note     TEXT,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Primary query: admin lists pending proposals
CREATE INDEX IF NOT EXISTS idx_tuning_proposals_status
    ON tuning_proposals (status, ts DESC);

-- Secondary: filter by category or task_type
CREATE INDEX IF NOT EXISTS idx_tuning_proposals_cat
    ON tuning_proposals (category, task_type)
    WHERE status = 'pending';

COMMENT ON TABLE tuning_proposals IS
    'Auto-generated tuning proposals from feedback analysis. Require admin approval before applying to hot path.';

-- Auto-expire proposals older than 30 days (housekeeping).
-- The analyzer skips generating duplicate proposals for keywords already
-- pending in an un-reviewed proposal.
CREATE INDEX IF NOT EXISTS idx_tuning_proposals_created
    ON tuning_proposals (created_at)
    WHERE status = 'pending';

COMMIT;
