export default {
  title: 'Gestión de proxies',
  tabs: { status: 'Resumen de estado', subscriptions: 'Suscripciones', nodes: 'Nodos' },
  status: { overview: 'Resumen', subscriptions: 'Suscripciones activas', nodes: 'Nodos totales', dialable: 'Nodos conectables', healthy: 'Nodos saludables', unhealthy: 'Nodos no saludables', selectedNode: 'Nodo seleccionado', noNodeSelected: 'Ningún nodo seleccionado', swapState: 'Estado de cambio automático', currentNode: 'Nodo activo', lastProbeAt: 'Última comprobación', consecutiveFails: 'Fallos consecutivos', probeInterval: 'Intervalo de comprobación', swapIdle: 'No hay nodo activo', regions: 'Distribución regional', policyTitle: 'Política de selección' },
  actions: { batchHealthCheckAll: 'Comprobar todos los nodos', forceSwap: 'Forzar cambio al mejor nodo' },
  regions: { empty: 'No hay datos de nodos', region: 'Región', total: 'Total', dialable: 'Conectable', active: 'Activo', unhealthy: 'No saludable', banned: 'Excluido', avgLatency: 'Latencia media', bestNode: 'Mejor nodo' },
  policy: { lbStrategy: 'Estrategia de equilibrio de carga', affinity: 'Afinidad de ubicación', autoDisableThreshold: 'Umbral de desactivación automática', autoDisableEnabled: 'Desactivación automática', autoRecoverEnabled: 'Recuperación automática', swapIntervalMs: 'Intervalo de cambio (ms)', swapFailThreshold: 'Umbral de fallo para cambio', edit: 'Editar política', editTitle: 'Editar política de selección', loading: 'Cargando…' },
  subscriptions: { create: 'Nueva suscripción', createTitle: 'Crear suscripción de proxy', name: 'Nombre', url: 'URL de suscripción', urlHint: 'Debe comenzar con http:// o https:// (suscripción Clash)', nodeCount: 'Nodos', status: 'Estado', lastFetch: 'Última obtención', refresh: 'Actualizar', notes: 'Notas', bannedRegions: 'Regiones excluidas', bannedRegionsHint: 'Separadas por comas, por ejemplo US, JP, HK. Los nodos de estas regiones se filtran al seleccionar.', batchHealthCheck: 'Comprobación en lote', empty: 'Sin suscripciones' },
  nodes: { create: 'Nuevo nodo', createTitle: 'Crear nodo de proxy', subscription: 'Suscripción', selectSubscription: 'Seleccionar suscripción', protocolHint: 'Solo se admite HTTP/HTTPS/SOCKS5; trojan/vless debe exponerse mediante un puente local', healthCheck: 'Comprobación de salud', empty: 'Sin nodos' },
  node: { name: 'Nombre', protocol: 'Protocolo', server: 'Servidor', port: 'Puerto', username: 'Nombre de usuario', password: 'Contraseña', location: 'Ubicación', bannedRegions: 'Regiones excluidas', dialable: 'Conectable', status: 'Estado', latency: 'Latencia', failures: 'Fallos consecutivos', healthCheckUrl: 'URL de comprobación de salud' },
  confirmRefresh: '¿Actualizar la suscripción "{name}"?', confirmDeleteSub: '¿Eliminar la suscripción "{name}" y todos sus nodos?', confirmHealthCheck: '¿Ejecutar la comprobación de salud del nodo "{name}"?', confirmDeleteNode: '¿Eliminar el nodo "{name}"?', confirmBatchAll: '¿Comprobar todos los nodos ahora? Esto omite el intervalo inteligente y puede tardar varios segundos.', confirmBatchSub: '¿Comprobar todos los nodos de la suscripción "{name}"?',
  batchResult: { healthAll: 'Comprobación en lote terminada: correctos {ok} / fallidos {failed} / omitidos {skipped}', healthSub: 'Comprobación en lote de la suscripción "{name}": correctos {ok} / fallidos {failed}', swap: 'Cambio forzado al nodo: {name}', policySaved: 'Política guardada y persistida' },
  error: { loadStatusFailed: 'Error al cargar el estado', loadSubsFailed: 'Error al cargar las suscripciones', loadNodesFailed: 'Error al cargar los nodos', nameUrlRequired: 'El nombre y la URL son obligatorios', subscribeUrlMustHttp: 'La URL de suscripción debe comenzar con http:// o https://', createSubFailed: 'Error al crear la suscripción', refreshSubFailed: 'Error al actualizar la suscripción', deleteSubFailed: 'Error al eliminar la suscripción', nodeFieldsRequired: 'El nombre, el servidor y la suscripción son obligatorios', protocolNotDialable: 'Solo se admite HTTP/HTTPS/SOCKS5; trojan/vless debe exponerse mediante un puente local', createNodeFailed: 'Error al crear el nodo', healthCheckFailed: 'Comprobación de salud fallida', deleteNodeFailed: 'Error al eliminar el nodo', batchHealthFailed: 'Comprobación en lote fallida', swapFailed: 'Cambio forzado fallido', savePolicyFailed: 'Error al guardar la política', saveSubBanFailed: 'Error al guardar las regiones excluidas de la suscripción', saveNodeBanFailed: 'Error al guardar las regiones excluidas del nodo' },
}
