--
-- Name: output_compliance_policies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.output_compliance_policies (
    id integer NOT NULL,
    tenant_id character varying(255) NOT NULL,
    enabled boolean DEFAULT true,
    enforcement_mode character varying(20) DEFAULT 'observe'::character varying,
    check_pii boolean DEFAULT true,
    check_toxicity boolean DEFAULT true,
    check_bias boolean DEFAULT false,
    check_hallucination boolean DEFAULT false,
    pii_threshold numeric(3,2) DEFAULT 0.7,
    toxicity_threshold numeric(3,2) DEFAULT 0.7,
    bias_threshold numeric(3,2) DEFAULT 0.6,
    hallucination_threshold numeric(3,2) DEFAULT 0.7,
    action_on_pii character varying(20) DEFAULT 'redact'::character varying,
    action_on_toxicity character varying(20) DEFAULT 'warn'::character varying,
    action_on_bias character varying(20) DEFAULT 'log'::character varying,
    action_on_hallucination character varying(20) DEFAULT 'log'::character varying,
    auto_redact boolean DEFAULT true,
    redact_email boolean DEFAULT true,
    redact_phone boolean DEFAULT true,
    redact_id_card boolean DEFAULT true,
    redact_credit_card boolean DEFAULT true,
    strict_mode boolean DEFAULT false,
    log_all_outputs boolean DEFAULT false,
    whitelist_patterns text[],
    total_checks integer DEFAULT 0,
    total_issues integer DEFAULT 0,
    total_redactions integer DEFAULT 0,
    last_check_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by character varying(255),
    updated_by character varying(255),
    llm_engine_id integer,
    pii_engine character varying(20) DEFAULT 'regex'::character varying,
    toxicity_engine character varying(20) DEFAULT 'keyword'::character varying,
    check_secrets boolean DEFAULT true,
    check_internal_ip boolean DEFAULT true,
    check_jailbreak_response boolean DEFAULT false,
    check_instruction_injection_response boolean DEFAULT false,
    secrets_threshold numeric(3,2) DEFAULT 0.7,
    internal_ip_threshold numeric(3,2) DEFAULT 0.7,
    alert_threshold_severity integer DEFAULT 7,
    action_on_secrets character varying(20) DEFAULT 'redact'::character varying,
    action_on_internal_ip character varying(20) DEFAULT 'redact'::character varying,
    action_on_jailbreak_response character varying(20) DEFAULT 'block'::character varying,
    action_on_instruction_injection_response character varying(20) DEFAULT 'block'::character varying,
    block_message text DEFAULT '响应因合规策略被阻断'::text,
    redact_bank_card boolean DEFAULT false,
    redact_jwt boolean DEFAULT true,
    redact_password boolean DEFAULT true,
    toxic_replacement character varying(100) DEFAULT '[内容已过滤]'::character varying,
    redact_format_overrides jsonb DEFAULT '{}'::jsonb,
    whitelist_keywords text[] DEFAULT '{}'::text[],
    exception_rules jsonb DEFAULT '[]'::jsonb,
    notification_channels jsonb DEFAULT '[]'::jsonb,
    realtime_alert_enabled boolean DEFAULT false,
    alert_aggregation_window_minutes integer DEFAULT 5,
    sampling_rate numeric(3,2) DEFAULT 1.0,
    auto_review_queue_enabled boolean DEFAULT false,
    feedback_loop_enabled boolean DEFAULT false,
    skill_generation_enabled boolean DEFAULT false,
    auto_threshold_tuning_enabled boolean DEFAULT false,
    retention_days integer DEFAULT 90,
    policy_name character varying(100) DEFAULT 'default'::character varying,
    CONSTRAINT output_compliance_policies_action_on_instruction_injectio_check CHECK (((action_on_instruction_injection_response)::text = ANY ((ARRAY['log'::character varying, 'warn'::character varying, 'block'::character varying])::text[]))),
    CONSTRAINT output_compliance_policies_action_on_internal_ip_check CHECK (((action_on_internal_ip)::text = ANY ((ARRAY['log'::character varying, 'warn'::character varying, 'redact'::character varying, 'block'::character varying])::text[]))),
    CONSTRAINT output_compliance_policies_action_on_jailbreak_response_check CHECK (((action_on_jailbreak_response)::text = ANY ((ARRAY['log'::character varying, 'warn'::character varying, 'block'::character varying])::text[]))),
    CONSTRAINT output_compliance_policies_action_on_secrets_check CHECK (((action_on_secrets)::text = ANY ((ARRAY['log'::character varying, 'warn'::character varying, 'redact'::character varying, 'block'::character varying])::text[]))),
    CONSTRAINT output_compliance_policies_alert_aggregation_window_minut_check CHECK ((alert_aggregation_window_minutes >= 0)),
    CONSTRAINT output_compliance_policies_alert_threshold_severity_check CHECK (((alert_threshold_severity >= 1) AND (alert_threshold_severity <= 10))),
    CONSTRAINT output_compliance_policies_pii_engine_check CHECK (((pii_engine)::text = ANY ((ARRAY['regex'::character varying, 'model'::character varying, 'hybrid'::character varying])::text[]))),
    CONSTRAINT output_compliance_policies_retention_days_check CHECK ((retention_days >= 0)),
    CONSTRAINT output_compliance_policies_sampling_rate_check CHECK (((sampling_rate >= (0)::numeric) AND (sampling_rate <= (1)::numeric))),
    CONSTRAINT output_compliance_policies_toxicity_engine_check CHECK (((toxicity_engine)::text = ANY ((ARRAY['keyword'::character varying, 'model'::character varying, 'hybrid'::character varying])::text[])))
);

