--
-- Name: session_summaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.session_summaries (
    session_key character varying(255) NOT NULL,
    tenant_id character varying(255) NOT NULL,
    first_request_at timestamp with time zone NOT NULL,
    last_request_at timestamp with time zone NOT NULL,
    duration_seconds integer GENERATED ALWAYS AS ((EXTRACT(epoch FROM (last_request_at - first_request_at)))::integer) STORED,
    request_count integer DEFAULT 0 NOT NULL,
    success_count integer DEFAULT 0 NOT NULL,
    error_count integer DEFAULT 0 NOT NULL,
    total_cost_usd numeric(12,6) DEFAULT 0 NOT NULL,
    input_cost_usd numeric(12,6) DEFAULT 0 NOT NULL,
    output_cost_usd numeric(12,6) DEFAULT 0 NOT NULL,
    total_prompt_tokens bigint DEFAULT 0 NOT NULL,
    total_completion_tokens bigint DEFAULT 0 NOT NULL,
    total_tokens bigint GENERATED ALWAYS AS ((total_prompt_tokens + total_completion_tokens)) STORED,
    avg_latency_ms integer DEFAULT 0 NOT NULL,
    min_latency_ms integer,
    max_latency_ms integer,
    models_used text[] DEFAULT '{}'::text[] NOT NULL,
    primary_model character varying(100),
    model_switch_count integer DEFAULT 0 NOT NULL,
    title character varying(200),
    summary text,
    key_topics text[],
    user_intent character varying(50),
    quality_score integer,
    compliance_status character varying(20) DEFAULT 'compliant'::character varying,
    compliance_issues_count integer DEFAULT 0 NOT NULL,
    prompt_injection_detected boolean DEFAULT false,
    pii_detected boolean DEFAULT false,
    toxic_output_detected boolean DEFAULT false,
    work_types text[],
    providers text[],
    client_models text[],
    last_summarized_at timestamp with time zone,
    summary_version integer DEFAULT 1,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    handoff_count integer,
    last_handoff_at timestamp without time zone,
    health_score integer,
    health_grade character varying(1),
    range character varying(20),
    last_health_at timestamp without time zone,
    tokens_at_trigger bigint DEFAULT 0 NOT NULL,
    messages_at_trigger integer DEFAULT 0 NOT NULL,
    last_trigger_reason character varying(64),
    last_trigger_at timestamp with time zone,
    CONSTRAINT session_summaries_quality_score_check CHECK (((quality_score >= 0) AND (quality_score <= 10)))
);

