--
-- Name: state_change_log; Type: TABLE; Schema: public; Owner: -
--
-- Records state transitions for (credential, model) nodes.
-- Written only when a node transitions between available/unavailable states.
-- 7-day retention — rows are pruned by scheduled cleanup.
-- Replaces credential_state_log, credential_state_nodes, passive_probe_state.
--

CREATE TABLE public.state_change_log (
    id bigint NOT NULL,
    credential_id integer NOT NULL,
    raw_model_name text NOT NULL,

    -- event metadata
    event_type text NOT NULL,                       -- 'available_unavailable' | 'unavailable_available'
    reason text NOT NULL,                           -- 'consecutive_2_failures' | 'request_success' | etc.
    error_kind text,                                -- error that triggered the transition
    consecutive_fail integer DEFAULT 0 NOT NULL,    -- consecutive_fail count at transition time

    -- snapshot of the Redis node state at transition time
    snapshot jsonb,

    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: state_change_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.state_change_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.state_change_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TABLE state_change_log; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.state_change_log IS
    'Records (credential, model) state transitions between available/unavailable. Written atomically by ursm.StateRecorder Lua script. 7-day retention.';


--
-- Name: idx_scl_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scl_created_at ON public.state_change_log USING btree (created_at);


--
-- Name: idx_scl_credential; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scl_credential ON public.state_change_log USING btree (credential_id, raw_model_name, created_at DESC);
