-- Migration 706: 存储优化方案 v2 · S1a —— 六表族补全（三新表 + sessions 补列）
--
-- docs/03-design/04-data-design/storage-optimization-plan.md §4 S1a 行：
--   session_memora / session_censors / session_tools 三新表 + sessions 补列。
--
-- 三新表职责（方案 §1）：
--   session_memora  —— 会话初始环境/上下文快照（首 turn 一次写入，insert-only）；
--                      与同实例 kxmemory 产品的 memora_* 表零接触（跨产品边界禁令）。
--   session_censors —— SmartSaniGuard 可逆脱敏映射落库（现 Redis-only、TTL 30min
--                      即永久丢失）；original_encrypted 为应用层 AES-GCM，密钥未
--                      配置时为 NULL（降级只存 type+占位符）。
--   session_tools   —— 承接 domains/toolexecution 写链（134 形状 + turn_no +
--                      月分区化）。审计事实（2026-09-14 本机）：migration 134 属
--                      domain 通道、本地两账本均无记录，tool_executions 表不存在，
--                      写链一直缺表；切到本表同时修复该缺口。tool_call_events
--                      （8 行、无 session、零读者）废弃不迁。
--
-- 分区惯例沿用 430：partition_date 存日粒度（calendarDate(ts)），月分区
-- [_2026_09 ...)；hot 表 + promote 函数沿用 614/615/638 惯例，PartitionManager
-- 经 bg.ensureSpecs/promoteSpecs 注册（Go 侧同提交）。
--
-- Compatibility: 纯增量建表 + 可空补列，对既有数据零回填、零锁风险。
-- down: DROP 三新表族 + sessions 补列（账本行保留，append-only）。

BEGIN;

-- =============================================
-- 1. session_memora
-- =============================================

CREATE TABLE IF NOT EXISTS public.session_memora (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    client_env JSONB,            -- 客户端类型/版本/入口/项目/agent
    initial_context JSONB,       -- system prompt digest+指纹、初始消息指纹、可用工具清单
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    partition_date DATE NOT NULL DEFAULT CURRENT_DATE,
    PRIMARY KEY (id, partition_date),
    UNIQUE (tenant_id, session_id, partition_date)
) PARTITION BY RANGE (partition_date);

CREATE INDEX IF NOT EXISTS idx_session_memora_session
    ON public.session_memora (session_id, partition_date DESC);

ALTER TABLE public.session_memora ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS session_memora_tenant_isolation ON public.session_memora;
CREATE POLICY session_memora_tenant_isolation ON public.session_memora
    USING (tenant_id = current_setting('app.current_tenant', true)::TEXT);

DROP POLICY IF EXISTS session_memora_super_admin_bypass ON public.session_memora;
CREATE POLICY session_memora_super_admin_bypass ON public.session_memora
    USING (current_setting('app.current_role', true) = 'super_admin'
        OR current_setting('app.bypass_rls', true) = 'true');

COMMENT ON TABLE public.session_memora IS
    '会话初始环境/上下文快照（存储优化方案 v2 S1a，migration 706）。
     首 turn 持久化时一次写入；记忆本体在外部 kxmemory，本表不是记忆库。';

-- =============================================
-- 2. session_censors
-- =============================================

CREATE TABLE IF NOT EXISTS public.session_censors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    request_id TEXT,
    turn_no INT,
    placeholder TEXT NOT NULL,       -- {SENSITIVE:phone:3}
    sensitive_type TEXT NOT NULL,    -- phone/id_card/email/credit_card/...
    original_encrypted BYTEA,        -- AES-GCM；租户开关关闭/无密钥时为 NULL
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    partition_date DATE NOT NULL DEFAULT CURRENT_DATE,
    PRIMARY KEY (id, partition_date)
) PARTITION BY RANGE (partition_date);

CREATE INDEX IF NOT EXISTS idx_session_censors_session
    ON public.session_censors (tenant_id, session_id, partition_date);
CREATE INDEX IF NOT EXISTS idx_session_censors_request
    ON public.session_censors (request_id, partition_date)
    WHERE request_id IS NOT NULL;

ALTER TABLE public.session_censors ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS session_censors_tenant_isolation ON public.session_censors;
CREATE POLICY session_censors_tenant_isolation ON public.session_censors
    USING (tenant_id = current_setting('app.current_tenant', true)::TEXT);

DROP POLICY IF EXISTS session_censors_super_admin_bypass ON public.session_censors;
CREATE POLICY session_censors_super_admin_bypass ON public.session_censors
    USING (current_setting('app.current_role', true) = 'super_admin'
        OR current_setting('app.bypass_rls', true) = 'true');

COMMENT ON TABLE public.session_censors IS
    'SmartSaniGuard 可逆脱敏映射落库（存储优化方案 v2 S1a，migration 706）。
     写点=sanitize 中间件 saveMapAndOffsets 双写；Redis 降级为热缓存。
     原文销毁单独走租户级请求（方案 §7）。';

-- =============================================
-- 3. session_tools
-- =============================================

CREATE TABLE IF NOT EXISTS public.session_tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    execution_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    turn_no INT,                     -- 134 无；S1a 补（hook 暂无 turn 上下文时为 NULL）
    tool_name VARCHAR(128) NOT NULL,
    tool_call_id VARCHAR(128),
    arguments JSONB,
    result JSONB,
    status VARCHAR(16) NOT NULL,     -- pending, success, error, timeout
    error_message TEXT,
    error_type VARCHAR(32),          -- network_error, timeout, invalid_args, execution_failed
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    duration_ms BIGINT,
    identity_hash VARCHAR(64),
    model VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    partition_date DATE NOT NULL DEFAULT CURRENT_DATE,
    PRIMARY KEY (id, partition_date),
    UNIQUE (execution_id, partition_date)
) PARTITION BY RANGE (partition_date);

CREATE INDEX IF NOT EXISTS idx_session_tools_session
    ON public.session_tools (session_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_session_tools_request
    ON public.session_tools (request_id, partition_date);
CREATE INDEX IF NOT EXISTS idx_session_tools_tenant
    ON public.session_tools (tenant_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_session_tools_tool_name
    ON public.session_tools (tool_name, started_at DESC);

ALTER TABLE public.session_tools ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS session_tools_tenant_isolation ON public.session_tools;
CREATE POLICY session_tools_tenant_isolation ON public.session_tools
    USING (tenant_id = current_setting('app.current_tenant', true)::TEXT);

DROP POLICY IF EXISTS session_tools_super_admin_bypass ON public.session_tools;
CREATE POLICY session_tools_super_admin_bypass ON public.session_tools
    USING (current_setting('app.current_role', true) = 'super_admin'
        OR current_setting('app.bypass_rls', true) = 'true');

COMMENT ON TABLE public.session_tools IS
    '会话工具调用明细（存储优化方案 v2 S1a，migration 706）。
     列承接 migration 134 的 tool_executions 形状 + turn_no + 月分区化；
     domains/toolexecution 写链切换到本表。tool_call_events 废弃（零读者）。';

-- =============================================
-- 4. hot 表（614 惯例）
-- =============================================

CREATE TABLE IF NOT EXISTS public.session_memora_hot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    client_env JSONB,
    initial_context JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    partition_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT session_memora_hot_uq UNIQUE (tenant_id, session_id, partition_date)
);

CREATE INDEX IF NOT EXISTS idx_session_memora_hot_session
    ON public.session_memora_hot (session_id, partition_date DESC);
CREATE INDEX IF NOT EXISTS idx_session_memora_hot_ts ON public.session_memora_hot (created_at);

ALTER TABLE public.session_memora_hot ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS session_memora_hot_tenant_isolation ON public.session_memora_hot;
CREATE POLICY session_memora_hot_tenant_isolation ON public.session_memora_hot
    USING (tenant_id = current_setting('app.current_tenant', true)::TEXT);
DROP POLICY IF EXISTS session_memora_hot_super_admin_bypass ON public.session_memora_hot;
CREATE POLICY session_memora_hot_super_admin_bypass ON public.session_memora_hot
    USING (current_setting('app.current_role', true) = 'super_admin'
        OR current_setting('app.bypass_rls', true) = 'true');

CREATE TABLE IF NOT EXISTS public.session_censors_hot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    request_id TEXT,
    turn_no INT,
    placeholder TEXT NOT NULL,
    sensitive_type TEXT NOT NULL,
    original_encrypted BYTEA,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    partition_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE INDEX IF NOT EXISTS idx_session_censors_hot_session
    ON public.session_censors_hot (tenant_id, session_id, partition_date);
CREATE INDEX IF NOT EXISTS idx_session_censors_hot_ts ON public.session_censors_hot (created_at);

ALTER TABLE public.session_censors_hot ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS session_censors_hot_tenant_isolation ON public.session_censors_hot;
CREATE POLICY session_censors_hot_tenant_isolation ON public.session_censors_hot
    USING (tenant_id = current_setting('app.current_tenant', true)::TEXT);
DROP POLICY IF EXISTS session_censors_hot_super_admin_bypass ON public.session_censors_hot;
CREATE POLICY session_censors_hot_super_admin_bypass ON public.session_censors_hot
    USING (current_setting('app.current_role', true) = 'super_admin'
        OR current_setting('app.bypass_rls', true) = 'true');

CREATE TABLE IF NOT EXISTS public.session_tools_hot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    turn_no INT,
    tool_name VARCHAR(128) NOT NULL,
    tool_call_id VARCHAR(128),
    arguments JSONB,
    result JSONB,
    status VARCHAR(16) NOT NULL,
    error_message TEXT,
    error_type VARCHAR(32),
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    duration_ms BIGINT,
    identity_hash VARCHAR(64),
    model VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    partition_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT session_tools_hot_uq UNIQUE (execution_id, partition_date)
);

CREATE INDEX IF NOT EXISTS idx_session_tools_hot_session
    ON public.session_tools_hot (session_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_session_tools_hot_ts ON public.session_tools_hot (created_at);

ALTER TABLE public.session_tools_hot ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS session_tools_hot_tenant_isolation ON public.session_tools_hot;
CREATE POLICY session_tools_hot_tenant_isolation ON public.session_tools_hot
    USING (tenant_id = current_setting('app.current_tenant', true)::TEXT);
DROP POLICY IF EXISTS session_tools_hot_super_admin_bypass ON public.session_tools_hot;
CREATE POLICY session_tools_hot_super_admin_bypass ON public.session_tools_hot
    USING (current_setting('app.current_role', true) = 'super_admin'
        OR current_setting('app.bypass_rls', true) = 'true');

-- =============================================
-- 5. ensure 函数（月分区；bg.ensureSpecs 注册）
-- =============================================

CREATE OR REPLACE FUNCTION public.ensure_session_family_partitions(target_date DATE DEFAULT CURRENT_DATE)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    month_start DATE := DATE_TRUNC('month', target_date)::DATE;
    month_end DATE := (DATE_TRUNC('month', target_date) + INTERVAL '1 month')::DATE;
    partition_suffix TEXT := TO_CHAR(month_start, 'YYYY_MM');
BEGIN
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.session_memora_%s PARTITION OF public.session_memora
         FOR VALUES FROM (%L) TO (%L)',
        partition_suffix, month_start, month_end
    );
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.session_censors_%s PARTITION OF public.session_censors
         FOR VALUES FROM (%L) TO (%L)',
        partition_suffix, month_start, month_end
    );
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.session_tools_%s PARTITION OF public.session_tools
         FOR VALUES FROM (%L) TO (%L)',
        partition_suffix, month_start, month_end
    );
    RAISE NOTICE 'Created session family partitions for %', partition_suffix;
END;
$$;

COMMENT ON FUNCTION public.ensure_session_family_partitions(DATE) IS
    'Ensure monthly partitions for session_memora/session_censors/session_tools.
     Called by bg.PartitionManager ensureSpecs (migration 706).';

SELECT public.ensure_session_family_partitions(CURRENT_DATE);
SELECT public.ensure_session_family_partitions((CURRENT_DATE + INTERVAL '1 month')::DATE);

-- =============================================
-- 6. promote 函数（638 守卫形态）
-- =============================================

CREATE OR REPLACE FUNCTION public.promote_session_memora_hot_to_partition(
    retention_window interval DEFAULT '8 hours',
    batch_size integer DEFAULT 5000
)
RETURNS TABLE(moved_count bigint) AS $$
DECLARE
    cutoff_ts timestamptz;
BEGIN
    IF retention_window IS NULL OR retention_window <= interval '0 seconds' THEN
        RAISE EXCEPTION 'retention_window must be positive';
    END IF;
    IF batch_size IS NULL OR batch_size < 1 THEN
        RAISE EXCEPTION 'batch_size must be >= 1';
    END IF;
    cutoff_ts := now() - retention_window;
    IF NOT pg_try_advisory_xact_lock(hashtext('public.promote_session_memora_hot_to_partition')) THEN
        RETURN QUERY SELECT 0::bigint;
        RETURN;
    END IF;
    WITH to_move AS (
        SELECT id, session_id, tenant_id, client_env, initial_context,
               created_at, partition_date
        FROM public.session_memora_hot
        WHERE created_at < cutoff_ts
        ORDER BY created_at
        LIMIT batch_size
        FOR UPDATE SKIP LOCKED
    ),
    inserted AS (
        INSERT INTO public.session_memora
            (id, session_id, tenant_id, client_env, initial_context,
             created_at, partition_date)
        SELECT id, session_id, tenant_id, client_env, initial_context,
               created_at, partition_date
        FROM to_move
        ON CONFLICT (id, partition_date) DO NOTHING
        RETURNING id, partition_date
    ),
    deleted AS (
        DELETE FROM public.session_memora_hot h
        USING inserted i
        WHERE h.id = i.id AND h.partition_date = i.partition_date
        RETURNING 1
    )
    SELECT count(*) INTO moved_count FROM deleted;
    RETURN QUERY SELECT moved_count;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.promote_session_censors_hot_to_partition(
    retention_window interval DEFAULT '8 hours',
    batch_size integer DEFAULT 5000
)
RETURNS TABLE(moved_count bigint) AS $$
DECLARE
    cutoff_ts timestamptz;
BEGIN
    IF retention_window IS NULL OR retention_window <= interval '0 seconds' THEN
        RAISE EXCEPTION 'retention_window must be positive';
    END IF;
    IF batch_size IS NULL OR batch_size < 1 THEN
        RAISE EXCEPTION 'batch_size must be >= 1';
    END IF;
    cutoff_ts := now() - retention_window;
    IF NOT pg_try_advisory_xact_lock(hashtext('public.promote_session_censors_hot_to_partition')) THEN
        RETURN QUERY SELECT 0::bigint;
        RETURN;
    END IF;
    WITH to_move AS (
        SELECT id, session_id, tenant_id, request_id, turn_no, placeholder,
               sensitive_type, original_encrypted, created_at, partition_date
        FROM public.session_censors_hot
        WHERE created_at < cutoff_ts
        ORDER BY created_at
        LIMIT batch_size
        FOR UPDATE SKIP LOCKED
    ),
    inserted AS (
        INSERT INTO public.session_censors
            (id, session_id, tenant_id, request_id, turn_no, placeholder,
             sensitive_type, original_encrypted, created_at, partition_date)
        SELECT id, session_id, tenant_id, request_id, turn_no, placeholder,
               sensitive_type, original_encrypted, created_at, partition_date
        FROM to_move
        ON CONFLICT (id, partition_date) DO NOTHING
        RETURNING id, partition_date
    ),
    deleted AS (
        DELETE FROM public.session_censors_hot h
        USING inserted i
        WHERE h.id = i.id AND h.partition_date = i.partition_date
        RETURNING 1
    )
    SELECT count(*) INTO moved_count FROM deleted;
    RETURN QUERY SELECT moved_count;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.promote_session_tools_hot_to_partition(
    retention_window interval DEFAULT '8 hours',
    batch_size integer DEFAULT 5000
)
RETURNS TABLE(moved_count bigint) AS $$
DECLARE
    cutoff_ts timestamptz;
BEGIN
    IF retention_window IS NULL OR retention_window <= interval '0 seconds' THEN
        RAISE EXCEPTION 'retention_window must be positive';
    END IF;
    IF batch_size IS NULL OR batch_size < 1 THEN
        RAISE EXCEPTION 'batch_size must be >= 1';
    END IF;
    cutoff_ts := now() - retention_window;
    IF NOT pg_try_advisory_xact_lock(hashtext('public.promote_session_tools_hot_to_partition')) THEN
        RETURN QUERY SELECT 0::bigint;
        RETURN;
    END IF;
    WITH to_move AS (
        SELECT id, execution_id, session_id, request_id, tenant_id, turn_no,
               tool_name, tool_call_id, arguments, result, status,
               error_message, error_type, started_at, completed_at,
               duration_ms, identity_hash, model, created_at, partition_date
        FROM public.session_tools_hot
        WHERE created_at < cutoff_ts
        ORDER BY created_at
        LIMIT batch_size
        FOR UPDATE SKIP LOCKED
    ),
    inserted AS (
        INSERT INTO public.session_tools
            (id, execution_id, session_id, request_id, tenant_id, turn_no,
             tool_name, tool_call_id, arguments, result, status,
             error_message, error_type, started_at, completed_at,
             duration_ms, identity_hash, model, created_at, partition_date)
        SELECT id, execution_id, session_id, request_id, tenant_id, turn_no,
               tool_name, tool_call_id, arguments, result, status,
               error_message, error_type, started_at, completed_at,
               duration_ms, identity_hash, model, created_at, partition_date
        FROM to_move
        ON CONFLICT (id, partition_date) DO NOTHING
        RETURNING id, partition_date
    ),
    deleted AS (
        DELETE FROM public.session_tools_hot h
        USING inserted i
        WHERE h.id = i.id AND h.partition_date = i.partition_date
        RETURNING 1
    )
    SELECT count(*) INTO moved_count FROM deleted;
    RETURN QUERY SELECT moved_count;
END;
$$ LANGUAGE plpgsql;

-- =============================================
-- 7. sessions 补列（全部可空，无回填锁风险）
-- =============================================

ALTER TABLE public.sessions
    ADD COLUMN IF NOT EXISTS project_id TEXT,
    ADD COLUMN IF NOT EXISTS api_key_id TEXT,
    ADD COLUMN IF NOT EXISTS application_id TEXT,
    ADD COLUMN IF NOT EXISTS end_user_id TEXT,
    ADD COLUMN IF NOT EXISTS owner_user TEXT,
    ADD COLUMN IF NOT EXISTS client_ip TEXT,
    ADD COLUMN IF NOT EXISTS agent_name TEXT,
    ADD COLUMN IF NOT EXISTS duration_ms BIGINT;

COMMENT ON COLUMN public.sessions.project_id IS '会话归属项目（首值优先，X-Gw-Project-Id 链路，706）';
COMMENT ON COLUMN public.sessions.api_key_id IS '访问维度·API key（首值优先，706）';
COMMENT ON COLUMN public.sessions.application_id IS '访问维度·应用（首值优先，706）';
COMMENT ON COLUMN public.sessions.end_user_id IS '访问维度·终端用户（首值优先，706）';
COMMENT ON COLUMN public.sessions.owner_user IS '访问维度·属主（首值优先，706）';
COMMENT ON COLUMN public.sessions.client_ip IS '首请求客户端 IP（706）';
COMMENT ON COLUMN public.sessions.agent_name IS '客户端 agent 名（首值优先，706）';
COMMENT ON COLUMN public.sessions.duration_ms IS '会话耗时；关闭时 closed_at-created_at（706）';

-- 双账本自登记（695-705 定式）。
INSERT INTO public.schema_migrations (version, description)
VALUES ('706', 'storage plan v2 S1a: session_memora/censors/tools tables + sessions access-dim columns')
ON CONFLICT (version) DO UPDATE SET description = EXCLUDED.description;

COMMIT;
