export default {
  title: 'Gestion des proxys',
  tabs: { status: 'Aperçu du statut', subscriptions: 'Abonnements', nodes: 'Nœuds' },
  status: { overview: 'Aperçu', subscriptions: 'Abonnements actifs', nodes: 'Total des nœuds', dialable: 'Nœuds utilisables', healthy: 'Nœuds sains', unhealthy: 'Nœuds non sains', selectedNode: 'Nœud sélectionné', noNodeSelected: 'Aucun nœud sélectionné', swapState: 'État du basculement automatique', currentNode: 'Nœud actif', lastProbeAt: 'Dernière sonde', consecutiveFails: 'Échecs consécutifs', probeInterval: 'Intervalle de sonde', swapIdle: 'Aucun nœud actif', regions: 'Répartition régionale', policyTitle: 'Politique de sélection' },
  actions: { batchHealthCheckAll: 'Vérifier tous les nœuds', forceSwap: 'Basculer de force vers le meilleur nœud' },
  regions: { empty: 'Aucune donnée de nœud', region: 'Région', total: 'Total', dialable: 'Utilisable', active: 'Actif', unhealthy: 'Non sain', banned: 'Exclu', avgLatency: 'Latence moy.', bestNode: 'Meilleur nœud' },
  policy: { lbStrategy: 'Stratégie d’équilibrage de charge', affinity: 'Affinité de localisation', autoDisableThreshold: 'Seuil de désactivation automatique', autoDisableEnabled: 'Désactivation automatique', autoRecoverEnabled: 'Récupération automatique', swapIntervalMs: 'Intervalle de basculement (ms)', swapFailThreshold: 'Seuil d’échec de basculement', edit: 'Modifier la politique', editTitle: 'Modifier la politique de sélection', loading: 'Chargement…' },
  subscriptions: { create: 'Nouvel abonnement', createTitle: 'Créer un abonnement proxy', name: 'Nom', url: 'URL d’abonnement', urlHint: 'Doit commencer par http:// ou https:// (abonnement Clash)', nodeCount: 'Nœuds', status: 'Statut', lastFetch: 'Dernière récupération', refresh: 'Actualiser', notes: 'Notes', bannedRegions: 'Régions exclues', bannedRegionsHint: 'Séparées par des virgules, par ex. US, JP, HK. Les nœuds de ces régions sont filtrés lors de la sélection.', batchHealthCheck: 'Vérification groupée', empty: 'Aucun abonnement' },
  nodes: { create: 'Nouveau nœud', createTitle: 'Créer un nœud proxy', subscription: 'Abonnement', selectSubscription: 'Sélectionner un abonnement', protocolHint: 'Seuls HTTP/HTTPS/SOCKS5 sont pris en charge ; trojan/vless doivent être exposés via un pont local', healthCheck: 'Vérification de santé', empty: 'Aucun nœud' },
  node: { name: 'Nom', protocol: 'Protocole', server: 'Serveur', port: 'Port', username: 'Nom d’utilisateur', password: 'Mot de passe', location: 'Emplacement', bannedRegions: 'Régions exclues', dialable: 'Utilisable', status: 'Statut', latency: 'Latence', failures: 'Échecs consécutifs', healthCheckUrl: 'URL de vérification de santé' },
  confirmRefresh: 'Actualiser l’abonnement « {name} » ?', confirmDeleteSub: 'Supprimer l’abonnement « {name} » et tous ses nœuds ?', confirmHealthCheck: 'Exécuter la vérification de santé du nœud « {name} » ?', confirmDeleteNode: 'Supprimer le nœud « {name} » ?', confirmBatchAll: 'Vérifier tous les nœuds maintenant ? Cela ignore l’intervalle intelligent et peut prendre plusieurs secondes.', confirmBatchSub: 'Vérifier tous les nœuds de l’abonnement « {name} » ?',
  batchResult: { healthAll: 'Vérification groupée terminée : réussies {ok} / échouées {failed} / ignorées {skipped}', healthSub: 'Vérification groupée de l’abonnement « {name} » : réussies {ok} / échouées {failed}', swap: 'Basculement forcé vers le nœud : {name}', policySaved: 'Politique enregistrée et persistée' },
  error: { loadStatusFailed: 'Échec du chargement du statut', loadSubsFailed: 'Échec du chargement des abonnements', loadNodesFailed: 'Échec du chargement des nœuds', nameUrlRequired: 'Le nom et l’URL sont requis', subscribeUrlMustHttp: 'L’URL d’abonnement doit commencer par http:// ou https://', createSubFailed: 'Échec de la création de l’abonnement', refreshSubFailed: 'Échec de l’actualisation de l’abonnement', deleteSubFailed: 'Échec de la suppression de l’abonnement', nodeFieldsRequired: 'Le nom, le serveur et l’abonnement sont requis', protocolNotDialable: 'Seuls HTTP/HTTPS/SOCKS5 sont pris en charge ; trojan/vless doivent être exposés via un pont local', createNodeFailed: 'Échec de la création du nœud', healthCheckFailed: 'Échec de la vérification de santé', deleteNodeFailed: 'Échec de la suppression du nœud', batchHealthFailed: 'Échec de la vérification groupée', swapFailed: 'Échec du basculement forcé', savePolicyFailed: 'Échec de l’enregistrement de la politique', saveSubBanFailed: 'Échec de l’enregistrement des régions exclues de l’abonnement', saveNodeBanFailed: 'Échec de l’enregistrement des régions exclues du nœud' },
}
