export default {
  title: 'إدارة الوكيل',
  tabs: { status: 'نظرة عامة على الحالة', subscriptions: 'الاشتراكات', nodes: 'العقد' },
  status: { overview: 'نظرة عامة', subscriptions: 'الاشتراكات النشطة', nodes: 'إجمالي العقد', dialable: 'العقد القابلة للاتصال', healthy: 'العقد السليمة', unhealthy: 'العقد غير السليمة', selectedNode: 'العقدة المحددة', noNodeSelected: 'لم يتم تحديد عقدة', swapState: 'حالة التبديل التلقائي', currentNode: 'العقدة النشطة', lastProbeAt: 'آخر فحص', consecutiveFails: 'الإخفاقات المتتالية', probeInterval: 'فاصل الفحص', swapIdle: 'لا توجد عقدة نشطة', regions: 'التوزيع حسب المنطقة', policyTitle: 'سياسة الاختيار' },
  actions: { batchHealthCheckAll: 'فحص جميع العقد دفعة واحدة', forceSwap: 'فرض التبديل إلى أفضل عقدة' },
  regions: { empty: 'لا توجد بيانات للعقد', region: 'المنطقة', total: 'الإجمالي', dialable: 'قابلة للاتصال', active: 'نشطة', unhealthy: 'غير سليمة', banned: 'مستبعدة', avgLatency: 'متوسط الكمون', bestNode: 'أفضل عقدة' },
  policy: { lbStrategy: 'استراتيجية موازنة الحمل', affinity: 'تقارب الموقع', autoDisableThreshold: 'حد التعطيل التلقائي', autoDisableEnabled: 'تعطيل تلقائي', autoRecoverEnabled: 'استرداد تلقائي', swapIntervalMs: 'فاصل التبديل (مللي ثانية)', swapFailThreshold: 'حد فشل التبديل', edit: 'تعديل السياسة', editTitle: 'تعديل سياسة الاختيار', loading: 'جارٍ التحميل…' },
  subscriptions: { create: 'اشتراك جديد', createTitle: 'إنشاء اشتراك وكيل', name: 'الاسم', url: 'عنوان URL للاشتراك', urlHint: 'يجب أن يبدأ بـ http:// أو https:// (اشتراك Clash)', nodeCount: 'العقد', status: 'الحالة', lastFetch: 'آخر جلب', refresh: 'تحديث', notes: 'ملاحظات', bannedRegions: 'المناطق المستبعدة', bannedRegionsHint: 'افصل بفواصل، مثل US وJP وHK. تُستبعد عقد هذه المناطق عند الاختيار.', batchHealthCheck: 'فحص جماعي', empty: 'لا توجد اشتراكات' },
  nodes: { create: 'عقدة جديدة', createTitle: 'إنشاء عقدة وكيل', subscription: 'الاشتراك', selectSubscription: 'حدد اشتراكًا', protocolHint: 'يدعم فقط HTTP/HTTPS/SOCKS5؛ يجب إتاحة trojan/vless عبر جسر محلي', healthCheck: 'فحص الصحة', empty: 'لا توجد عقد' },
  node: { name: 'الاسم', protocol: 'البروتوكول', server: 'الخادم', port: 'المنفذ', username: 'اسم المستخدم', password: 'كلمة المرور', location: 'الموقع', bannedRegions: 'المناطق المستبعدة', dialable: 'قابلة للاتصال', status: 'الحالة', latency: 'الكمون', failures: 'الإخفاقات المتتالية', healthCheckUrl: 'عنوان URL لفحص الصحة' },
  confirmRefresh: 'تحديث الاشتراك "{name}"؟', confirmDeleteSub: 'حذف الاشتراك "{name}" وجميع عقده؟', confirmHealthCheck: 'تشغيل فحص الصحة للعقدة "{name}"؟', confirmDeleteNode: 'حذف العقدة "{name}"؟', confirmBatchAll: 'إجراء فحص جماعي لكل العقد الآن؟ سيتجاوز ذلك الفاصل الذكي وقد يستغرق عدة ثوانٍ.', confirmBatchSub: 'إجراء فحص جماعي لكل عقد الاشتراك "{name}"؟',
  batchResult: { healthAll: 'اكتمل الفحص الجماعي: ناجح {ok} / فاشل {failed} / متخطى {skipped}', healthSub: 'الفحص الجماعي للاشتراك "{name}": ناجح {ok} / فاشل {failed}', swap: 'تم فرض التبديل إلى العقدة: {name}', policySaved: 'تم حفظ السياسة واستمرارها' },
  error: { loadStatusFailed: 'فشل تحميل الحالة', loadSubsFailed: 'فشل تحميل الاشتراكات', loadNodesFailed: 'فشل تحميل العقد', nameUrlRequired: 'الاسم وعنوان URL مطلوبان', subscribeUrlMustHttp: 'يجب أن يبدأ عنوان URL للاشتراك بـ http:// أو https://', createSubFailed: 'فشل إنشاء الاشتراك', refreshSubFailed: 'فشل تحديث الاشتراك', deleteSubFailed: 'فشل حذف الاشتراك', nodeFieldsRequired: 'الاسم والخادم والاشتراك مطلوبة', protocolNotDialable: 'يدعم فقط HTTP/HTTPS/SOCKS5؛ يجب إتاحة trojan/vless عبر جسر محلي', createNodeFailed: 'فشل إنشاء العقدة', healthCheckFailed: 'فشل فحص الصحة', deleteNodeFailed: 'فشل حذف العقدة', batchHealthFailed: 'فشل الفحص الجماعي', swapFailed: 'فشل التبديل القسري', savePolicyFailed: 'فشل حفظ السياسة', saveSubBanFailed: 'فشل حفظ المناطق المستبعدة للاشتراك', saveNodeBanFailed: 'فشل حفظ المناطق المستبعدة للعقدة' },
}
