export default {
  title: 'プロキシ管理',
  tabs: { status: 'ステータス概要', subscriptions: 'サブスクリプション', nodes: 'ノード' },
  status: { overview: '概要', subscriptions: 'アクティブなサブスクリプション', nodes: 'ノード総数', dialable: '接続可能なノード', healthy: '正常なノード', unhealthy: '異常なノード', selectedNode: '選択中のノード', noNodeSelected: 'ノードが選択されていません', swapState: '自動切替状態', currentNode: 'アクティブノード', lastProbeAt: '最終プローブ', consecutiveFails: '連続失敗回数', probeInterval: 'プローブ間隔', swapIdle: 'アクティブなノードはありません', regions: '地域分布', policyTitle: '選択ポリシー' },
  actions: { batchHealthCheckAll: 'すべてのノードを一括ヘルスチェック', forceSwap: '最適ノードへ強制切替' },
  regions: { empty: 'ノードデータがありません', region: '地域', total: '合計', dialable: '接続可能', active: 'アクティブ', unhealthy: '異常', banned: '除外済み', avgLatency: '平均レイテンシ', bestNode: '最適ノード' },
  policy: { lbStrategy: '負荷分散戦略', affinity: 'ロケーション親和性', autoDisableThreshold: '自動無効化しきい値', autoDisableEnabled: '自動無効化', autoRecoverEnabled: '自動復旧', swapIntervalMs: '切替間隔 (ms)', swapFailThreshold: '切替の連続失敗しきい値', edit: 'ポリシーを編集', editTitle: '選択ポリシーを編集', loading: '読み込み中…' },
  subscriptions: { create: '新規サブスクリプション', createTitle: 'プロキシサブスクリプション作成', name: '名前', url: 'サブスクリプションURL', urlHint: 'http:// または https:// で始まる Clash サブスクリプションURLである必要があります', nodeCount: 'ノード数', status: 'ステータス', lastFetch: '最終取得', refresh: '更新', notes: '備考', bannedRegions: '除外国', bannedRegionsHint: 'US, JP, HK のようにカンマで区切ります。これらの地域のノードは選択時に除外されます。', batchHealthCheck: '一括プローブ', empty: 'サブスクリプションがありません' },
  nodes: { create: '新規ノード', createTitle: 'プロキシノード作成', subscription: 'サブスクリプション', selectSubscription: 'サブスクリプションを選択', protocolHint: 'HTTP/HTTPS/SOCKS5 のみ対応。trojan/vless はローカルブリッジ経由で公開する必要があります', healthCheck: 'ヘルスチェック', empty: 'ノードがありません' },
  node: { name: '名前', protocol: 'プロトコル', server: 'サーバー', port: 'ポート', username: 'ユーザー名', password: 'パスワード', location: '場所', bannedRegions: '除外国', dialable: '接続可能', status: 'ステータス', latency: 'レイテンシ', failures: '連続失敗', healthCheckUrl: 'ヘルスチェックURL' },
  confirmRefresh: 'サブスクリプション「{name}」を更新しますか？', confirmDeleteSub: 'サブスクリプション「{name}」とすべてのノードを削除しますか？', confirmHealthCheck: 'ノード「{name}」のヘルスチェックを実行しますか？', confirmDeleteNode: 'ノード「{name}」を削除しますか？', confirmBatchAll: 'すべてのノードを今すぐ一括ヘルスチェックしますか？スマート間隔をスキップするため、数十秒かかる場合があります。', confirmBatchSub: 'サブスクリプション「{name}」のすべてのノードを一括ヘルスチェックしますか？',
  batchResult: { healthAll: '一括ヘルスチェック完了: 成功 {ok} / 失敗 {failed} / スキップ {skipped}', healthSub: 'サブスクリプション「{name}」の一括ヘルスチェック: 成功 {ok} / 失敗 {failed}', swap: 'ノードへ強制切替しました: {name}', policySaved: 'ポリシーを保存し永続化しました' },
  error: { loadStatusFailed: 'ステータスの読み込みに失敗しました', loadSubsFailed: 'サブスクリプションの読み込みに失敗しました', loadNodesFailed: 'ノードの読み込みに失敗しました', nameUrlRequired: '名前とURLは必須です', subscribeUrlMustHttp: 'サブスクリプションURLは http:// または https:// で始まる必要があります', createSubFailed: 'サブスクリプションの作成に失敗しました', refreshSubFailed: 'サブスクリプションの更新に失敗しました', deleteSubFailed: 'サブスクリプションの削除に失敗しました', nodeFieldsRequired: '名前、サーバー、サブスクリプションは必須です', protocolNotDialable: 'HTTP/HTTPS/SOCKS5 のみ対応。trojan/vless はローカルブリッジ経由で公開する必要があります', createNodeFailed: 'ノードの作成に失敗しました', healthCheckFailed: 'ヘルスチェックに失敗しました', deleteNodeFailed: 'ノードの削除に失敗しました', batchHealthFailed: '一括ヘルスチェックに失敗しました', swapFailed: '強制切替に失敗しました', savePolicyFailed: 'ポリシーの保存に失敗しました', saveSubBanFailed: 'サブスクリプションの除外国の保存に失敗しました', saveNodeBanFailed: 'ノードの除外国の保存に失敗しました' },
}
