--
-- Name: request_logs_hot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.request_logs_hot (
    id bigint DEFAULT nextval('public.request_logs_id_seq'::regclass) NOT NULL,
    request_id text NOT NULL,
    ts timestamp with time zone NOT NULL,
    tenant_id text NOT NULL,
    application_id bigint,
    api_key_id bigint,
    end_user_id text,
    client_model text,
    outbound_model text,
    credential_id bigint,
    provider_id bigint,
    canonical_id bigint,
    client_profile text,
    request_mode text,
    prompt_tokens integer,
    completion_tokens integer,
    total_tokens integer,
    cost_usd numeric(14,8),
    latency_ms integer,
    success boolean NOT NULL,
    error_kind text,
    search_text text,
    cache_read_tokens integer,
    cache_write_tokens integer,
    identity_hash text,
    virtual_client_id text,
    virtual_ip text,
    virtual_mac text,
    affinity_hit boolean,
    stream_first_chunk_ms integer,
    stream_chunk_count integer,
    stream_interrupted boolean,
    stream_done_sent boolean,
    request_checksum text,
    response_checksum text,
    transform_rule_id text,
    egress_protocol text,
    failure_stage text,
    failure_detail_code text,
    request_preview text,
    transform_summary text,
    response_preview text,
    stream_done_received boolean,
    cost_display numeric(14,8),
    cost_currency text,
    usage_source text DEFAULT 'llm'::text NOT NULL,
    gw_session_id text,
    gw_task_id text,
    request_status text,
    api_key_prefix text,
    owner_user text,
    application_code text,
    key_alias text,
    api_key_owner_user text,
    is_auto_request boolean DEFAULT false,
    task_type text,
    auto_profile text,
    auto_decision jsonb,
    auto_confidence numeric(4,3),
    work_type text,
    task_type_chosen text,
    confidence_num numeric(4,3),
    model_chosen text,
    strategy_used text,
    credits_charged bigint,
    parent_request_id text,
    compression_reason text,
    compression_strategy text,
    compression_meta jsonb,
    outbound_msg_count integer,
    outbound_token_est integer,
    outbound_msg_hashes jsonb,
    quality_flags text[] DEFAULT '{}'::text[] NOT NULL,
    quality_fix_actions jsonb DEFAULT '{}'::jsonb NOT NULL,
    quality_score numeric(3,2),
    upstream_finish_reason text,
    tool_calls jsonb,
    client_endpoint text,
    client_timeout boolean,
    stream_chunk_errors integer,
    stream_chunks_sent integer DEFAULT 0 NOT NULL,
    client_request_id text,
    upstream_status_code integer,
    test_col text[] DEFAULT '{}'::text[] NOT NULL,
    test_tab_indent text,
    provider_model text,
    attachments jsonb,
    has_attachments boolean DEFAULT false,
    attachment_count integer DEFAULT 0,
    client_ip inet,
    caller_id text,
    session_correlation_id text,
    compression_start_index integer,
    compression_end_index integer,
    client_forwarded_for text,
    agent_name text,
    agent_type text,
    api_key_fingerprint text,
    customer_id text,
    upstream_endpoint text,
    session_title text,
    session_summary text,
    task_id text,
    task_title text,
    protocol_conversion text,
    ir_extensions text,
    sanitizer_mutations text,
    compression_ratio double precision,
    cache_hit boolean,
    cache_tokens_saved integer,
    content_safety_score double precision,
    dlp_violations text[],
    sensitive_keywords text[],
    vendor_metadata jsonb,
    client_protocol character varying(50),
    rate_limit_status character varying(50),
    upstream_protocol character varying(50),
    reasoning_tokens integer,
    image_tokens integer,
    audio_tokens integer,
    video_tokens integer,
    provider_tokens integer,
    origin_stage character varying(32) DEFAULT NULL::character varying,
    origin_actor character varying(255) DEFAULT NULL::character varying,
    routing_attempts jsonb,
    routing_summary text,
    trace_events jsonb,
    canonical_model text,
    t0_arrived_at timestamp with time zone,
    t1_total_enqueued_at timestamp with time zone,
    t2_total_dequeued_at timestamp with time zone,
    t3_model_enqueued_at timestamp with time zone,
    t4_model_dequeued_at timestamp with time zone,
    t5_cred_enqueued_at timestamp with time zone,
    t6_cred_dequeued_at timestamp with time zone,
    t7_forward_start_at timestamp with time zone,
    t8_response_start_at timestamp with time zone,
    t9_response_end_at timestamp with time zone,
    CONSTRAINT chk_compression_parent_single CHECK (((parent_request_id IS NULL) OR (compression_reason IS NOT NULL) OR (origin_actor IS NOT NULL))),
    CONSTRAINT request_logs_strategy_used_check CHECK (((strategy_used IS NULL) OR (strategy_used = ANY (ARRAY['baseline_heuristic'::text, 'pattern_layered'::text, 'llm_fallback'::text]))))
)
WITH (autovacuum_enabled='true', autovacuum_vacuum_scale_factor='0.05', autovacuum_vacuum_threshold='10', autovacuum_analyze_scale_factor='0.02', autovacuum_analyze_threshold='50');
