package secrets

import (
	"fmt"
	"os"
	"strings"
)

// EnvFile .env 文件读写（强制 LF 无 BOM）
type EnvFile struct {
	Path string
}

// NewEnvFile 创建 EnvFile
func NewEnvFile(path string) *EnvFile {
	return &EnvFile{Path: path}
}

// Write 写入 .env 文件（覆盖现有）
// entries: key=value 列表，value 中的特殊字符会自动加引号
func (e *EnvFile) Write(entries map[string]string) error {
	var sb strings.Builder
	sb.WriteString("# llm-gateway-go .env (generated by llm-gw-installer)\n")
	sb.WriteString("# DO NOT EDIT MANUALLY - re-run installer to regenerate\n")
	sb.WriteString("# Permissions: 600\n\n")

	// 保持稳定顺序：先按字母序
	keys := make([]string, 0, len(entries))
	for k := range entries {
		keys = append(keys, k)
	}

	for _, k := range keys {
		v := entries[k]
		sb.WriteString(fmt.Sprintf("%s=%s\n", k, quoteValue(v)))
	}

	// 强制 LF 换行（Windows 兼容）
	content := strings.ReplaceAll(sb.String(), "\r\n", "\n")

	// 写文件
	if err := os.WriteFile(e.Path, []byte(content), 0600); err != nil {
		return fmt.Errorf("写入 .env 失败: %w", err)
	}

	return nil
}

// Read 读取现有 .env 文件
func (e *EnvFile) Read() (map[string]string, error) {
	data, err := os.ReadFile(e.Path)
	if err != nil {
		if os.IsNotExist(err) {
			return make(map[string]string), nil
		}
		return nil, err
	}

	result := make(map[string]string)
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(parts[0])
		val := strings.TrimSpace(parts[1])
		// 去掉引号
		val = unquoteValue(val)
		result[key] = val
	}
	return result, nil
}

// Exists 检查 .env 是否存在
func (e *EnvFile) Exists() bool {
	_, err := os.Stat(e.Path)
	return err == nil
}

// quoteValue 自动加引号（含空格或特殊字符时）
func quoteValue(v string) string {
	needsQuote := false
	for _, c := range v {
		if c == ' ' || c == '$' || c == '`' || c == '"' || c == '\'' || c == '\\' || c == '#' {
			needsQuote = true
			break
		}
	}
	if !needsQuote {
		return v
	}
	// 用单引号包裹，内部单引号用 '\'' 转义
	return "'" + strings.ReplaceAll(v, "'", `'\''`) + "'"
}

// unquoteValue 去掉引号
func unquoteValue(v string) string {
	if len(v) >= 2 && v[0] == '\'' && v[len(v)-1] == '\'' {
		v = v[1 : len(v)-1]
		v = strings.ReplaceAll(v, `'\''`, "'")
	} else if len(v) >= 2 && v[0] == '"' && v[len(v)-1] == '"' {
		v = v[1 : len(v)-1]
	}
	return v
}
