package settings

// GoalSpecs returns the configuration specs for goal mode feature.
func GoalSpecs() []Spec {
	return []Spec{
		{
			Key:             "goal.enabled",
			EnvName:         "LLM_GATEWAY_GOAL_ENABLED",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         false,
			Description:     "启用Goal模式",
			DescriptionLong: "启用后，系统会自动检测需要持续执行的任务并进行自动化管理",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.detection_mode",
			EnvName:         "LLM_GATEWAY_GOAL_DETECTION_MODE",
			Type:            TypeEnum,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         "hybrid",
			Options:         []string{"keyword", "explicit", "llm", "hybrid"},
			Description:     "Goal模式检测方式",
			DescriptionLong: "keyword=关键词检测，explicit=明确标记，llm=LLM分类，hybrid=混合方式",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.auto_select_recommended",
			EnvName:         "LLM_GATEWAY_GOAL_AUTO_SELECT",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         true,
			Description:     "自动选择推荐选项",
			DescriptionLong: "当LLM需要用户选择时，自动选择标记为Recommended的选项",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.auto_continue_on_pause",
			EnvName:         "LLM_GATEWAY_GOAL_AUTO_CONTINUE",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         true,
			Description:     "暂停时自动继续",
			DescriptionLong: "当会话暂停时，自动发送\"请继续下一步\"指令",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.max_retry_count",
			EnvName:         "LLM_GATEWAY_GOAL_MAX_RETRY",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         3,
			Min:             floatPtr(1),
			Max:             floatPtr(10),
			Description:     "最大重试次数",
			DescriptionLong: "网络错误或超时时的最大自动重试次数",
			Unit:            "次",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.max_auto_continue_count",
			EnvName:         "LLM_GATEWAY_GOAL_MAX_AUTO_CONTINUE",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         10,
			Min:             floatPtr(1),
			Max:             floatPtr(50),
			Description:     "最大自动继续次数",
			DescriptionLong: "防止无限循环的自动继续次数上限",
			Unit:            "次",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.use_autoroute_for_audit",
			EnvName:         "LLM_GATEWAY_GOAL_USE_AUTOROUTE_AUDIT",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         true,
			Description:     "审计时使用自动路由",
			DescriptionLong: "使用autoroute的code_audit任务类型自动选择最佳审计模型（推荐启用）",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.use_autoroute_for_intent",
			EnvName:         "LLM_GATEWAY_GOAL_USE_AUTOROUTE_INTENT",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         true,
			Description:     "意图检测使用自动路由",
			DescriptionLong: "使用autoroute的intent_classification任务类型自动选择模型",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.fallback_audit_model",
			EnvName:         "LLM_GATEWAY_GOAL_FALLBACK_AUDIT_MODEL",
			Type:            TypeString,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         "auto",
			Description:     "审计备用模型",
			DescriptionLong: "当autoroute不可用时使用的备用模型",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.auto_fix_enabled",
			EnvName:         "LLM_GATEWAY_GOAL_AUTO_FIX",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         false,
			Description:     "启用自动修复",
			DescriptionLong: "审计发现问题后，自动应用修正建议（高风险，建议人工审核）",
			HotReload:       true,
			DangerLevel:     Dangerous,
		},
		{
			Key:             "goal.audit_enabled",
			EnvName:         "LLM_GATEWAY_GOAL_AUDIT_ENABLED",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         false,
			Description:     "启用任务完成后审计",
			DescriptionLong: "任务完成后使用LLM审计执行结果，识别潜在问题",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.audit_model",
			EnvName:         "LLM_GATEWAY_GOAL_AUDIT_MODEL",
			Type:            TypeString,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         "auto",
			Description:     "审计使用的模型",
			DescriptionLong: "执行审计的LLM模型，auto表示使用autoroute选择",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.audit_min_confidence",
			EnvName:         "LLM_GATEWAY_GOAL_AUDIT_MIN_CONFIDENCE",
			Type:            TypeFloat,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         0.7,
			Min:             floatPtr(0.0),
			Max:             floatPtr(1.0),
			Description:     "审计最低置信度",
			DescriptionLong: "审计结果置信度低于此值将被标记为不可信",
			HotReload:       true,
			DangerLevel:     Safe,
		},

		// ── Loop detection & model switching (2026-07-06) ─────────────────
		// When the continue budget is exhausted OR the model repeats itself,
		// goal mode can rotate to a different model and retry, instead of
		// giving up or looping forever on a stuck model.
		{
			Key:             "goal.model_switch_on_loop",
			EnvName:         "LLM_GATEWAY_GOAL_MODEL_SWITCH_ON_LOOP",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         true,
			Description:     "死循环时切换模型",
			DescriptionLong: "检测到死循环（续跑预算耗尽或响应重复）时，自动切换到备选模型重试，而不是放弃或无限循环",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.max_model_switch_count",
			EnvName:         "LLM_GATEWAY_GOAL_MAX_MODEL_SWITCH",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         3,
			Min:             floatPtr(0),
			Max:             floatPtr(20),
			Description:     "最大模型切换次数",
			DescriptionLong: "单会话最多切换几次模型。超过后放弃续跑，避免无限切换。0 表示禁止切换",
			Unit:            "次",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.fallback_models",
			EnvName:         "LLM_GATEWAY_GOAL_FALLBACK_MODELS",
			Type:            TypeString,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         "",
			Description:     "备选模型列表",
			DescriptionLong: "逗号分隔的模型名，死循环时依次切换。留空或填 auto 表示走 autoroute 自动选模型。例如: auto,gpt-4o,claude-3-5-sonnet",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.repeat_detection_enabled",
			EnvName:         "LLM_GATEWAY_GOAL_REPEAT_DETECTION",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         true,
			Description:     "启用重复响应检测",
			DescriptionLong: "连续相同响应达到阈值时判定为死循环并触发模型切换",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.repeat_threshold",
			EnvName:         "LLM_GATEWAY_GOAL_REPEAT_THRESHOLD",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         3,
			Min:             floatPtr(2),
			Max:             floatPtr(20),
			Description:     "重复响应判定阈值",
			DescriptionLong: "连续相同响应次数达到此值判定为死循环。0 表示禁用重复检测",
			Unit:            "次",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.completion_confidence",
			EnvName:         "LLM_GATEWAY_GOAL_COMPLETION_CONFIDENCE",
			Type:            TypeFloat,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         0.8,
			Min:             floatPtr(0.0),
			Max:             floatPtr(1.0),
			Description:     "完成检测最低置信度",
			DescriptionLong: "LLM 完成度分析的最低置信度阈值，低于此值不判定为完成，继续续跑。越低越容易判定完成（续跑更少），越高越保守",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.max_follow_up_depth",
			EnvName:         "LLM_GATEWAY_GOAL_MAX_FOLLOW_UP_DEPTH",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         5,
			Min:             floatPtr(1),
			Max:             floatPtr(20),
			Description:     "续跑递归最大深度",
			DescriptionLong: "单个请求链路（含模型切换）的最大递归 follow-up 深度，防止放大成本。0 表示用系统默认值",
			Unit:            "层",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.max_follow_ups_per_session",
			EnvName:         "LLM_GATEWAY_GOAL_MAX_FOLLOW_UPS_PER_SESSION",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         50,
			Min:             floatPtr(1),
			Max:             floatPtr(500),
			Description:     "单会话续跑总次数上限",
			DescriptionLong: "单会话允许的 follow-up 续跑总次数硬上限（含模型切换），防止死循环放大成本。0 表示用系统默认值",
			Unit:            "次",
			HotReload:       true,
			DangerLevel:     Warning,
		},
	}
}
