package settings

// GoalSpecs returns the configuration specs for goal mode feature.
func GoalSpecs() []Spec {
	return []Spec{
		{
			Key:             "goal.enabled",
			EnvName:         "LLM_GATEWAY_GOAL_ENABLED",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         false,
			Description:     "启用Goal模式",
			DescriptionLong: "启用后，系统会自动检测需要持续执行的任务并进行自动化管理。模块级主开关，由 admin/modules 页面统一管理；具体策略（detection_mode、auto_continue_on_pause 等）仍按租户粒度配置。",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		// ── Cost Mode (2026-07-19, Phase 0) ───────────────────────────────
		// Three-tier cost control: minimal (+20%), balanced (+140%), aggressive (+252%).
		// Each mode is a complete preset bundle (retry, continue, audit, fix, budget).
		// Users select one mode instead of tuning dozens of individual settings.
		// See: docs/会话优化v2/18-Goal模式成本控制与分级方案.md
		{
			Key:             "goal.cost_mode",
			EnvName:         "LLM_GATEWAY_GOAL_COST_MODE",
			Type:            TypeEnum,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         "minimal",
			Options:         []string{"minimal", "balanced", "aggressive"},
			Description:     "成本控制模式",
			DescriptionLong: "三级成本模式：minimal(+20%成本，仅重试)、balanced(+140%，重试+自动继续)、aggressive(+252%，全自动含审计修正)。选择一个模式即可，无需逐项配置。",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.retry_on_error",
			EnvName:         "LLM_GATEWAY_GOAL_RETRY_ON_ERROR",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         false,
			Description:     "LLM错误时自动重试",
			DescriptionLong: "LLM返回错误（5xx、timeout、no_candidates等）时延时后自动重试。由cost_mode预设控制，一般无需单独配置。",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.retry_delay_seconds",
			EnvName:         "LLM_GATEWAY_GOAL_RETRY_DELAY_SECONDS",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         20,
			Min:             floatPtr(5),
			Max:             floatPtr(60),
			Description:     "重试延时（秒）",
			DescriptionLong: "LLM错误后延时多少秒再重试。由cost_mode预设控制。",
			Unit:            "秒",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.retry_total_timeout_seconds",
			EnvName:         "LLM_GATEWAY_GOAL_RETRY_TOTAL_TIMEOUT",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         50,
			Min:             floatPtr(10),
			Max:             floatPtr(300),
			Description:     "重试总超时（秒）",
			DescriptionLong: "所有重试的总超时时间，防止超过客户端超时限制。由cost_mode预设控制。",
			Unit:            "秒",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.retriable_errors",
			EnvName:         "LLM_GATEWAY_GOAL_RETRIABLE_ERRORS",
			Type:            TypeString,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         "5xx,timeout,no_candidates,rate_limit,overloaded",
			Description:     "可重试的错误类型",
			DescriptionLong: "逗号分隔的错误类型列表，匹配这些错误时触发重试。",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.monthly_token_limit",
			EnvName:         "LLM_GATEWAY_GOAL_MONTHLY_TOKEN_LIMIT",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         500000,
			Min:             floatPtr(0),
			Max:             floatPtr(100000000),
			Description:     "月度token限额",
			DescriptionLong: "租户级Goal模式月度token消耗上限，防止成本失控。由cost_mode预设控制。0表示无限制。",
			Unit:            "tokens",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.session_token_budget",
			EnvName:         "LLM_GATEWAY_GOAL_SESSION_TOKEN_BUDGET",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         30000,
			Min:             floatPtr(0),
			Max:             floatPtr(10000000),
			Description:     "单次任务token预算",
			DescriptionLong: "单个Goal会话的token消耗上限，超过后停止自动化。由cost_mode预设控制。0表示无限制。",
			Unit:            "tokens",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.cost_alert_threshold",
			EnvName:         "LLM_GATEWAY_GOAL_COST_ALERT_THRESHOLD",
			Type:            TypeFloat,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         0.85,
			Min:             floatPtr(0.0),
			Max:             floatPtr(1.0),
			Description:     "成本告警阈值",
			DescriptionLong: "月度使用量达到限额的此比例时触发告警。由cost_mode预设控制。",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.downgrade_on_budget",
			EnvName:         "LLM_GATEWAY_GOAL_DOWNGRADE_ON_BUDGET",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         true,
			Description:     "预算不足时自动降级",
			DescriptionLong: "月度token接近限额时自动降级到minimal模式，仅保留重试能力。由cost_mode预设控制。",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.auto_fix_severity_threshold",
			EnvName:         "LLM_GATEWAY_GOAL_AUTO_FIX_SEVERITY",
			Type:            TypeEnum,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         "high",
			Options:         []string{"high", "medium", "low"},
			Description:     "自动修正严重程度阈值",
			DescriptionLong: "自动修正哪些严重程度的问题。high=仅高危、medium=高危+中危、low=全部。由cost_mode预设控制。",
			HotReload:       true,
			DangerLevel:     Dangerous,
		},
		{
			Key:             "goal.detection_mode",
			EnvName:         "LLM_GATEWAY_GOAL_DETECTION_MODE",
			Type:            TypeEnum,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         "hybrid",
			Options:         []string{"keyword", "explicit", "llm", "hybrid"},
			Description:     "Goal模式检测方式",
			DescriptionLong: "keyword=关键词检测，explicit=明确标记，llm=LLM分类，hybrid=混合方式",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.auto_select_recommended",
			EnvName:         "LLM_GATEWAY_GOAL_AUTO_SELECT",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         true,
			Description:     "自动选择推荐选项",
			DescriptionLong: "当LLM需要用户选择时，自动选择标记为Recommended的选项",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.auto_continue_on_pause",
			EnvName:         "LLM_GATEWAY_GOAL_AUTO_CONTINUE",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         true,
			Description:     "暂停时自动继续",
			DescriptionLong: "当会话暂停时，自动发送\"请继续下一步\"指令",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.max_retry_count",
			EnvName:         "LLM_GATEWAY_GOAL_MAX_RETRY",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         3,
			Min:             floatPtr(1),
			Max:             floatPtr(10),
			Description:     "最大重试次数",
			DescriptionLong: "网络错误或超时时的最大自动重试次数",
			Unit:            "次",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:      "goal.max_auto_continue_count",
			EnvName:  "LLM_GATEWAY_GOAL_MAX_AUTO_CONTINUE",
			Type:     TypeInt,
			Scope:    ScopeTenant,
			Category: CategorySession,
			// Default 3 (not a larger value): the per-model continue budget must
			// fit within goal.max_follow_up_depth's worst-case chain
			// (max_auto_continue_count × (max_model_switch_count+1) + audit).
			// With defaults 3×4=12 ≤ depth 15. A larger default would be silently
			// truncated by the follow-up depth guard, defeating budget-exhaustion
			// model switching.
			Default:         3,
			Min:             floatPtr(1),
			Max:             floatPtr(50),
			Description:     "最大自动继续次数",
			DescriptionLong: "防止无限循环的自动继续次数上限",
			Unit:            "次",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.use_autoroute_for_audit",
			EnvName:         "LLM_GATEWAY_GOAL_USE_AUTOROUTE_AUDIT",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         true,
			Description:     "审计时使用自动路由",
			DescriptionLong: "使用autoroute的code_audit任务类型自动选择最佳审计模型（推荐启用）",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.use_autoroute_for_intent",
			EnvName:         "LLM_GATEWAY_GOAL_USE_AUTOROUTE_INTENT",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         true,
			Description:     "意图检测使用自动路由",
			DescriptionLong: "使用autoroute的intent_classification任务类型自动选择模型",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.fallback_audit_model",
			EnvName:         "LLM_GATEWAY_GOAL_FALLBACK_AUDIT_MODEL",
			Type:            TypeString,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         "auto",
			Description:     "审计备用模型",
			DescriptionLong: "当autoroute不可用时使用的备用模型",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.auto_fix_enabled",
			EnvName:         "LLM_GATEWAY_GOAL_AUTO_FIX",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         false,
			Description:     "启用自动修复",
			DescriptionLong: "审计发现问题后，自动应用修正建议（高风险，建议人工审核）",
			HotReload:       true,
			DangerLevel:     Dangerous,
		},
		{
			Key:             "goal.audit_enabled",
			EnvName:         "LLM_GATEWAY_GOAL_AUDIT_ENABLED",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         false,
			Description:     "启用任务完成后审计",
			DescriptionLong: "任务完成后使用LLM审计执行结果，识别潜在问题",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.audit_model",
			EnvName:         "LLM_GATEWAY_GOAL_AUDIT_MODEL",
			Type:            TypeString,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         "auto",
			Description:     "审计使用的模型",
			DescriptionLong: "执行审计的LLM模型，auto表示使用autoroute选择",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.audit_min_confidence",
			EnvName:         "LLM_GATEWAY_GOAL_AUDIT_MIN_CONFIDENCE",
			Type:            TypeFloat,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         0.7,
			Min:             floatPtr(0.0),
			Max:             floatPtr(1.0),
			Description:     "审计最低置信度",
			DescriptionLong: "审计结果置信度低于此值将被标记为不可信",
			HotReload:       true,
			DangerLevel:     Safe,
		},

		// ── Loop detection & model switching (2026-07-06) ─────────────────
		// When the continue budget is exhausted OR the model repeats itself,
		// goal mode can rotate to a different model and retry, instead of
		// giving up or looping forever on a stuck model.
		{
			Key:             "goal.model_switch_on_loop",
			EnvName:         "LLM_GATEWAY_GOAL_MODEL_SWITCH_ON_LOOP",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         true,
			Description:     "死循环时切换模型",
			DescriptionLong: "检测到死循环（续跑预算耗尽或响应重复）时，自动切换到备选模型重试，而不是放弃或无限循环",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.max_model_switch_count",
			EnvName:         "LLM_GATEWAY_GOAL_MAX_MODEL_SWITCH",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         3,
			Min:             floatPtr(0),
			Max:             floatPtr(20),
			Description:     "最大模型切换次数",
			DescriptionLong: "单会话最多切换几次模型。超过后放弃续跑，避免无限切换。0 表示禁止切换",
			Unit:            "次",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.fallback_models",
			EnvName:         "LLM_GATEWAY_GOAL_FALLBACK_MODELS",
			Type:            TypeString,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         "",
			Description:     "备选模型列表",
			DescriptionLong: "逗号分隔的模型名，死循环时依次切换。留空或填 auto 表示走 autoroute 自动选模型。例如: auto,gpt-4o,claude-3-5-sonnet",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.repeat_detection_enabled",
			EnvName:         "LLM_GATEWAY_GOAL_REPEAT_DETECTION",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         true,
			Description:     "启用重复响应检测",
			DescriptionLong: "连续相同响应达到阈值时判定为死循环并触发模型切换",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.repeat_threshold",
			EnvName:         "LLM_GATEWAY_GOAL_REPEAT_THRESHOLD",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         3,
			Min:             floatPtr(2),
			Max:             floatPtr(20),
			Description:     "重复响应判定阈值",
			DescriptionLong: "连续相同响应次数达到此值判定为死循环。0 表示禁用重复检测",
			Unit:            "次",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.completion_confidence",
			EnvName:         "LLM_GATEWAY_GOAL_COMPLETION_CONFIDENCE",
			Type:            TypeFloat,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         0.8,
			Min:             floatPtr(0.0),
			Max:             floatPtr(1.0),
			Description:     "完成检测最低置信度",
			DescriptionLong: "LLM 完成度分析的最低置信度阈值，低于此值不判定为完成，继续续跑。越低越容易判定完成（续跑更少），越高越保守",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:      "goal.max_follow_up_depth",
			EnvName:  "LLM_GATEWAY_GOAL_MAX_FOLLOW_UP_DEPTH",
			Type:     TypeInt,
			Scope:    ScopeTenant,
			Category: CategorySession,
			// Default 15: must exceed the worst-case goal loop depth
			// (max_auto_continue_count × (max_model_switch_count+1) + audit margin).
			// With defaults 3×4=12 + audit ≈ 14 ≤ 15. A smaller default would
			// truncate the loop before the continue budget is exhausted, silently
			// disabling budget-exhaustion model switching.
			Default:         15,
			Min:             floatPtr(1),
			Max:             floatPtr(50),
			Description:     "续跑递归最大深度",
			DescriptionLong: "单个请求链路（含模型切换）的最大递归 follow-up 深度，防止放大成本。0 表示用系统默认值",
			Unit:            "层",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.max_follow_ups_per_session",
			EnvName:         "LLM_GATEWAY_GOAL_MAX_FOLLOW_UPS_PER_SESSION",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         50,
			Min:             floatPtr(1),
			Max:             floatPtr(500),
			Description:     "单会话续跑总次数上限",
			DescriptionLong: "单会话允许的 follow-up 续跑总次数硬上限（含模型切换），防止死循环放大成本。0 表示用系统默认值",
			Unit:            "次",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.client_signal_enabled",
			EnvName:         "LLM_GATEWAY_GOAL_CLIENT_DRIVEN",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         false,
			Description:     "启用客户端驱动的 Goal 控制信号",
			DescriptionLong: "仅当客户端通过 X-Gw-Capabilities 声明 continue 或 handoff 时，网关才以控制信号替代服务端 follow-up。关闭时保留历史服务端续跑行为。",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "goal.client_signal_mode",
			EnvName:         "LLM_GATEWAY_GOAL_CLIENT_SIGNAL_MODE",
			Type:            TypeEnum,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         "auto",
			Options:         []string{"auto", "continue", "handoff", "both"},
			Description:     "客户端 Goal 控制信号模式",
			DescriptionLong: "auto 根据上下文阈值选择 continue 或 handoff；continue 只允许同会话继续；handoff 只允许会话迁移；both 允许两者。",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "goal.handoff_signal_threshold_tokens",
			EnvName:         "LLM_GATEWAY_GOAL_HANDOFF_SIGNAL_THRESHOLD",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         200000,
			Min:             floatPtr(1),
			Max:             floatPtr(10000000),
			Description:     "触发 handoff 信号的上下文 token 阈值",
			DescriptionLong: "任务未完成且 token 使用量达到该值时，支持 handoff 的客户端会收到 gw-handoff，而不是 gw-continue。",
			Unit:            "tokens",
			HotReload:       true,
			DangerLevel:     Warning,
		},
	}
}
