package settings

// HandoffSpecs returns the configuration specs for automatic handoff feature.
func HandoffSpecs() []Spec {
	return []Spec{
		{
			Key:             "handoff.auto_control.enabled",
			EnvName:         "LLM_GATEWAY_HANDOFF_AUTO_ENABLED",
			Type:            TypeBool,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         false,
			Description:     "启用自动Handoff功能",
			DescriptionLong: "当会话上下文达到阈值时，自动触发handoff流程，保存状态并生成新会话提示词。注意：此键与压缩模块的 handoff.enabled 不同。",
			HotReload:       true,
			DangerLevel:     Warning,
		},
		{
			Key:             "handoff.auto_control.absolute_threshold",
			EnvName:         "LLM_GATEWAY_HANDOFF_ABSOLUTE_THRESHOLD",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         180000,
			Min:             floatPtr(10000),
			Max:             floatPtr(2000000),
			Description:     "Handoff绝对token阈值",
			DescriptionLong: "当会话总token数达到此阈值时触发handoff（默认180K）",
			Unit:            "tokens",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "handoff.auto_control.percentage_threshold",
			EnvName:         "LLM_GATEWAY_HANDOFF_PERCENTAGE_THRESHOLD",
			Type:            TypeFloat,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         0.8,
			Min:             floatPtr(0.5),
			Max:             floatPtr(0.95),
			Description:     "Handoff百分比阈值",
			DescriptionLong: "当会话token数达到模型上下文窗口的此百分比时触发handoff（默认80%）",
			Unit:            "%",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "handoff.auto_control.message_threshold",
			EnvName:         "LLM_GATEWAY_HANDOFF_MESSAGE_THRESHOLD",
			Type:            TypeInt,
			Scope:           ScopeTenant,
			Category:        CategorySession,
			Default:         0,
			Min:             floatPtr(0),
			Max:             floatPtr(1000),
			Description:     "Handoff消息数量阈值（0=禁用）",
			DescriptionLong: "当会话消息数达到此阈值时触发handoff（默认禁用）",
			Unit:            "条",
			HotReload:       true,
			DangerLevel:     Safe,
		},
		{
			Key:             "handoff.auto_control.skill_name",
			EnvName:         "LLM_GATEWAY_HANDOFF_SKILL_NAME",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         "handoff",
			Description:     "Handoff使用的skill名称",
			DescriptionLong: "触发handoff时调用的skill名称（如/handoff）",
			HotReload:       true,
			DangerLevel:     Safe,
		},
	}
}
