package settings

import "encoding/json"

// CategoryModules groups all module-level settings together
const CategoryModules Category = "modules"

// ModuleSpecs returns all platform-scoped module management specs.
// Each feature module gets an enable/disable toggle; new enterprise
// integrations (Feishu bot, webhook, etc.) are defined here as well.
func ModuleSpecs() []*Spec {
	return []*Spec{
		// ── Audit logging ─────────────────────────────────────────────
		{
			Key:             "audit.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "审计日志",
			DescriptionLong: "记录所有 API 请求的审计追踪（谁、何时、做了什么）。关闭后仍保留当前请求的部分关键日志，但审计管理页面将不可用。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "prompt_injection.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "提示词注入检测",
			DescriptionLong: "LLM-as-judge 检测提示词注入攻击和角色劫持。仅检测模式，不拦截请求。关闭后完全跳过注入分析。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "输出合规检测",
			DescriptionLong: "检查 LLM 输出是否包含敏感数据（PII、密钥、内部 IP 等）。发现时触发告警或脱敏。关闭后跳过所有输出检查。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "session_audit.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "会话审计与审批",
			DescriptionLong: "高风险会话自动触发审计审批流程。管理员可以批准/拒绝高风险操作。关闭后所有会话直接放行。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "session_inspector.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "会话健康检查",
			DescriptionLong: "监控会话 token 限制、不活跃超时、高频请求等健康指标。关闭后跳过所有会话健康检查。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "security.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "安全检测（意图+威胁）",
			DescriptionLong: "意图分析与威胁检测引擎。识别恶意意图（越狱、数据泄露）并触发预设响应策略。关闭后跳过所有安全检测。",
			DangerLevel:     Dangerous,
			HotReload:       true,
		},
		// ── Security Engine - Detection Mode ────────────────────────────
		{
			Key:             "security.mode",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "observe",
			Description:     "检测模式",
			DescriptionLong: "observe=仅记录不拦截（推荐测试期），enforce=高风险请求直接阻断。切换到强制模式前请确保已完成充分测试。",
			DangerLevel:     Dangerous,
			HotReload:       true,
			Options:         []string{"observe", "enforce"},
		},
		// ── Security Engine - LLM Model Configuration ───────────────────
		{
			Key:             "security.llm.intent_model",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "gpt-4o-mini",
			Description:     "意图分析模型",
			DescriptionLong: "用于意图分类的LLM模型。推荐使用轻量模型（gpt-4o-mini/Claude Haiku）以降低延迟和成本。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.llm.threat_model",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "gpt-4o-mini",
			Description:     "威胁检测模型",
			DescriptionLong: "用于威胁评分的LLM模型。需要较强的推理能力，推荐 gpt-4o-mini 或更高版本。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		// ── Security Engine - Intent Analysis ───────────────────────────
		{
			Key:             "security.intent.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "启用意图分析",
			DescriptionLong: "分析用户请求的意图类型（代码/聊天/有害等）。基于关键词和LLM的混合分类。关闭后跳过意图分析。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.intent.confidence_threshold",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         0.7,
			Description:     "意图置信度阈值",
			DescriptionLong: "意图分类的置信度阈值（0-1）。低于此值的分类结果将标记为unknown。建议0.6-0.8。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "security.intent.drift_threshold",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         0.5,
			Description:     "意图漂移阈值",
			DescriptionLong: "意图漂移检测阈值（0-1）。超过此值表示会话意图发生显著变化，可能需要重新路由。基于KL散度计算。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		// ── Security Engine - Threat Detection ──────────────────────────
		{
			Key:             "security.threat.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "启用威胁检测",
			DescriptionLong: "检测请求中的安全威胁（注入、越狱、数据泄露等）。基于规则+LLM的双层检测。关闭后跳过所有威胁检测。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.threat.severity_threshold",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         7,
			Description:     "威胁严重度阈值（高风险）",
			DescriptionLong: "severity >= 7 视为高风险，触发 security.response.high_risk 动作。建议7-8。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.threat.risk_level.low_threshold",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         3,
			Description:     "低风险阈值",
			DescriptionLong: "severity < 3 视为正常通过，3 ≤ severity < 5 视为低风险，触发 security.response.low_risk 动作。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "security.threat.risk_level.medium_threshold",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         5,
			Description:     "中风险阈值",
			DescriptionLong: "5 ≤ severity < 7 视为中风险，触发 security.response.medium_risk 动作。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "security.threat.checks.prompt_inject",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "提示词注入检测",
			DescriptionLong: "检测提示词注入攻击（忽略指令、角色切换等）。依赖：prompt_injection 模块。关闭后不检测注入类威胁。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.threat.checks.jailbreak",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "越狱攻击检测",
			DescriptionLong: "检测越狱尝试（DAN模式、开发者模式等）。基于30+正则模式库。关闭后不检测越狱类威胁。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.threat.checks.data_leak",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "数据泄露检测",
			DescriptionLong: "检测敏感数据泄露（API密钥、内部IP等）。依赖：output_compliance 模块。关闭后不检测数据泄露。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.threat.checks.pii",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "PII检测",
			DescriptionLong: "检测个人信息（身份证、手机号、邮箱等）。依赖：output_compliance 模块。关闭后不检测PII。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.threat.checks.persona_override",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "角色劫持检测",
			DescriptionLong: "检测角色劫持尝试（假装是管理员、root等）。基于关键词模式匹配。关闭后不检测角色劫持。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		// ── Security Engine - Response Strategy ─────────────────────────
		{
			Key:             "security.response.low_risk",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "log",
			Description:     "低风险响应动作",
			DescriptionLong: "低风险威胁的响应动作：log=仅记录日志，warn=记录+告警。",
			DangerLevel:     Safe,
			HotReload:       true,
			Options:         []string{"log", "warn"},
		},
		{
			Key:             "security.response.medium_risk",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "warn",
			Description:     "中风险响应动作",
			DescriptionLong: "中风险威胁的响应动作：warn=警告，sanitize=清洗内容，block=阻断请求，approval=人工审批。",
			DangerLevel:     Warning,
			HotReload:       true,
			Options:         []string{"warn", "sanitize", "block", "approval"},
		},
		{
			Key:             "security.response.high_risk",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "block",
			Description:     "高风险响应动作",
			DescriptionLong: "高风险威胁的响应动作：block=直接阻断，approval=人工审批。依赖：session_audit 模块（审批功能）。",
			DangerLevel:     Dangerous,
			HotReload:       true,
			Options:         []string{"block", "approval"},
		},
		// ── Security Engine - Audit Integration ─────────────────────────
		{
			Key:             "security.audit.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "启用审计联动",
			DescriptionLong: "将安全检测结果写入审计日志。依赖：session_audit 模块。关闭后检测结果不进入审计流程。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "security.audit.log_all",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "记录所有检测结果",
			DescriptionLong: "记录所有请求的检测结果（包括安全通过的）。依赖：audit 模块。开启后会增加存储消耗。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "security.audit.sampling_rate",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         1.0,
			Description:     "审计采样率",
			DescriptionLong: "安全审计的采样率（0-1）。1.0=全量记录，0.1=10%采样。高流量场景可降低以减少存储压力。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		// ── Rate Limiting ──────────────────────────────────────────────
		{
			Key:             "rate_limit.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "限流控制",
			DescriptionLong: "RPM / 并发 / TPM 多维度流量控制。关闭后将不限制任何请求速率（危险操作，仅限调试场景）。",
			DangerLevel:     Breaking,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "飞书机器人集成",
			DescriptionLong: "对接飞书机器人实现远程运维：告警通知、审批执行、状态查询。需要先配置 Webhook URL 和验证令牌。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.webhook_url",
			Type:            TypeURL,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "飞书机器人 Webhook URL",
			DescriptionLong: "飞书自定义机器人的 Webhook 地址（格式：https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxx）。必须先启用飞书机器人模块。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.verify_token",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "飞书机器人验证令牌",
			DescriptionLong: "用于验证飞书回调请求来源的签名令牌。可在飞书机器人安全设置中获取。留空则不验证签名。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.notify_on_alert",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "告警推送",
			DescriptionLong: "当系统检测到异常（注入攻击、高延迟、错误率飙升）时自动推送飞书消息。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.notify_on_approval",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "审批通知",
			DescriptionLong: "高风险会话需要审批时通过飞书通知管理员。管理员可直接在飞书消息中操作审批。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.allowed_users",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "飞书白名单用户",
			DescriptionLong: "允许通过飞书执行操作的用户 OpenID 列表（逗号分隔）。留空表示允许所有已绑定用户。",
			DangerLevel:     Safe,
			HotReload:       true,
		},

		// ── WeChat bot (企业微信机器人) ────────────────────────────────
		{
			Key:             "wechat_bot.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "微信机器人集成",
			DescriptionLong: "对接企业微信自定义机器人，实现远程运维通知、风险告警推送、审批操作执行等功能。依赖压缩管理、提示词注入检测、会话缓存、会话审计与审批等模块。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "wechat_bot.webhook_url",
			Type:            TypeURL,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "企业微信群机器人 Webhook URL",
			DescriptionLong: "企业微信群机器人的 Webhook 地址（格式：https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxx）。配置后通过群机器人推送消息，无需 access_token。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "wechat_bot.corp_id",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "企业 CorpID",
			DescriptionLong: "企业微信的企业 ID（CorpID）。在企业管理后台「我的企业」页面获取。配置后可使用应用消息推送（比群机器人更灵活）。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "wechat_bot.agent_id",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "应用 AgentID",
			DescriptionLong: "企业微信自建应用的 AgentID。在应用管理页面创建应用后获取。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "wechat_bot.corp_secret",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "应用 Secret",
			DescriptionLong: "企业微信自建应用的 Secret（敏感信息，不会出现在日志中）。在应用管理页面获取，用于获取 access_token。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "wechat_bot.encoding_aes_key",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "回调加密 EncodingAESKey",
			DescriptionLong: "企业微信回调加密的 AES Key（43 字符）。在应用的「接收消息」设置中生成。配置后回调消息将使用 AES-CBC 解密。留空则按明文处理。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "wechat_bot.verify_token",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "回调验证 Token",
			DescriptionLong: "企业微信回调验证令牌。在应用的「接收消息」设置中自定义。用于验证回调请求来源的 SHA1 签名。留空则不验证签名。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "wechat_bot.notify_on_alert",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "安全告警推送",
			DescriptionLong: "当系统检测到安全异常（提示词注入攻击、角色劫持等）时自动推送微信消息。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "wechat_bot.notify_on_approval",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "审批通知",
			DescriptionLong: "高风险会话需要审批时通过微信通知管理员。管理员可直接在微信消息中操作审批。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "wechat_bot.notify_on_latency",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "高延迟告警",
			DescriptionLong: "当请求延迟超过阈值时自动推送告警。延迟阈值通过 wechat_bot.latency_threshold_ms 配置。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "wechat_bot.notify_on_error_rate",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "错误率飙升告警",
			DescriptionLong: "当错误率超过阈值时自动推送告警。错误率阈值通过 wechat_bot.error_rate_threshold 配置。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "wechat_bot.latency_threshold_ms",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         5000,
			Description:     "延迟告警阈值（毫秒）",
			DescriptionLong: "触发高延迟告警的阈值，单位毫秒。默认 5000ms（5秒）。仅当 notify_on_latency 开启时生效。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "wechat_bot.error_rate_threshold",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         0.1,
			Description:     "错误率告警阈值",
			DescriptionLong: "触发错误率告警的阈值，取值 0.0~1.0。默认 0.1（10%）。仅当 notify_on_error_rate 开启时生效。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "wechat_bot.allowed_users",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "微信白名单用户",
			DescriptionLong: "允许通过微信执行操作的用户 UserID 列表（逗号分隔）。留空表示允许所有已绑定用户。用户ID为企业微信中的用户标识。",
			DangerLevel:     Safe,
			HotReload:       true,
		},

		// ── DingTalk bot (钉钉机器人) ──────────────────────────────────
		{
			Key:             "dingtalk_bot.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "钉钉机器人集成",
			DescriptionLong: "对接钉钉自定义机器人，实现远程运维通知、风险告警推送、审批操作执行等功能。支持群机器人 Webhook（加签/关键词）与工作通知（应用消息）两种模式。依赖压缩管理、提示词注入检测、会话缓存、会话审计与审批等模块。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		// 连接方式一：群机器人 Webhook（加签）
		{
			Key:             "dingtalk_bot.webhook_url",
			Type:            TypeURL,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "群机器人 Webhook URL",
			DescriptionLong: "钉钉自定义机器人的 Webhook 地址（格式：https://oapi.dingtalk.com/robot/send?access_token=xxxx）。配置后通过群机器人推送消息，无需 access_token。建议安全设置使用「加签」以校验请求合法性。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "dingtalk_bot.sign_secret",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "加签 Secret",
			DescriptionLong: "群机器人「加签」安全设置的密钥。推送时按 timestamp+\"\\n\"+secret 做 HMAC-SHA256 并 Base64 编码作为签名。留空表示不启用加签（此时建议开启关键词或 IP 白名单保护）。敏感信息，不进入日志。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		// 连接方式二：工作通知（应用消息）
		{
			Key:             "dingtalk_bot.app_key",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "应用 AppKey",
			DescriptionLong: "钉钉企业内部应用的 AppKey。在钉钉开发者后台「应用开发-企业内部开发」创建机器人/应用后获取。配置后可使用工作通知（按 userid 列表下发），比群机器人更精准。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "dingtalk_bot.app_secret",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "应用 AppSecret",
			DescriptionLong: "钉钉企业内部应用的 AppSecret（敏感信息，不会出现在日志中）。用于获取 access_token 以发送工作通知。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "dingtalk_bot.agent_id",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "应用 AgentID",
			DescriptionLong: "钉钉企业内部应用的 AgentID。配合 AppKey/AppSecret 使用，工作通知通过该 agent_id 下发。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "dingtalk_bot.base_url",
			Type:            TypeURL,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "https://oapi.dingtalk.com",
			Description:     "钉钉 OpenAPI 基础地址",
			DescriptionLong: "钉钉开放平台 API 地址。默认 https://oapi.dingtalk.com。私有化部署（专属钉钉）可修改为内网网关地址。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		// 实时告警推送
		{
			Key:             "dingtalk_bot.notify_on_alert",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "安全告警推送",
			DescriptionLong: "当系统检测到安全异常（提示词注入攻击、角色劫持、越狱、数据泄露等）时自动推送钉钉消息。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "dingtalk_bot.notify_on_latency",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "高延迟告警",
			DescriptionLong: "当请求延迟超过阈值时自动推送告警。延迟阈值通过 dingtalk_bot.latency_threshold_ms 配置。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "dingtalk_bot.notify_on_error_rate",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "错误率飙升告警",
			DescriptionLong: "当错误率超过阈值时自动推送告警。错误率阈值通过 dingtalk_bot.error_rate_threshold 配置。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "dingtalk_bot.latency_threshold_ms",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         5000,
			Description:     "延迟告警阈值（毫秒）",
			DescriptionLong: "触发高延迟告警的阈值，单位毫秒。默认 5000ms（5秒）。仅当 notify_on_latency 开启时生效。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "dingtalk_bot.error_rate_threshold",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         0.1,
			Description:     "错误率告警阈值",
			DescriptionLong: "触发错误率告警的阈值，取值 0.0~1.0。默认 0.1（10%）。仅当 notify_on_error_rate 开启时生效。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		// 高风险操作审批通知与钉钉内操作
		{
			Key:             "dingtalk_bot.notify_on_approval",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "审批通知与钉钉内操作",
			DescriptionLong: "高风险会话需要审批时通过钉钉通知管理员。管理员可直接在钉钉消息中点击「批准/拒绝」完成审批。需配置回调地址（见 dingtalk_bot.callback_*）以接收审批结果。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "dingtalk_bot.callback_url",
			Type:            TypeURL,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "审批回调地址",
			DescriptionLong: "接收钉钉审批回调的公网地址（格式：https://your-domain/api/webhooks/dingtalk/approval-callback）。在钉钉机器人「接收消息」/「事件订阅」中配置为该地址。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "dingtalk_bot.verify_signature",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "钉钉回调签名验证",
			DescriptionLong: "对钉钉回调请求做签名校验（HMAC-SHA256：timestamp+\"\\n\"+加签Secret/AppSecret）。开启后仅接受来自钉钉的合法回调，防止伪造请求触发审批。强烈建议保持开启。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		// 系统状态查询
		{
			Key:             "dingtalk_bot.enable_status_query",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "系统状态查询",
			DescriptionLong: "允许管理员在钉钉中通过指令（如 /status、/health）查询网关运行状态（延迟、错误率、在线会话数等）。仅白名单用户可触发。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		// 安全：签名验证 + 白名单
		{
			Key:             "dingtalk_bot.allowed_users",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "钉钉白名单用户",
			DescriptionLong: "允许通过钉钉执行操作/查询的用户标识列表（逗号分隔），可填手机号（atMobiles）或 UserID（atUserIds）。留空表示允许所有可接收消息的成员。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		// 推送体验：卡片类型 + @ 策略
		{
			Key:             "dingtalk_bot.card_type",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "actionCard",
			Description:     "消息卡片类型",
			DescriptionLong: "审批/告警消息的卡片样式：actionCard=整体跳转交互卡片（含「查看详情」按钮），markdown=纯 Markdown 文本。审批类消息建议使用 actionCard。",
			DangerLevel:     Safe,
			HotReload:       true,
			Options:         []string{"actionCard", "markdown", "text"},
		},
		{
			Key:             "dingtalk_bot.at_all",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "默认 @ 所有人",
			DescriptionLong: "推送告警/审批消息时是否默认 @ 群内所有人。告警类建议关闭（避免打扰），审批类可按需开启。开启后将覆盖白名单的 @ 名单。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		// 限流保护（钉钉群机器人 20 条/分钟）
		{
			Key:             "dingtalk_bot.rate_limit_per_min",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         18,
			Description:     "每分钟发送上限",
			DescriptionLong: "钉钉群机器人官方限制为 20 条/分钟，超限将被限流 10 分钟。此处设置实际发送的限速值（默认 18，预留余量）。工作通知模式不受此限制。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
	}
}

// IsSessionAnalyticsEnabled reads the session_analytics.enabled setting
// (platform fallback) to decide whether the analysis hook plugin is active.
// Mirrors resolveModuleEnabled in admin/modules.go but usable from the
// pipeline/hook layer without an HTTP request.
func IsSessionAnalyticsEnabled() bool {
	if Global == nil {
		return false
	}
	sp := Global.Spec("session_analytics.enabled")
	if sp == nil {
		return false
	}
	raw, _, err := Global.EffectiveValue(sp.Scope, sp.Key, "")
	if err != nil || raw == nil {
		return false
	}
	var v bool
	if err := json.Unmarshal(raw, &v); err != nil {
		return false
	}
	return v
}
