package settings

// SessionAuditSpecs returns all session audit & approval configuration specs.
func SessionAuditSpecs() []*Spec {
	return []*Spec{
		// ========== 全局设置 ==========
		{
			Key:             "session_audit.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "启用会话审计与审批",
			DescriptionLong: "启用后，高风险会话将触发审计流程并可能需要人工审批",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "session_audit.enforcement_level",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         "strict",
			Options:         []string{"strict", "advisory", "audit_only"},
			Description:     "强制级别",
			DescriptionLong: "strict=拦截高风险请求，advisory=仅通知不拦截，audit_only=仅记录",
			DangerLevel:     Warning,
			HotReload:       true,
		},

		// ========== 风险检测配置 ==========
		{
			Key:             "session_audit.detector_models",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         `["gpt-4o-mini"]`,
			Description:     "检测模型",
			DescriptionLong: "用于风险检测的 LLM 模型列表（JSON 数组），支持多模型投票",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "session_audit.approval_threshold",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         70,
			Description:     "审批阈值",
			DescriptionLong: "风险评分 ≥ 此值时触发审批流程（0-100）",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "session_audit.auto_block_threshold",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         90,
			Description:     "自动拒绝阈值",
			DescriptionLong: "风险评分 ≥ 此值时直接拒绝，无需审批（0-100）",
			DangerLevel:     Dangerous,
			HotReload:       true,
		},
		{
			Key:             "session_audit.detect_prompt_injection",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         true,
			Description:     "检测提示词注入",
			DescriptionLong: "启用提示词注入检测（需要 prompt_injection 模块）",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "session_audit.detect_pii_leakage",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         true,
			Description:     "检测 PII 泄漏",
			DescriptionLong: "启用个人身份信息（PII）泄漏检测",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "session_audit.detect_jailbreak",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         true,
			Description:     "检测越狱尝试",
			DescriptionLong: "启用 Jailbreak 攻击检测",
			DangerLevel:     Safe,
			HotReload:       true,
		},

		// ========== 审批流程配置 ==========
		{
			Key:             "session_audit.approval_timeout",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         "4h",
			Description:     "审批超时时间",
			DescriptionLong: "审批请求的超时时间（如：2h, 4h, 8h, 24h）",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "session_audit.timeout_action",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         "deny",
			Options:         []string{"deny", "escalate", "auto_approve"},
			Description:     "超时后动作",
			DescriptionLong: "审批超时后的处理方式：deny=拒绝，escalate=升级，auto_approve=自动批准",
			DangerLevel:     Dangerous,
			HotReload:       true,
		},
		{
			Key:             "session_audit.min_approvals",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         1,
			Description:     "最少审批人数",
			DescriptionLong: "需要多少人批准后才能通过审批",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "session_audit.approver_roles",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         `["security_admin"]`,
			Description:     "审批角色",
			DescriptionLong: "允许审批的角色列表（JSON 数组）",
			DangerLevel:     Dangerous,
			HotReload:       true,
		},

		// ========== 升级策略 ==========
		{
			Key:             "session_audit.escalation_enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         false,
			Description:     "启用升级策略",
			DescriptionLong: "审批超时后自动升级到更高级别审批人",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "session_audit.escalation_after",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         "2h",
			Description:     "升级延迟",
			DescriptionLong: "多长时间未审批后触发升级（如：1h, 2h, 4h）",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "session_audit.escalation_approvers",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         `["ciso","cto"]`,
			Description:     "升级审批人",
			DescriptionLong: "升级后的审批人角色列表（JSON 数组）",
			DangerLevel:     Dangerous,
			HotReload:       true,
		},

		// ========== 通知集成 ==========
		{
			Key:             "session_audit.notify_channels",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryIntegration,
			Default:         `["feishu"]`,
			Description:     "通知渠道",
			DescriptionLong: "审批通知的渠道列表（JSON 数组：feishu, dingtalk, wechat）",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "session_audit.notify_on_pending",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryIntegration,
			Default:         true,
			Description:     "待审批时通知",
			DescriptionLong: "创建审批请求时立即发送通知",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "session_audit.notify_on_timeout",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryIntegration,
			Default:         true,
			Description:     "超时时通知",
			DescriptionLong: "审批超时时发送通知",
			DangerLevel:     Safe,
			HotReload:       true,
		},

		// ========== 模块联动 ==========
		{
			Key:             "session_audit.require_intent_analysis",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         false,
			Description:     "需要意图分析",
			DescriptionLong: "启用后将意图识别结果纳入风险评分",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "session_audit.intent_weight",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         0.3,
			Description:     "意图分析权重",
			DescriptionLong: "意图分析在总风险评分中的权重（0.0-1.0）",
			DangerLevel:     Safe,
			HotReload:       true,
		},

		// ========== 审计设置 ==========
		{
			Key:             "session_audit.retention_days",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         90,
			Description:     "审计记录保留天数",
			DescriptionLong: "审计记录在数据库中的保留天数",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "session_audit.mask_sensitive_data",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         true,
			Description:     "脱敏敏感数据",
			DescriptionLong: "在审计日志中自动脱敏敏感信息（PII、密钥等）",
			DangerLevel:     Safe,
			HotReload:       true,
		},
	}
}
