package settings

// SessionSpecs contains session-related platform settings.
func SessionSpecs() []*Spec {
	return []*Spec{
		{
			Key:             "session.id_body_keys",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         "",
			Description:     "请求体会话别名键",
			DescriptionLong: "用于从前端请求体中提取 session_id 的附加 key 名称，逗号分隔；会与默认别名合并，修改后立即生效。",
			Unit:            "csv",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/settings/session.id_body_keys",
		},
		{
			Key:             "session.stopped_ttl_minutes",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         30,
			Description:     "会话停止后保留时间（分钟）",
			DescriptionLong: "会话停止后 Redis 数据保留的时间，超时后自动删除。支持会话恢复功能。",
			Unit:            "分钟",
			DangerLevel:     Safe,
			HotReload:       true,
			Observability:   "/api/admin/sessions?status=stopped",
		},
		{
			Key:             "session.cred_history_max",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         100,
			Description:     "每会话凭据轮换历史保留条数",
			DescriptionLong: "Redis List 中保留的凭据轮换历史最大条数，超出后自动截断最旧记录。",
			Unit:            "条",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "session.db_batch_size",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         10,
			Description:     "凭据轮换记录批量写 DB 的批次大小",
			DescriptionLong: "凭据轮换记录异步批量写入数据库的批次大小，每 N 条轮次或每 M 秒触发一次。",
			Unit:            "条",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "session.db_flush_interval_sec",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         60,
			Description:     "凭据轮换记录批量写 DB 的时间间隔（秒）",
			DescriptionLong: "凭据轮换记录异步批量写入数据库的时间间隔，到达时间或批次大小触发 flush。",
			Unit:            "秒",
			DangerLevel:     Warning,
			HotReload:       true,
		},
	}
}
