package settings

// SessionsV2Specs contains Sessions V2 feature flag configuration.
//
// 会话优化V2灰度发布的Feature Flag控制配置。
// 用于控制新表体系(sessions/session_turns/session_bodies)的流量路由。
//
// Created: 2026-07-17, Migration 430
func SessionsV2Specs() []*Spec {
	return []*Spec{
		{
			Key:             "sessions_v2.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         false,
			Description:     "Sessions V2 总开关",
			DescriptionLong: "启用会话存储V2架构。关闭时完全使用request_logs，开启后根据其他开关决定读写路由。",
			Unit:            "",
			DangerLevel:     Dangerous,
			HotReload:       true,
			Observability:   "/api/admin/sessions/v2/status",
		},
		{
			Key:             "sessions_v2.shadow_write",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         false,
			Description:     "启用副写模式",
			DescriptionLong: "副写模式：同时写入request_logs和V2表，但仅从request_logs读取。用于验证V2表写入正确性。需要enabled=true。",
			Unit:            "",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/sessions/v2/shadow_metrics",
		},
		{
			Key:             "sessions_v2.rollout_percent",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         0,
			Description:     "灰度百分比",
			DescriptionLong: "V2表的流量灰度百分比(0-100)。0表示不路由到V2，100表示全部路由到V2。基于session_id哈希决定路由。",
			Unit:            "%",
			DangerLevel:     Dangerous,
			HotReload:       true,
			Observability:   "/api/admin/sessions/v2/rollout_stats",
			Min:             floatPtr(0),
			Max:             floatPtr(100),
		},
		{
			Key:             "sessions_v2.l3_read",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         false,
			Description:     "启用从V2表读取(L3缓存)",
			DescriptionLong: "启用从session_turns读取会话数据作为L3缓存。需要enabled=true。",
			Unit:            "",
			DangerLevel:     Dangerous,
			HotReload:       true,
			Observability:   "/api/admin/sessions/v2/l3_hit_rate",
		},
		{
			Key:             "sessions_v2.dual_read",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         false,
			Description:     "双读对账模式",
			DescriptionLong: "同时读取request_logs和V2表，对比结果差异并记录。用于验证V2读取正确性。需要enabled=true且l3_read=true。",
			Unit:            "",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/sessions/v2/dual_read_diff",
		},
		{
			Key:             "sessions_v2.primary_read",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         false,
			Description:     "V2作为主读取源",
			DescriptionLong: "将V2表作为主读取源，request_logs作为降级备份。需要enabled=true且l3_read=true。与dual_read互斥。",
			Unit:            "",
			DangerLevel:     Breaking,
			HotReload:       true,
			Observability:   "/api/admin/sessions/v2/primary_read_stats",
		},
		{
			Key:             "sessions_v2.write_timeout_ms",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         500,
			Description:     "V2写入超时时间",
			DescriptionLong: "写入V2表的超时时间(毫秒)。超时后不阻塞主流程，异步重试。",
			Unit:            "毫秒",
			DangerLevel:     Safe,
			HotReload:       true,
			Min:             floatPtr(100),
			Max:             floatPtr(5000),
		},
		{
			Key:             "sessions_v2.read_timeout_ms",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         300,
			Description:     "V2读取超时时间",
			DescriptionLong: "从V2表读取的超时时间(毫秒)。超时后降级到request_logs。",
			Unit:            "毫秒",
			DangerLevel:     Safe,
			HotReload:       true,
			Min:             floatPtr(50),
			Max:             floatPtr(3000),
		},
		{
			Key:             "sessions_v2.compression_enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         true,
			Description:     "启用V2压缩检测",
			DescriptionLong: "检测客户端是否已压缩会话历史，标记submit_mode字段。",
			Unit:            "",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "sessions_v2.turn_logs_retention_hours",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         24,
			Description:     "环节日志保留时间",
			DescriptionLong: "session_turn_logs表中环节日志的保留时间(小时)，超时后自动清理。",
			Unit:            "小时",
			DangerLevel:     Safe,
			HotReload:       true,
			Min:             floatPtr(1),
			Max:             floatPtr(168), // 7天
		},
		{
			// CO-5 (docs/修订0811/19 §3): sessions_v2.enabled 时
			// request_logs_bodies 默认只落摘要信封(sha256+长度+截断头部)。
			// 本开关用于排障时恢复全量落库。sessions_v2 未启用时本开关无效
			// (始终全量落库)。
			Key:             "sessions_v2.request_bodies_full",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         false,
			Description:     "sessions_v2 启用时仍全量落库请求/响应体",
			DescriptionLong: "排障开关：sessions_v2.enabled 下 request_logs_bodies 默认摘要模式(只落 sha256/字节长度/截断头部)。置为 true 恢复全量落库；sessions_v2 未启用时始终全量落库，本开关无效。",
			Unit:            "",
			DangerLevel:     Warning,
			HotReload:       true,
		},
	}
}
