package settings

// DashboardSpecs configures board stats cache (Redis baseline + delta).
func DashboardSpecs() []*Spec {
	return []*Spec{
		{
			Key:             "dashboard.stats.fold_unit",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategoryGeneral,
			Default:         "second",
			Options:         []string{"second", "minute"},
			Description:     "看板统计 fold 粒度",
			DescriptionLong: "秒级：数字更新更平滑（默认）；分钟级：降低 Redis 写入与 fold 频率。",
			DangerLevel:     Safe,
			HotReload:       true,
			Observability:   "/api/admin/dashboard/board",
		},
		{
			Key:             "dashboard.stats.fold_interval",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryGeneral,
			Default:         10,
			Min:             floatPtr(1),
			Max:             floatPtr(60),
			Description:     "fold 间隔（单位由 fold_unit 决定）",
			DescriptionLong: "每 N 秒或 N 分钟将 Redis delta 合并进看板缓存。默认 10 秒（SSE 负责实时更新）。",
			Unit:            "秒/分钟",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "dashboard.stats.rebuild_interval_hours",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryGeneral,
			Default:         4,
			Min:             floatPtr(1),
			Max:             floatPtr(24),
			Description:     "PG→Redis baseline 校准周期",
			DescriptionLong: "从 PostgreSQL 重建看板 baseline 的目标间隔（小时）。默认 4 小时。",
			Unit:            "小时",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "dashboard.stats.rebuild_idle_qps",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryGeneral,
			Default:         10,
			Min:             floatPtr(1),
			Max:             floatPtr(1000),
			Description:     "baseline 重建闲时 QPS 阈值",
			DescriptionLong: "近 5 分钟平均 QPS 低于此值时才执行 PG 全量校准。",
			Unit:            "QPS",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "dashboard.stats.rebuild_max_delay_minutes",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryGeneral,
			Default:         120,
			Min:             floatPtr(15),
			Max:             floatPtr(360),
			Description:     "baseline 重建最大推迟时间",
			DescriptionLong: "繁忙时最多推迟 baseline 重建的分钟数，超时后强制执行。",
			Unit:            "分钟",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "dashboard.stats.delta_ttl_hours",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryGeneral,
			Default:         6,
			Min:             floatPtr(2),
			Max:             floatPtr(48),
			Description:     "delta 桶 Redis TTL",
			DescriptionLong: "请求增量桶在 Redis 中的保留时间，应大于 rebuild 周期。",
			Unit:            "小时",
			DangerLevel:     Safe,
			HotReload:       true,
		},
	}
}
