package settings

// CompressionSpecs — 7 平台级 + 0 租户级 — 压缩与会话相关
// 对应 LLM_GATEWAY_COMPRESSION_MODE / _WINDOW_FRACTION /
// LLM_GATEWAY_SESSION_TTL_HOURS / LLM_GATEWAY_ENABLE_DISGUISE /
// LLM_GATEWAY_STREAM_RETRY_THRESHOLD
func CompressionSpecs() []*Spec {
	minFraction := 0.0
	maxFraction := 1.0
	return []*Spec{
		{
			Key:             "compression.mode",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Options:         []string{"off", "auto_threshold", "on_4xx", "delta_only", "smart", "aggressive"},
			Default:         "smart",
			Description:     "压缩模式",
			DescriptionLong: "off=从不压缩；auto_threshold=请求前按阈值压缩；on_4xx=仅在 upstream 返回 context_length_exceeded 后压缩；smart=v4 智能压缩（默认，含工具裁剪+滑动窗口）；aggressive=v4 激进压缩（含任务分析+主动压缩）。",
			Unit:            "",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "compression.window_fraction",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Min:             &minFraction,
			Max:             &maxFraction,
			Default:         0.80,
			Description:     "压缩窗口阈值比例",
			DescriptionLong: "达到供应商模型上下文窗口的 80% 时考虑压缩；可按需调整，建议 0.7-0.8。",
			Unit:            "比例",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "compression.strategy_runner_enabled",
			EnvName:         "LLM_GATEWAY_COMPRESSION_STRATEGY_RUNNER_ENABLED",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Default:         false,
			Description:     "启用可选压缩策略执行器",
			DescriptionLong: "默认关闭。开启后，auto_threshold 和 on_4xx 模式会在既有机械压缩前尝试已启用的策略链；无收益或失败时保留原有回退链。",
			Unit:            "",
			DangerLevel:     Warning,
			HotReload:       false,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "compression.selector_mode",
			EnvName:         "LLM_GATEWAY_COMPRESSION_SELECTOR",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Options:         []string{"manual", "adaptive"},
			Default:         "manual",
			Description:     "压缩策略选择模式",
			DescriptionLong: "manual 按 compression.selector_spec 的顺序执行；adaptive 使用已启用阶段的 lite→toolfocused→caveman 字节预算启发式阶梯。",
			Unit:            "",
			DangerLevel:     Warning,
			HotReload:       false,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "compression.selector_spec",
			EnvName:         "LLM_GATEWAY_COMPRESSION_SELECTOR_SPEC",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Default:         "",
			Description:     "手动压缩策略列表",
			DescriptionLong: "仅 manual 模式使用。以逗号分隔策略名，例如 lite,toolfocused；空值表示不选择任何策略。",
			Unit:            "csv",
			DangerLevel:     Warning,
			HotReload:       false,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "compression.adaptive_target_ratio",
			EnvName:         "LLM_GATEWAY_COMPRESSION_TARGET_RATIO",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Min:             &minFraction,
			Max:             &maxFraction,
			Default:         0.8,
			Description:     "自适应压缩目标比例",
			DescriptionLong: "adaptive 模式下将 body 压缩到 context window 字节阈值的该比例。该值是字节启发式，不等同于 provider tokenizer 的精确 token 预算。",
			Unit:            "比例",
			DangerLevel:     Warning,
			HotReload:       false,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "compression.token_threshold_consider",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Min:             floatPtr(0),
			Max:             floatPtr(2_000_000),
			Default:         200_000,
			Description:     "会话压缩预备 token 阈值",
			DescriptionLong: "按实际 outbound token（已压缩历史加本轮 delta）计算。超过此值只标记预备压缩，不会因原始输入大小单独触发摘要；设为 0 可关闭。",
			Unit:            "tokens",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "compression.token_threshold_force",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Min:             floatPtr(0),
			Max:             floatPtr(2_000_000),
			Default:         400_000,
			Description:     "会话压缩强制 token 阈值",
			DescriptionLong: "按实际 outbound token（已压缩历史加本轮 delta）计算。超过此值强制进入既有会话摘要/机械裁剪回退路径；设为 0 可关闭。",
			Unit:            "tokens",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "compression.llm_model",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Default:         "minimax-text-01,gemini-2.5-flash",
			Description:     "压缩/摘要用大模型",
			DescriptionLong: "会话压缩执行 LLM 总结时优先使用的模型列表（逗号分隔，从左到右依次尝试）。要求模型上下文窗口 ≥ 800k tokens。留空则回退到环境变量 LLM_GATEWAY_COMPACTION_MODELS 或内置默认。",
			Unit:            "csv",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "summary_models.project_context",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Default:         "auto",
			Description:     "项目维度总结模型",
			DescriptionLong: "项目上下文总结时优先使用的模型列表（逗号分隔，从左到右依次尝试）。留空或 auto 时回退到 summary_models.fallback，然后回退到 compression.llm_model。",
			Unit:            "csv",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "summary_models.keywords",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Default:         "auto",
			Description:     "关键词维度总结模型",
			DescriptionLong: "关键词提取总结时优先使用的模型列表（逗号分隔，从左到右依次尝试）。留空或 auto 时回退到 summary_models.fallback，然后回退到 compression.llm_model。",
			Unit:            "csv",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "summary_models.tasks",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Default:         "auto",
			Description:     "任务维度总结模型",
			DescriptionLong: "任务追踪总结时优先使用的模型列表（逗号分隔，从左到右依次尝试）。留空或 auto 时回退到 summary_models.fallback，然后回退到 compression.llm_model。",
			Unit:            "csv",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "summary_models.decisions",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Default:         "auto",
			Description:     "决策维度总结模型",
			DescriptionLong: "重要决策总结时优先使用的模型列表（逗号分隔，从左到右依次尝试）。留空或 auto 时回退到 summary_models.fallback，然后回退到 compression.llm_model。",
			Unit:            "csv",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "summary_models.problems",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Default:         "auto",
			Description:     "问题维度总结模型",
			DescriptionLong: "问题与解决方案总结时优先使用的模型列表（逗号分隔，从左到右依次尝试）。留空或 auto 时回退到 summary_models.fallback，然后回退到 compression.llm_model。",
			Unit:            "csv",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "summary_models.technical_details",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Default:         "auto",
			Description:     "技术维度总结模型",
			DescriptionLong: "技术细节总结时优先使用的模型列表（逗号分隔，从左到右依次尝试）。留空或 auto 时回退到 summary_models.fallback，然后回退到 compression.llm_model。",
			Unit:            "csv",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "summary_models.document_summary",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Default:         "auto",
			Description:     "文档总结专用模型队列",
			DescriptionLong: "强制会话压缩处理超长实际 outbound 时使用的低成本模型列表（逗号分隔，从左到右依次尝试）。留空或 auto 时回退到 summary_models.fallback，再回退到 compression.llm_model。",
			Unit:            "csv",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "summary_models.fallback",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Default:         "auto",
			Description:     "总结模型兜底",
			DescriptionLong: "所有维度总结模型的共享兜底列表（逗号分隔，从左到右依次尝试）。留空或 auto 时回退到 compression.llm_model。",
			Unit:            "csv",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "cache.session_redis_ttl_minutes",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Min:             floatPtr(5),
			Max:             floatPtr(1440),
			Default:         30,
			Description:     "会话缓存 Redis TTL",
			DescriptionLong: "SessionCache L2 Redis Hash 的 TTL（分钟）。默认 30 分钟（与 sliding-window 5 分钟的空闲超时保持安全边距）。最小 5 分钟，最大 1440 分钟（24 小时）。热更新生效。",
			Unit:            "分钟",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "cache.session_l1_capacity",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Min:             floatPtr(64),
			Max:             floatPtr(16384),
			Default:         1024,
			Description:     "会话缓存 L1 容量",
			DescriptionLong: "SessionCache L1 LRU 进程内缓存最大会话数。超出时淘汰最久未使用的条目。默认 1024。热更新生效（仅影响后续驱逐决策，不主动缩减现有条目）。",
			Unit:            "条目数",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "cache.session_l1_max_bytes",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Min:             floatPtr(16 << 20),
			Max:             floatPtr(2 << 30),
			Default:         256 << 20,
			Description:     "会话缓存 L1 字节预算",
			DescriptionLong: "SessionCache L1 LRU 的聚合字节上限。条目会在达到会话数上限或字节预算时按最近最少使用顺序淘汰。默认 256 MiB，最小 16 MiB，最大 2 GiB。热更新生效。",
			Unit:            "字节",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key: "compression.enabled",

			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Default:         true,
			Description:     "启用会话压缩",
			DescriptionLong: "主开关：关闭时所有压缩模式（包括 v4 smart/aggressive）均不生效，仅 delta-append 保留。",
			Unit:            "",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "handoff.threshold",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryCompression,
			Min:             &minFraction,
			Max:             &maxFraction,
			Default:         0.8,
			Description:     "触发 Handoff 上下文阈值",
			DescriptionLong: "上下文使用率达到此比例时触发 handoff 建议（0.0-1.0）。默认 0.8 表示 80%。",
			Unit:            "比例",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/compression/stats",
		},
		{
			Key:             "session.ttl_hours",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Min:             floatPtr(1),
			Max:             floatPtr(8760),
			Default:         168,
			Description:     "会话 TTL",
			DescriptionLong: "会话在 Redis 中保留的小时数。影响 session.Manager 的 TTL。",
			Unit:            "小时",
			DangerLevel:     Dangerous,
			HotReload:       true,
			Observability:   "/api/admin/session-context",
		},
		{
			Key:             "enable_disguise",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySecurity,
			Default:         false,
			Description:     "启用 UA/TLS 伪装",
			DescriptionLong: "启用 User-Agent 和 TLS 指纹轮换（参考 docs/legal/disguise-compliance.md）。在模块管理页面可配置轮换间隔、池大小、平台过滤、TLS 指纹、Slot 并发等详细参数。",
			Unit:            "",
			DangerLevel:     Breaking,
			HotReload:       true,
			Observability:   "/healthz?full=true",
		},
		{
			Key:             "stream_retry_threshold",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryTimeout,
			Min:             floatPtr(0),
			Max:             floatPtr(100),
			Default:         5,
			Description:     "流式重试阈值",
			DescriptionLong: "上游流式 chunk 数低于此值时触发 failover 到下一个 credential。",
			Unit:            "chunks",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/routing/decisions",
		},
	}
}

func floatPtr(f float64) *float64 { return &f }
