package settings

// CategoryStorage groups all attachment/storage management settings.
// 2026-07-02: 本地文件存储（附件）的运维配置。
const CategoryStorage Category = "storage"

// StorageSpecs returns all platform-scoped storage/attachment management specs.
// 这些设置控制附件文件系统的保留策略、配额水位、自动清理行为。
// 持久化到 settings_kv（category='storage'），通过数据生命周期页面管理。
func StorageSpecs() []*Spec {
	return []*Spec{
		{
			Key:             "storage.attachment_dir_override",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryStorage,
			Default:         "",
			Description:     "附件存储目录覆盖",
			DescriptionLong: "覆盖默认附件存储目录（环境变量 LLM_GATEWAY_ATTACHMENT_DIR）。留空则使用环境变量或默认 ./data/attachments。修改后需要重启服务进程生效（不会自动迁移已有文件）。",
			DangerLevel:     Dangerous,
			HotReload:       false,
		},
		{
			Key:             "storage.attachment_ttl_days",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryStorage,
			Min:             floatPtr(1),
			Max:             floatPtr(3650),
			Default:         30,
			Description:     "附件保留天数",
			DescriptionLong: "超过此天数的附件文件视为过期，可被清理或归档。默认 30 天。",
			Unit:            "天",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "storage.attachment_max_size_mb",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryStorage,
			Min:             floatPtr(1),
			Max:             floatPtr(200),
			Default:         20,
			Description:     "单个附件大小上限",
			DescriptionLong: "单个附件文件（解码后）的最大字节数。超过此大小的附件会被拒绝存储（但请求仍正常转发）。默认 20MB。",
			Unit:            "MB",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "storage.disk_quota_percent",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryStorage,
			Min:             floatPtr(50),
			Max:             floatPtr(99),
			Default:         80,
			Description:     "磁盘告警水位",
			DescriptionLong: "磁盘使用率达到此百分比时触发告警。默认 80%。",
			Unit:            "%",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "storage.auto_cleanup_enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryStorage,
			Default:         false,
			Description:     "启用自动清理",
			DescriptionLong: "启用后，后台 worker 会定期检查磁盘水位，超过阈值时自动按 LRU 清理最老的附件和归档日志。默认关闭，避免误删。",
			DangerLevel:     Dangerous,
			HotReload:       true,
		},
		{
			Key:             "storage.auto_cleanup_threshold",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryStorage,
			Min:             floatPtr(60),
			Max:             floatPtr(99),
			Default:         85,
			Description:     "自动清理触发水位",
			DescriptionLong: "磁盘使用率达到此百分比时触发自动清理（需启用 auto_cleanup_enabled）。默认 85%。",
			Unit:            "%",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "log.delete_days",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryLogs,
			Min:             floatPtr(7),
			Max:             floatPtr(3650),
			Default:         30,
			Description:     "日志删除天数",
			DescriptionLong: "超过此天数的归档日志自动删除。默认 30 天。删除不可恢复。",
			Unit:            "天",
			DangerLevel:     Warning,
			HotReload:       true,
		},
	}
}
