package settings

import "encoding/json"

// CategoryModules groups all module-level settings together
const CategoryModules Category = "modules"

// ModuleSpecs returns all platform-scoped module management specs.
// Each feature module gets an enable/disable toggle; new enterprise
// integrations (Feishu bot, webhook, etc.) are defined here as well.
func ModuleSpecs() []*Spec {
	return []*Spec{
		// ── Audit logging ─────────────────────────────────────────────
		{
			Key:             "audit.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "审计日志",
			DescriptionLong: "记录所有 API 请求的审计追踪（谁、何时、做了什么）。关闭后仍保留当前请求的部分关键日志，但审计管理页面将不可用。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "prompt_injection.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "提示词注入检测",
			DescriptionLong: "LLM-as-judge 检测提示词注入攻击和角色劫持。仅检测模式，不拦截请求。关闭后完全跳过注入分析。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "输出合规检测",
			DescriptionLong: "检查 LLM 输出是否包含敏感数据（PII、密钥、内部 IP 等）。发现时触发告警或脱敏。关闭后跳过所有输出检查。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "session_audit.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "会话审计与审批",
			DescriptionLong: "高风险会话自动触发审计审批流程。管理员可以批准/拒绝高风险操作。关闭后所有会话直接放行。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "session_inspector.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "会话健康检查",
			DescriptionLong: "监控会话 token 限制、不活跃超时、高频请求等健康指标。关闭后跳过所有会话健康检查。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "security.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "安全检测（意图+威胁）",
			DescriptionLong: "意图分析与威胁检测引擎。识别恶意意图（越狱、数据泄露）并触发预设响应策略。关闭后跳过所有安全检测。",
			DangerLevel:     Dangerous,
			HotReload:       true,
		},
		// ── Security Engine - Detection Mode ────────────────────────────
		{
			Key:             "security.mode",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "observe",
			Description:     "检测模式",
			DescriptionLong: "observe=仅记录不拦截（推荐测试期），enforce=高风险请求直接阻断。切换到强制模式前请确保已完成充分测试。",
			DangerLevel:     Dangerous,
			HotReload:       true,
			Options:         []string{"observe", "enforce"},
		},
		// ── Security Engine - LLM Model Configuration ───────────────────
		{
			Key:             "security.llm.intent_model",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "gpt-4o-mini",
			Description:     "意图分析模型",
			DescriptionLong: "用于意图分类的LLM模型。推荐使用轻量模型（gpt-4o-mini/Claude Haiku）以降低延迟和成本。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.llm.threat_model",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "gpt-4o-mini",
			Description:     "威胁检测模型",
			DescriptionLong: "用于威胁评分的LLM模型。需要较强的推理能力，推荐 gpt-4o-mini 或更高版本。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		// ── Security Engine - Intent Analysis ───────────────────────────
		{
			Key:             "security.intent.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "启用意图分析",
			DescriptionLong: "分析用户请求的意图类型（代码/聊天/有害等）。基于关键词和LLM的混合分类。关闭后跳过意图分析。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.intent.confidence_threshold",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         0.7,
			Description:     "意图置信度阈值",
			DescriptionLong: "意图分类的置信度阈值（0-1）。低于此值的分类结果将标记为unknown。建议0.6-0.8。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "security.intent.drift_threshold",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         0.5,
			Description:     "意图漂移阈值",
			DescriptionLong: "意图漂移检测阈值（0-1）。超过此值表示会话意图发生显著变化，可能需要重新路由。基于KL散度计算。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		// ── Security Engine - Threat Detection ──────────────────────────
		{
			Key:             "security.threat.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "启用威胁检测",
			DescriptionLong: "检测请求中的安全威胁（注入、越狱、数据泄露等）。基于规则+LLM的双层检测。关闭后跳过所有威胁检测。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.threat.severity_threshold",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         7,
			Description:     "威胁严重度阈值",
			DescriptionLong: "触发响应动作的威胁严重度阈值（0-10）。低于此值的威胁仅记录日志。建议7-8。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.threat.checks.prompt_inject",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "提示词注入检测",
			DescriptionLong: "检测提示词注入攻击（忽略指令、角色切换等）。依赖：prompt_injection 模块。关闭后不检测注入类威胁。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.threat.checks.jailbreak",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "越狱攻击检测",
			DescriptionLong: "检测越狱尝试（DAN模式、开发者模式等）。基于30+正则模式库。关闭后不检测越狱类威胁。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.threat.checks.data_leak",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "数据泄露检测",
			DescriptionLong: "检测敏感数据泄露（API密钥、内部IP等）。依赖：output_compliance 模块。关闭后不检测数据泄露。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.threat.checks.pii",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "PII检测",
			DescriptionLong: "检测个人信息（身份证、手机号、邮箱等）。依赖：output_compliance 模块。关闭后不检测PII。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "security.threat.checks.persona_override",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "角色劫持检测",
			DescriptionLong: "检测角色劫持尝试（假装是管理员、root等）。基于关键词模式匹配。关闭后不检测角色劫持。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		// ── Security Engine - Response Strategy ─────────────────────────
		{
			Key:             "security.response.low_risk",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "log",
			Description:     "低风险响应动作",
			DescriptionLong: "低风险威胁的响应动作：log=仅记录日志，warn=记录+告警。",
			DangerLevel:     Safe,
			HotReload:       true,
			Options:         []string{"log", "warn"},
		},
		{
			Key:             "security.response.medium_risk",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "warn",
			Description:     "中风险响应动作",
			DescriptionLong: "中风险威胁的响应动作：warn=警告，sanitize=清洗内容，block=阻断请求，approval=人工审批。",
			DangerLevel:     Warning,
			HotReload:       true,
			Options:         []string{"warn", "sanitize", "block", "approval"},
		},
		{
			Key:             "security.response.high_risk",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "block",
			Description:     "高风险响应动作",
			DescriptionLong: "高风险威胁的响应动作：block=直接阻断，approval=人工审批。依赖：session_audit 模块（审批功能）。",
			DangerLevel:     Dangerous,
			HotReload:       true,
			Options:         []string{"block", "approval"},
		},
		// ── Security Engine - Audit Integration ─────────────────────────
		{
			Key:             "security.audit.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "启用审计联动",
			DescriptionLong: "将安全检测结果写入审计日志。依赖：session_audit 模块。关闭后检测结果不进入审计流程。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "security.audit.log_all",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "记录所有检测结果",
			DescriptionLong: "记录所有请求的检测结果（包括安全通过的）。依赖：audit 模块。开启后会增加存储消耗。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "security.audit.sampling_rate",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         1.0,
			Description:     "审计采样率",
			DescriptionLong: "安全审计的采样率（0-1）。1.0=全量记录，0.1=10%采样。高流量场景可降低以减少存储压力。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		// ── Rate Limiting ──────────────────────────────────────────────
		{
			Key:             "rate_limit.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "限流控制",
			DescriptionLong: "RPM / 并发 / TPM 多维度流量控制。关闭后将不限制任何请求速率（危险操作，仅限调试场景）。",
			DangerLevel:     Breaking,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "飞书机器人集成",
			DescriptionLong: "对接飞书机器人实现远程运维：告警通知、审批执行、状态查询。需要先配置 Webhook URL 和验证令牌。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.webhook_url",
			Type:            TypeURL,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "飞书机器人 Webhook URL",
			DescriptionLong: "飞书自定义机器人的 Webhook 地址（格式：https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxx）。必须先启用飞书机器人模块。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.verify_token",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "飞书机器人验证令牌",
			DescriptionLong: "用于验证飞书回调请求来源的签名令牌。可在飞书机器人安全设置中获取。留空则不验证签名。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.notify_on_alert",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "告警推送",
			DescriptionLong: "当系统检测到异常（注入攻击、高延迟、错误率飙升）时自动推送飞书消息。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.notify_on_approval",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "审批通知",
			DescriptionLong: "高风险会话需要审批时通过飞书通知管理员。管理员可直接在飞书消息中操作审批。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.allowed_users",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "飞书白名单用户",
			DescriptionLong: "允许通过飞书执行操作的用户 OpenID 列表（逗号分隔）。留空表示允许所有已绑定用户。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
	}
}

// IsSessionAnalyticsEnabled reads the session_analytics.enabled setting
// (platform fallback) to decide whether the analysis hook plugin is active.
// Mirrors resolveModuleEnabled in admin/modules.go but usable from the
// pipeline/hook layer without an HTTP request.
func IsSessionAnalyticsEnabled() bool {
	if Global == nil {
		return false
	}
	sp := Global.Spec("session_analytics.enabled")
	if sp == nil {
		return false
	}
	raw, _, err := Global.EffectiveValue(sp.Scope, sp.Key, "")
	if err != nil || raw == nil {
		return false
	}
	var v bool
	if err := json.Unmarshal(raw, &v); err != nil {
		return false
	}
	return v
}
