package settings

import "encoding/json"

// CategoryModules groups all module-level settings together
const CategoryModules Category = "modules"

// ModuleSpecs returns all platform-scoped module management specs.
// Each feature module gets an enable/disable toggle; new enterprise
// integrations (Feishu bot, webhook, etc.) are defined here as well.
func ModuleSpecs() []*Spec {
	return []*Spec{
		// ── Audit logging ─────────────────────────────────────────────
		{
			Key:             "audit.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "审计日志",
			DescriptionLong: "记录所有 API 请求的审计追踪（谁、何时、做了什么）。关闭后仍保留当前请求的部分关键日志，但审计管理页面将不可用。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "prompt_injection.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "提示词注入检测",
			DescriptionLong: "LLM-as-judge 检测提示词注入攻击和角色劫持。仅检测模式，不拦截请求。关闭后完全跳过注入分析。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "输出合规检测",
			DescriptionLong: "检查 LLM 输出是否包含敏感数据（PII、密钥、内部 IP 等）。发现时触发告警或脱敏。关闭后跳过所有输出检查。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.enforcement_mode",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Options:         []string{"observe", "enforce"},
			Default:         "observe",
			Description:     "执行模式",
			DescriptionLong: "observe：仅记录审计日志，不修改响应；enforce：根据策略执行脱敏/阻断。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		// 检测引擎选择
		{
			Key:             "output_compliance.pii_engine",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Options:         []string{"regex", "model", "hybrid"},
			Default:         "regex",
			Description:     "PII 检测引擎",
			DescriptionLong: "regex：基于正则规则库；model：LLM 语义识别；hybrid：规则 + LLM 双重判定。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.toxicity_engine",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Options:         []string{"keyword", "model", "hybrid"},
			Default:         "keyword",
			Description:     "毒性检测引擎",
			DescriptionLong: "keyword：关键词匹配；model：LLM 语义识别；hybrid：关键词 + LLM 双重判定。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		// 检测类型开关
		{
			Key:             "output_compliance.check_pii",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "检测 PII",
			DescriptionLong: "检测邮箱、手机号、身份证、信用卡、银行卡、IP 等个人身份信息。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.check_toxicity",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "检测毒性内容",
			DescriptionLong: "检测辱骂、仇恨言论、暴力、色情等有害内容。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.check_bias",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "检测偏见",
			DescriptionLong: "检测性别、种族、年龄等潜在偏见内容。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.check_hallucination",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "检测幻觉提示",
			DescriptionLong: "检测模型输出中可能存在的幻觉信号（实验性）。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.check_secrets",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "检测密钥/凭据",
			DescriptionLong: "检测 API Key、私钥、JWT Token、密码等敏感凭据泄漏。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.check_internal_ip",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "检测内网 IP",
			DescriptionLong: "检测 RFC1918 私有 IP 地址泄漏。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.check_jailbreak_response",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "检测越狱响应",
			DescriptionLong: "检测模型输出是否包含被越狱/角色劫持后的异常内容。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.check_instruction_injection_response",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "检测指令注入响应",
			DescriptionLong: "检测模型输出是否因提示词注入而泄露系统提示或执行异常指令。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		// 阈值
		{
			Key:             "output_compliance.pii_threshold",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Min:             floatPtr(0.0),
			Max:             floatPtr(1.0),
			Default:         0.7,
			Description:     "PII 检测阈值",
			DescriptionLong: "规则引擎命中即 1.0；模型引擎判定置信度需达到此阈值才进入后续动作逻辑。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.toxicity_threshold",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Min:             floatPtr(0.0),
			Max:             floatPtr(1.0),
			Default:         0.7,
			Description:     "毒性检测阈值",
			DescriptionLong: "关键词命中即 1.0；模型引擎判定置信度需达到此阈值才进入后续动作逻辑。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.bias_threshold",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Min:             floatPtr(0.0),
			Max:             floatPtr(1.0),
			Default:         0.6,
			Description:     "偏见检测阈值",
			DescriptionLong: "模型引擎判定置信度需达到此阈值才进入后续动作逻辑。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.hallucination_threshold",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Min:             floatPtr(0.0),
			Max:             floatPtr(1.0),
			Default:         0.7,
			Description:     "幻觉检测阈值",
			DescriptionLong: "模型引擎判定置信度需达到此阈值才进入后续动作逻辑。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		// 响应动作
		{
			Key:             "output_compliance.action_on_pii",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Options:         []string{"log", "warn", "redact", "block"},
			Default:         "redact",
			Description:     "PII 命中动作",
			DescriptionLong: "log：仅记录；warn：记录并升级治理评分；redact：自动脱敏；block：阻断响应。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.action_on_toxicity",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Options:         []string{"log", "warn", "redact", "block"},
			Default:         "warn",
			Description:     "毒性命中动作",
			DescriptionLong: "log：仅记录；warn：记录并升级治理评分；redact：替换为 toxic_replacement；block：阻断响应。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.action_on_bias",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Options:         []string{"log", "warn"},
			Default:         "log",
			Description:     "偏见命中动作",
			DescriptionLong: "log：仅记录；warn：记录并升级治理评分。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.action_on_secrets",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Options:         []string{"log", "warn", "redact", "block"},
			Default:         "redact",
			Description:     "密钥/凭据命中动作",
			DescriptionLong: "log：仅记录；warn：记录并升级治理评分；redact：自动脱敏；block：阻断响应。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.action_on_internal_ip",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Options:         []string{"log", "warn", "redact", "block"},
			Default:         "redact",
			Description:     "内网 IP 命中动作",
			DescriptionLong: "log：仅记录；warn：记录并升级治理评分；redact：自动脱敏；block：阻断响应。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.action_on_jailbreak_response",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Options:         []string{"log", "warn", "block"},
			Default:         "block",
			Description:     "越狱响应命中动作",
			DescriptionLong: "log：仅记录；warn：记录并升级治理评分；block：阻断响应。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.action_on_instruction_injection_response",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Options:         []string{"log", "warn", "block"},
			Default:         "block",
			Description:     "指令注入响应命中动作",
			DescriptionLong: "log：仅记录；warn：记录并升级治理评分；block：阻断响应。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		// 脱敏维度
		{
			Key:             "output_compliance.redact_email",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "脱敏邮箱",
			DescriptionLong: "命中邮箱 PII 时是否执行脱敏。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.redact_phone",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "脱敏手机号",
			DescriptionLong: "命中手机号 PII 时是否执行脱敏。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.redact_id_card",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "脱敏身份证",
			DescriptionLong: "命中身份证 PII 时是否执行脱敏。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.redact_credit_card",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "脱敏信用卡",
			DescriptionLong: "命中信用卡 PII 时是否执行脱敏。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.redact_bank_card",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "脱敏银行卡",
			DescriptionLong: "命中银行卡号时是否执行脱敏。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.redact_jwt",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "脱敏 JWT Token",
			DescriptionLong: "命中 JWT 结构 Token 时是否执行脱敏。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.redact_password",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "脱敏密码",
			DescriptionLong: "命中密码/Passphrase 模式时是否执行脱敏。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.toxic_replacement",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "[内容已过滤]",
			Description:     "毒性内容替换文本",
			DescriptionLong: "action_on_toxicity=redact 时，命中内容被替换为该文本。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.block_message",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "响应因合规策略被阻断",
			Description:     "阻断提示文案",
			DescriptionLong: "命中动作为 block 时返回给调用方的默认文案。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.strict_mode",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "严格模式",
			DescriptionLong: "任一命中 severity>=9 的问题直接导致阻断（等价于所有类型 action=block）。",
			DangerLevel:     Breaking,
			HotReload:       true,
		},
		// 数据保留与采样
		{
			Key:             "output_compliance.retention_days",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Min:             floatPtr(0.0),
			Max:             floatPtr(3650.0),
			Default:         90,
			Description:     "审计日志保留天数",
			DescriptionLong: "output_compliance_audit 日志保留天数，0 表示永久。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.sampling_rate",
			Type:            TypeFloat,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Min:             floatPtr(0.0),
			Max:             floatPtr(1.0),
			Default:         1.0,
			Description:     "采样率",
			DescriptionLong: "每轮输出被送入检测的概率；1.0=全量检测，0=关闭检测（不影响策略开关）。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		// 告警与学习
		{
			Key:             "output_compliance.realtime_alert_enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "启用实时告警",
			DescriptionLong: "命中高严重度问题时通过配置通道发送告警。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.alert_threshold_severity",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Min:             floatPtr(1.0),
			Max:             floatPtr(10.0),
			Default:         7,
			Description:     "告警严重度阈值",
			DescriptionLong: "命中问题 severity >= 此值时触发实时告警。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.alert_aggregation_window_minutes",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         5,
			Description:     "告警聚合窗口（分钟）",
			DescriptionLong: "同一问题类型在窗口期内只发送一次告警，避免告警风暴。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.auto_review_queue_enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "启用人工复核队列",
			DescriptionLong: "高严重度命中自动进入 output_compliance_review_queue 供人工复核。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.feedback_loop_enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "启用反馈闭环",
			DescriptionLong: "记录误报/漏报反馈，用于后续阈值调优。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.skill_generation_enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "启用安全改写/技能生成",
			DescriptionLong: "命中时自动生成合规改写建议或团队安全技能（需 LLM 引擎）。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.auto_threshold_tuning_enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "自动阈值调优",
			DescriptionLong: "基于反馈闭环数据自动微调阈值（实验性）。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "output_compliance.llm_engine_id",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         0,
			Description:     "模型检测引擎 ID",
			DescriptionLong: "用于偏见/幻觉/越狱响应/技能生成等场景关联 prompt_injection_llm_engines 的引擎 ID，0 表示不指定。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "session_audit.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "会话审计与审批",
			DescriptionLong: "高风险会话自动触发审计审批流程。管理员可以批准/拒绝高风险操作。关闭后所有会话直接放行。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "session_inspector.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "会话健康检查",
			DescriptionLong: "监控会话 token 限制、不活跃超时、高频请求等健康指标。关闭后跳过所有会话健康检查。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "security.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "安全检测（意图+威胁）",
			DescriptionLong: "意图分析与威胁检测引擎。识别恶意意图（越狱、数据泄露）并触发预设响应策略。关闭后跳过所有安全检测。",
			DangerLevel:     Dangerous,
			HotReload:       true,
		},
		{
			Key:             "rate_limit.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "限流控制",
			DescriptionLong: "RPM / 并发 / TPM 多维度流量控制。关闭后将不限制任何请求速率（危险操作，仅限调试场景）。",
			DangerLevel:     Breaking,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         false,
			Description:     "飞书机器人集成",
			DescriptionLong: "对接飞书机器人实现远程运维：告警通知、审批执行、状态查询。需要先配置 Webhook URL 和验证令牌。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.webhook_url",
			Type:            TypeURL,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "飞书机器人 Webhook URL",
			DescriptionLong: "飞书自定义机器人的 Webhook 地址（格式：https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxx）。必须先启用飞书机器人模块。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.verify_token",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "飞书机器人验证令牌",
			DescriptionLong: "用于验证飞书回调请求来源的签名令牌。可在飞书机器人安全设置中获取。留空则不验证签名。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.notify_on_alert",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "告警推送",
			DescriptionLong: "当系统检测到异常（注入攻击、高延迟、错误率飙升）时自动推送飞书消息。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.notify_on_approval",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         true,
			Description:     "审批通知",
			DescriptionLong: "高风险会话需要审批时通过飞书通知管理员。管理员可直接在飞书消息中操作审批。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:             "feishu_bot.allowed_users",
			Type:            TypeString,
			Scope:           ScopePlatform,
			Category:        CategoryModules,
			Default:         "",
			Description:     "飞书白名单用户",
			DescriptionLong: "允许通过飞书执行操作的用户 OpenID 列表（逗号分隔）。留空表示允许所有已绑定用户。",
			DangerLevel:     Safe,
			HotReload:       true,
		},
	}
}

// IsSessionAnalyticsEnabled reads the session_analytics.enabled setting
// (platform fallback) to decide whether the analysis hook plugin is active.
// Mirrors resolveModuleEnabled in admin/modules.go but usable from the
// pipeline/hook layer without an HTTP request.
func IsSessionAnalyticsEnabled() bool {
	if Global == nil {
		return false
	}
	sp := Global.Spec("session_analytics.enabled")
	if sp == nil {
		return false
	}
	raw, _, err := Global.EffectiveValue(sp.Scope, sp.Key, "")
	if err != nil || raw == nil {
		return false
	}
	var v bool
	if err := json.Unmarshal(raw, &v); err != nil {
		return false
	}
	return v
}
