package settings

// SessionsV2Specs contains Sessions V2 feature flag configuration.
//
// 会话优化V2灰度发布的Feature Flag控制配置。
// 用于控制新表体系(sessions/session_turns/session_bodies)的流量路由。
//
// Created: 2026-07-17, Migration 430
func SessionsV2Specs() []*Spec {
	return []*Spec{
		{
			Key:             "sessions_v2.enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         false,
			Description:     "Sessions V2 总开关",
			DescriptionLong: "启用会话存储V2架构。关闭时完全使用request_logs，开启后根据其他开关决定读写路由。",
			Unit:            "",
			DangerLevel:     Dangerous,
			HotReload:       true,
			Observability:   "/api/admin/sessions/v2/status",
		},
		{
			Key:             "sessions_v2.shadow_write",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         false,
			Description:     "启用副写模式",
			DescriptionLong: "副写模式：同时写入request_logs和V2表，但仅从request_logs读取。用于验证V2表写入正确性。需要enabled=true。",
			Unit:            "",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/sessions/v2/shadow_metrics",
		},
		{
			Key:             "sessions_v2.rollout_percent",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         0,
			Description:     "灰度百分比",
			DescriptionLong: "V2表的流量灰度百分比(0-100)。0表示不路由到V2，100表示全部路由到V2。基于session_id哈希决定路由。",
			Unit:            "%",
			DangerLevel:     Dangerous,
			HotReload:       true,
			Observability:   "/api/admin/sessions/v2/rollout_stats",
			Min:             floatPtr(0),
			Max:             floatPtr(100),
		},
		{
			Key:             "sessions_v2.l3_read",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         false,
			Description:     "启用从V2表读取(L3缓存)",
			DescriptionLong: "启用从session_turns读取会话数据作为L3缓存。需要enabled=true。",
			Unit:            "",
			DangerLevel:     Dangerous,
			HotReload:       true,
			Observability:   "/api/admin/sessions/v2/l3_hit_rate",
		},
		{
			Key:             "sessions_v2.dual_read",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         false,
			Description:     "双读对账模式",
			DescriptionLong: "同时读取request_logs和V2表，对比结果差异并记录。用于验证V2读取正确性。需要enabled=true且l3_read=true。",
			Unit:            "",
			DangerLevel:     Warning,
			HotReload:       true,
			Observability:   "/api/admin/sessions/v2/dual_read_diff",
		},
		{
			Key:             "sessions_v2.primary_read",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         false,
			Description:     "V2作为主读取源",
			DescriptionLong: "将V2表作为主读取源，request_logs作为降级备份。需要enabled=true且l3_read=true。与dual_read互斥。",
			Unit:            "",
			DangerLevel:     Breaking,
			HotReload:       true,
			Observability:   "/api/admin/sessions/v2/primary_read_stats",
		},
		{
			Key:             "sessions_v2.write_timeout_ms",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         500,
			Description:     "V2写入超时时间",
			DescriptionLong: "写入V2表的超时时间(毫秒)。超时后不阻塞主流程，异步重试。",
			Unit:            "毫秒",
			DangerLevel:     Safe,
			HotReload:       true,
			Min:             floatPtr(100),
			Max:             floatPtr(5000),
		},
		{
			Key:             "sessions_v2.read_timeout_ms",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         300,
			Description:     "V2读取超时时间",
			DescriptionLong: "从V2表读取的超时时间(毫秒)。超时后降级到request_logs。",
			Unit:            "毫秒",
			DangerLevel:     Safe,
			HotReload:       true,
			Min:             floatPtr(50),
			Max:             floatPtr(3000),
		},
		{
			// R29 审计（2026-09-15）：mirror shadow-write 失败登记（712
			// session_mirror_outbox）与重放器的 kill switch。未注册时
			// getPlatformBool 对 Spec==nil 直接返回 fallback 不读
			// settings_kv——运维 PUT 无效，应急热关能力落空。
			Key:             "sessions_v2.mirror_outbox",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         true,
			Description:     "Mirror 失败登记开关",
			DescriptionLong: "shadow-write 失败的会话轮次持久登记到 session_mirror_outbox（迁移 712）。关闭后失败行只进进程内 backlog（重启即丢，GAP-2 修复前行为）。",
			Unit:            "",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "sessions_v2.mirror_outbox_replay",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         true,
			Description:     "Mirror 失败重放开关",
			DescriptionLong: "MirrorOutboxReaper 周期重放 session_mirror_outbox 欠账行到 V2 表。关闭后登记行滞留（pending gauge 持续增长），用于应急止血。",
			Unit:            "",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "sessions_v2.mirror_outbox_max_attempts",
			Type:            TypeInt,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Min:             floatPtr(5),
			Max:             floatPtr(30),
			Default:         10,
			Description:     "Mirror 失败重放次数上限",
			DescriptionLong: "session_mirror_outbox 欠账行重放多少次后转入 dead-letter（重放次数 >= 本值即 markDead）。MirrorOutboxReaper.requeue 每次调用都经 currentMaxAtts 重新读取本键，因此改动**即时生效、无需重启**。范围 5-30：下限防止一次配置失误把每一行都在首次失败时就判死（欠账被静默吞掉），上限防止把重试路径饿死。越界值由 Go 侧 currentMaxAtts 钳制到 [5,30]，故登记 Min/Max 与代码钳制必须同时存在——只写消费点不登记本键会让 GetPlatformInt 恒返回 fallback，热重载形同虚设（审计 §23 F-15）。",
			Unit:            "次",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			Key:             "sessions_v2.compression_enabled",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         true,
			Description:     "启用V2压缩检测",
			DescriptionLong: "检测客户端是否已压缩会话历史，标记submit_mode字段。",
			Unit:            "",
			DangerLevel:     Safe,
			HotReload:       true,
		},
		{
			Key:         "sessions_v2.turn_logs_retention_hours",
			Type:        TypeInt,
			Scope:       ScopePlatform,
			Category:    CategorySession,
			Default:     24,
			Description: "环节日志保留时间（已废弃，无效果）",
			// R73 审计 B-F6：该键自登记起无任何 Get 消费者——turn_logs 的
			// 活 TTL 键是 lifecycle.session_turn_logs_ttl_hours（写入端
			// turn_logs_writer 与清扫端 partition_manager 双端消费）。
			// 原 DescriptionLong「超时后自动清理」为假（F-15 同类：登记
			// 未消费第 5 例）。改为此废弃声明防误导运维；键本身保留以
			// 兼容已存过该键的 settings 存储，下一清理轮连同
			// spec_sessions_v2_test.go 的键清单一起删除。
			DescriptionLong: "已废弃别名：真实生效键为 lifecycle.session_turn_logs_ttl_hours（Min1/Max168/Default24）。本键修改无任何效果。",
			Unit:            "小时",
			DangerLevel:     Safe,
			HotReload:       true,
			Min:             floatPtr(1),
			Max:             floatPtr(168), // 7天
		},
		{
			Key:             "sessions_v2.turns_list_routing",
			Type:            TypeEnum,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         "tree",
			Options:         []string{"tree", "dual", "v2"},
			Description:     "会话轮次列表路由模式",
			DescriptionLong: "控制 /api/admin/sessions/{id}/turns 使用 tree、dual 对账或统一 V2 metadata 契约。",
			DangerLevel:     Warning,
			HotReload:       true,
		},
		{
			// CO-5 (docs/修订0811/19 §3): sessions_v2.enabled 时
			// 兼容保留的旧开关。新请求始终保存完整请求/响应体；历史 false
			// 值不再启用摘要信封，避免大请求的唯一审计副本被截断。
			Key:             "sessions_v2.request_bodies_full",
			Type:            TypeBool,
			Scope:           ScopePlatform,
			Category:        CategorySession,
			Default:         true,
			Description:     "sessions_v2 启用时仍全量落库请求/响应体",
			DescriptionLong: "兼容旧配置项：新请求始终全量保存 request_logs_bodies。历史 false 值不再启用摘要写入；已有摘要信封仍可读取。",
			Unit:            "",
			DangerLevel:     Warning,
			HotReload:       true,
		},
	}
}
