-- Migration 573 DOWN: re-add request body columns (NULLABLE jsonb) on
-- request_logs_hot and request_logs (parent + partitions), and restore
-- the body projection in request_logs_with_current_month view.
--
-- This is a structural revert only — no data backfill. Rows that were
-- NULL on these columns before LP1 remain NULL after the down; the only
-- source of body content in production is request_logs_bodies_hot /
-- request_logs_bodies (LP1 moved it there permanently).

BEGIN;

-- ─── 1. Re-add body columns (NULLABLE — historical rows preserved as NULL) ───
ALTER TABLE public.request_logs_hot ADD COLUMN IF NOT EXISTS request_body jsonb;
ALTER TABLE public.request_logs_hot ADD COLUMN IF NOT EXISTS response_body jsonb;
ALTER TABLE public.request_logs_hot ADD COLUMN IF NOT EXISTS outbound_body jsonb;

ALTER TABLE public.request_logs ADD COLUMN IF NOT EXISTS request_body jsonb;
ALTER TABLE public.request_logs ADD COLUMN IF NOT EXISTS response_body jsonb;
ALTER TABLE public.request_logs ADD COLUMN IF NOT EXISTS outbound_body jsonb;

-- ─── 2. Restore view body projection ───
-- Note: this restores the projection list verbatim from migration 459
-- (2026-07-27 SSOT). SSOT canonical projection lives in
-- sql/objects/views/request_logs_with_current_month.sql; keep both
-- copies in sync (rule 38 §11).
CREATE OR REPLACE VIEW public.request_logs_with_current_month AS
 SELECT request_logs_hot.id,
    request_logs_hot.request_id,
    request_logs_hot.ts,
    request_logs_hot.tenant_id,
    request_logs_hot.application_id,
    request_logs_hot.api_key_id,
    request_logs_hot.end_user_id,
    request_logs_hot.client_model,
    request_logs_hot.outbound_model,
    request_logs_hot.credential_id,
    request_logs_hot.provider_id,
    request_logs_hot.canonical_id,
    request_logs_hot.client_profile,
    request_logs_hot.request_mode,
    request_logs_hot.prompt_tokens,
    request_logs_hot.completion_tokens,
    request_logs_hot.total_tokens,
    request_logs_hot.cost_usd,
    request_logs_hot.latency_ms,
    request_logs_hot.success,
    request_logs_hot.error_kind,
    request_logs_hot.search_text,
    request_logs_hot.cache_read_tokens,
    request_logs_hot.cache_write_tokens,
    request_logs_hot.identity_hash,
    request_logs_hot.virtual_client_id,
    request_logs_hot.virtual_ip,
    request_logs_hot.virtual_mac,
    request_logs_hot.affinity_hit,
    request_logs_hot.stream_first_chunk_ms,
    request_logs_hot.stream_chunk_count,
    request_logs_hot.stream_interrupted,
    request_logs_hot.stream_done_sent,
    request_logs_hot.request_checksum,
    request_logs_hot.response_checksum,
    request_logs_hot.transform_rule_id,
    request_logs_hot.egress_protocol,
    request_logs_hot.failure_stage,
    request_logs_hot.failure_detail_code,
    request_logs_hot.request_preview,
    request_logs_hot.transform_summary,
    request_logs_hot.response_preview,
    request_logs_hot.stream_done_received,
    request_logs_hot.request_body,
    request_logs_hot.response_body,
    request_logs_hot.cost_display,
    request_logs_hot.cost_currency,
    request_logs_hot.usage_source,
    request_logs_hot.gw_session_id,
    request_logs_hot.gw_task_id,
    request_logs_hot.request_status,
    request_logs_hot.api_key_prefix,
    request_logs_hot.owner_user,
    request_logs_hot.application_code,
    request_logs_hot.key_alias,
    request_logs_hot.api_key_owner_user,
    request_logs_hot.is_auto_request,
    request_logs_hot.task_type,
    request_logs_hot.auto_profile,
    request_logs_hot.auto_decision,
    request_logs_hot.auto_confidence,
    request_logs_hot.work_type,
    request_logs_hot.task_type_chosen,
    request_logs_hot.confidence_num,
    request_logs_hot.model_chosen,
    request_logs_hot.strategy_used,
    request_logs_hot.credits_charged,
    request_logs_hot.parent_request_id,
    request_logs_hot.compression_reason,
    request_logs_hot.compression_strategy,
    request_logs_hot.compression_meta,
    request_logs_hot.outbound_body,
    request_logs_hot.outbound_msg_count,
    request_logs_hot.outbound_token_est,
    request_logs_hot.outbound_msg_hashes,
    request_logs_hot.quality_flags,
    request_logs_hot.quality_fix_actions,
    request_logs_hot.quality_score,
    request_logs_hot.upstream_finish_reason,
    request_logs_hot.tool_calls,
    request_logs_hot.client_endpoint,
    request_logs_hot.client_timeout,
    request_logs_hot.stream_chunk_errors,
    request_logs_hot.stream_chunks_sent,
    request_logs_hot.client_request_id,
    request_logs_hot.upstream_status_code,
    request_logs_hot.test_col,
    request_logs_hot.test_tab_indent,
    request_logs_hot.provider_model,
    request_logs_hot.attachments,
    request_logs_hot.has_attachments,
    request_logs_hot.attachment_count,
    request_logs_hot.routing_attempts,
    request_logs_hot.routing_summary,
    request_logs_hot.agent_name,
    request_logs_hot.agent_type,
    request_logs_hot.client_protocol,
    request_logs_hot.canonical_model,
    request_logs_hot.t0_arrived_at,
    request_logs_hot.t1_total_enqueued_at,
    request_logs_hot.t2_total_dequeued_at,
    request_logs_hot.t3_model_enqueued_at,
    request_logs_hot.t4_model_dequeued_at,
    request_logs_hot.t5_cred_enqueued_at,
    request_logs_hot.t6_cred_dequeued_at,
    request_logs_hot.t7_forward_start_at,
    request_logs_hot.t8_response_start_at,
    request_logs_hot.t9_response_end_at,
    request_logs_hot.request_type,
    request_logs_hot.is_final_success,
    request_logs_hot.origin_actor
   FROM public.request_logs_hot
UNION ALL
 SELECT request_logs.id,
    request_logs.request_id,
    request_logs.ts,
    request_logs.tenant_id,
    request_logs.application_id,
    request_logs.api_key_id,
    request_logs.end_user_id,
    request_logs.client_model,
    request_logs.outbound_model,
    request_logs.credential_id,
    request_logs.provider_id,
    request_logs.canonical_id,
    request_logs.client_profile,
    request_logs.request_mode,
    request_logs.prompt_tokens,
    request_logs.completion_tokens,
    request_logs.total_tokens,
    request_logs.cost_usd,
    request_logs.latency_ms,
    request_logs.success,
    request_logs.error_kind,
    request_logs.search_text,
    request_logs.cache_read_tokens,
    request_logs.cache_write_tokens,
    request_logs.identity_hash,
    request_logs.virtual_client_id,
    request_logs.virtual_ip,
    request_logs.virtual_mac,
    request_logs.affinity_hit,
    request_logs.stream_first_chunk_ms,
    request_logs.stream_chunk_count,
    request_logs.stream_interrupted,
    request_logs.stream_done_sent,
    request_logs.request_checksum,
    request_logs.response_checksum,
    request_logs.transform_rule_id,
    request_logs.egress_protocol,
    request_logs.failure_stage,
    request_logs.failure_detail_code,
    request_logs.request_preview,
    request_logs.transform_summary,
    request_logs.response_preview,
    request_logs.stream_done_received,
    request_logs.request_body,
    request_logs.response_body,
    request_logs.cost_display,
    request_logs.cost_currency,
    request_logs.usage_source,
    request_logs.gw_session_id,
    request_logs.gw_task_id,
    request_logs.request_status,
    request_logs.api_key_prefix,
    request_logs.owner_user,
    request_logs.application_code,
    request_logs.key_alias,
    request_logs.api_key_owner_user,
    request_logs.is_auto_request,
    request_logs.task_type,
    request_logs.auto_profile,
    request_logs.auto_decision,
    request_logs.auto_confidence,
    request_logs.work_type,
    request_logs.task_type_chosen,
    request_logs.confidence_num,
    request_logs.model_chosen,
    request_logs.strategy_used,
    request_logs.credits_charged,
    request_logs.parent_request_id,
    request_logs.compression_reason,
    request_logs.compression_strategy,
    request_logs.compression_meta,
    request_logs.outbound_body,
    request_logs.outbound_msg_count,
    request_logs.outbound_token_est,
    request_logs.outbound_msg_hashes,
    request_logs.quality_flags,
    request_logs.quality_fix_actions,
    request_logs.quality_score,
    request_logs.upstream_finish_reason,
    request_logs.tool_calls,
    request_logs.client_endpoint,
    request_logs.client_timeout,
    request_logs.stream_chunk_errors,
    request_logs.stream_chunks_sent,
    request_logs.client_request_id,
    request_logs.upstream_status_code,
    request_logs.test_col,
    request_logs.test_tab_indent,
    request_logs.provider_model,
    request_logs.attachments,
    request_logs.has_attachments,
    request_logs.attachment_count,
    request_logs.routing_attempts,
    request_logs.routing_summary,
    request_logs.agent_name,
    request_logs.agent_type,
    request_logs.client_protocol,
    request_logs.canonical_model,
    request_logs.t0_arrived_at,
    request_logs.t1_total_enqueued_at,
    request_logs.t2_total_dequeued_at,
    request_logs.t3_model_enqueued_at,
    request_logs.t4_model_dequeued_at,
    request_logs.t5_cred_enqueued_at,
    request_logs.t6_cred_dequeued_at,
    request_logs.t7_forward_start_at,
    request_logs.t8_response_start_at,
    request_logs.t9_response_end_at,
    request_logs.request_type,
    request_logs.is_final_success,
    request_logs.origin_actor
   FROM public.request_logs;

COMMIT;

-- Post-revert verification:
--   ./scripts/check-body-storage-schema.sh
--   expected: exit 1 (would mean we're back to pre-LP1 state; investigate
--   before any further action)