-- Migration 629: audit_attachments_cleanup — append-only tombstones for
-- attachment-cleanup operations. Solves audit-data-closure-B (2026-08-31):
-- the existing handleDataLifecycleAttachmentCleanupExecute does a silent
-- UPDATE on request_logs_hot without recording who ran the cleanup, when,
-- with what retention threshold, or which (request_id, attachment_hash) pairs
-- were affected. Columnar historical partitions cannot be UPDATEd at all,
-- so a future operator cannot tell whether a historical request's metadata
-- was ever cleaned.
--
-- Design choices:
-- - Heap table (NOT columnar, NOT partitioned) so cleanup ops INSERT quickly
--   and the table itself never has to be vacuumed aggressively. Cleanup
--   runs are infrequent (weekly / monthly) so growth is bounded.
-- - cleanup_run_id is a UUID generated by the caller so multiple cleanup
--   transactions in one request share the same run id and can be diffed
--   against a single operator action.
-- - (request_id, attachment_hash) is unique so re-running cleanup with a
--   smaller older_than_days is idempotent at the row level.
-- - We do NOT add RLS at the table level; cleanup is a super-admin-only
--   action and the access path (handleDataLifecycleAttachmentCleanupExecute)
--   already enforces that gate. Future reader endpoints must respect the
--   super_admin check before exposing rows.

BEGIN;

CREATE TABLE IF NOT EXISTS public.audit_attachments_cleanup (
    cleanup_run_id    uuid        NOT NULL,
    tenant_id         text        NOT NULL,
    request_id        text        NOT NULL,
    attachment_hash   text        NOT NULL,
    cleaned_at        timestamptz NOT NULL DEFAULT NOW(),
    older_than_days   integer     NOT NULL CHECK (older_than_days > 0),
    triggered_by_user text        NOT NULL,
    reason            text,
    CONSTRAINT audit_attachments_cleanup_unique
        UNIQUE (request_id, attachment_hash, cleanup_run_id)
);

CREATE INDEX IF NOT EXISTS idx_audit_attachments_cleanup_run
    ON public.audit_attachments_cleanup (cleanup_run_id);

CREATE INDEX IF NOT EXISTS idx_audit_attachments_cleanup_request
    ON public.audit_attachments_cleanup (request_id, cleaned_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_attachments_cleanup_tenant_ts
    ON public.audit_attachments_cleanup (tenant_id, cleaned_at DESC);

COMMIT;
