-- Rollback Migration 707: session_turns wide-table backfill columns.
--
-- Drops the 50 nullable columns from BOTH parent and hot (restoring the 688
-- column contract) and the two partial unique indexes. Any data written into
-- the backfill columns between up and down is destroyed — 707 is only safe to
-- reverse while the S1b writers are still flag-gated OFF (defaults). The
-- promote function rewrite is intentionally kept: the SELECT * body with the
-- ordered contract check is equally correct for the narrow pre-707 shape, so
-- no function rollback is needed.
--
-- The schema_migrations row is kept (append-only ledger convention).

DROP INDEX IF EXISTS public.uq_session_turns_hot_final_success;
DROP INDEX IF EXISTS public.uq_session_turns_final_success;

ALTER TABLE public.session_turns_hot
    DROP COLUMN IF EXISTS request_delta,
    DROP COLUMN IF EXISTS response_delta,
    DROP COLUMN IF EXISTS is_final_success,
    DROP COLUMN IF EXISTS api_key_id,
    DROP COLUMN IF EXISTS application_id,
    DROP COLUMN IF EXISTS end_user_id,
    DROP COLUMN IF EXISTS customer_id,
    DROP COLUMN IF EXISTS credits_charged,
    DROP COLUMN IF EXISTS cost_display,
    DROP COLUMN IF EXISTS cost_currency,
    DROP COLUMN IF EXISTS work_type,
    DROP COLUMN IF EXISTS token_band,
    DROP COLUMN IF EXISTS usage_source,
    DROP COLUMN IF EXISTS is_auto_request,
    DROP COLUMN IF EXISTS auto_decision,
    DROP COLUMN IF EXISTS auto_confidence,
    DROP COLUMN IF EXISTS task_type_chosen,
    DROP COLUMN IF EXISTS routing_attempts,
    DROP COLUMN IF EXISTS routing_summary,
    DROP COLUMN IF EXISTS canonical_id,
    DROP COLUMN IF EXISTS canonical_model,
    DROP COLUMN IF EXISTS raw_model_name,
    DROP COLUMN IF EXISTS trace_events,
    DROP COLUMN IF EXISTS failure_stage,
    DROP COLUMN IF EXISTS failure_detail_code,
    DROP COLUMN IF EXISTS upstream_status_code,
    DROP COLUMN IF EXISTS upstream_finish_reason,
    DROP COLUMN IF EXISTS stream_first_chunk_ms,
    DROP COLUMN IF EXISTS stream_chunk_count,
    DROP COLUMN IF EXISTS stream_interrupted,
    DROP COLUMN IF EXISTS stream_done_sent,
    DROP COLUMN IF EXISTS client_request_id,
    DROP COLUMN IF EXISTS client_endpoint,
    DROP COLUMN IF EXISTS client_timeout,
    DROP COLUMN IF EXISTS egress_protocol,
    DROP COLUMN IF EXISTS search_text,
    DROP COLUMN IF EXISTS request_preview,
    DROP COLUMN IF EXISTS response_preview,
    DROP COLUMN IF EXISTS transform_summary,
    DROP COLUMN IF EXISTS identity_hash,
    DROP COLUMN IF EXISTS request_checksum,
    DROP COLUMN IF EXISTS response_checksum,
    DROP COLUMN IF EXISTS system_fingerprint,
    DROP COLUMN IF EXISTS origin_stage,
    DROP COLUMN IF EXISTS origin_actor,
    DROP COLUMN IF EXISTS client_ip,
    DROP COLUMN IF EXISTS client_forwarded_for,
    DROP COLUMN IF EXISTS agent_name,
    DROP COLUMN IF EXISTS agent_type,
    DROP COLUMN IF EXISTS virtual_client_id;

ALTER TABLE public.session_turns
    DROP COLUMN IF EXISTS request_delta,
    DROP COLUMN IF EXISTS response_delta,
    DROP COLUMN IF EXISTS is_final_success,
    DROP COLUMN IF EXISTS api_key_id,
    DROP COLUMN IF EXISTS application_id,
    DROP COLUMN IF EXISTS end_user_id,
    DROP COLUMN IF EXISTS customer_id,
    DROP COLUMN IF EXISTS credits_charged,
    DROP COLUMN IF EXISTS cost_display,
    DROP COLUMN IF EXISTS cost_currency,
    DROP COLUMN IF EXISTS work_type,
    DROP COLUMN IF EXISTS token_band,
    DROP COLUMN IF EXISTS usage_source,
    DROP COLUMN IF EXISTS is_auto_request,
    DROP COLUMN IF EXISTS auto_decision,
    DROP COLUMN IF EXISTS auto_confidence,
    DROP COLUMN IF EXISTS task_type_chosen,
    DROP COLUMN IF EXISTS routing_attempts,
    DROP COLUMN IF EXISTS routing_summary,
    DROP COLUMN IF EXISTS canonical_id,
    DROP COLUMN IF EXISTS canonical_model,
    DROP COLUMN IF EXISTS raw_model_name,
    DROP COLUMN IF EXISTS trace_events,
    DROP COLUMN IF EXISTS failure_stage,
    DROP COLUMN IF EXISTS failure_detail_code,
    DROP COLUMN IF EXISTS upstream_status_code,
    DROP COLUMN IF EXISTS upstream_finish_reason,
    DROP COLUMN IF EXISTS stream_first_chunk_ms,
    DROP COLUMN IF EXISTS stream_chunk_count,
    DROP COLUMN IF EXISTS stream_interrupted,
    DROP COLUMN IF EXISTS stream_done_sent,
    DROP COLUMN IF EXISTS client_request_id,
    DROP COLUMN IF EXISTS client_endpoint,
    DROP COLUMN IF EXISTS client_timeout,
    DROP COLUMN IF EXISTS egress_protocol,
    DROP COLUMN IF EXISTS search_text,
    DROP COLUMN IF EXISTS request_preview,
    DROP COLUMN IF EXISTS response_preview,
    DROP COLUMN IF EXISTS transform_summary,
    DROP COLUMN IF EXISTS identity_hash,
    DROP COLUMN IF EXISTS request_checksum,
    DROP COLUMN IF EXISTS response_checksum,
    DROP COLUMN IF EXISTS system_fingerprint,
    DROP COLUMN IF EXISTS origin_stage,
    DROP COLUMN IF EXISTS origin_actor,
    DROP COLUMN IF EXISTS client_ip,
    DROP COLUMN IF EXISTS client_forwarded_for,
    DROP COLUMN IF EXISTS agent_name,
    DROP COLUMN IF EXISTS agent_type,
    DROP COLUMN IF EXISTS virtual_client_id;
