-- 757 down: 撤回 session_turns_with_current_month 的 origin_actor 投影
--
-- ⚠️ 同样禁止把 CREATE OR REPLACE VIEW 包进 DO 块的 EXECUTE——实测在 PL/pgSQL
--    EXECUTE 里它**静默无效**（不报错、视图不变）。必须顶层执行，见 up 文件头。
--
-- ⚠️ 撤回后，v2SessionBodiesBaseQuery 与 sessionTurnDigestQuery 会重新变成
--    ERROR: column t.origin_actor does not exist。**这个 down 只用于验证回滚路径，
--    不要在生产执行**——那等于把 R79 续十六 定位的 P1 原样装回去。

CREATE OR REPLACE VIEW public.session_turns_with_current_month AS
 SELECT hot.id,
    hot.session_id,
    hot.turn_no,
    hot.tenant_id,
    hot.request_id,
    hot.project_id,
    hot.namespace,
    hot.parent_request_id,
    hot.task_type,
    hot.ts,
    hot.submit_mode,
    hot.compression_applied,
    hot.compression_strategy,
    hot.compression_meta,
    hot.compression_tokens_saved,
    hot.injection_verdict,
    hot.output_verdict,
    hot.model,
    hot.provider,
    hot.credential_id,
    hot.prompt_tokens,
    hot.completion_tokens,
    hot.cache_read_tokens,
    hot.cache_write_tokens,
    hot.cost_usd,
    hot.latency_ms,
    hot.status_code,
    hot.success,
    hot.error_kind,
    hot.source_kind,
    hot.quality,
    hot.partition_date,
    hot.attachment_count,
    hot.attachment_total_bytes,
    hot.multimodal_types,
    hot.attempt_no,
    hot.tools,
    hot.title,
    hot.summary,
    hot.digest,
    hot.aggregate_applied_at,
    hot.t0_arrived_at,
    hot.t1_total_enqueued_at,
    hot.t2_total_dequeued_at,
    hot.t3_model_enqueued_at,
    hot.t4_model_dequeued_at,
    hot.t5_cred_enqueued_at,
    hot.t6_cred_dequeued_at,
    hot.t7_forward_start_at,
    hot.t8_response_start_at,
    hot.t9_response_end_at,
    hot.client_protocol,
    hot.upstream_protocol,
    hot.ir_metadata
   FROM session_turns_hot hot
  WHERE NOT (EXISTS ( SELECT 1
           FROM session_turns archived
          WHERE archived.tenant_id::text = hot.tenant_id::text AND archived.request_id = hot.request_id))
UNION ALL
 SELECT session_turns.id,
    session_turns.session_id,
    session_turns.turn_no,
    session_turns.tenant_id,
    session_turns.request_id,
    session_turns.project_id,
    session_turns.namespace,
    session_turns.parent_request_id,
    session_turns.task_type,
    session_turns.ts,
    session_turns.submit_mode,
    session_turns.compression_applied,
    session_turns.compression_strategy,
    session_turns.compression_meta,
    session_turns.compression_tokens_saved,
    session_turns.injection_verdict,
    session_turns.output_verdict,
    session_turns.model,
    session_turns.provider,
    session_turns.credential_id,
    session_turns.prompt_tokens,
    session_turns.completion_tokens,
    session_turns.cache_read_tokens,
    session_turns.cache_write_tokens,
    session_turns.cost_usd,
    session_turns.latency_ms,
    session_turns.status_code,
    session_turns.success,
    session_turns.error_kind,
    session_turns.source_kind,
    session_turns.quality,
    session_turns.partition_date,
    session_turns.attachment_count,
    session_turns.attachment_total_bytes,
    session_turns.multimodal_types,
    session_turns.attempt_no,
    session_turns.tools,
    session_turns.title,
    session_turns.summary,
    session_turns.digest,
    session_turns.aggregate_applied_at,
    session_turns.t0_arrived_at,
    session_turns.t1_total_enqueued_at,
    session_turns.t2_total_dequeued_at,
    session_turns.t3_model_enqueued_at,
    session_turns.t4_model_dequeued_at,
    session_turns.t5_cred_enqueued_at,
    session_turns.t6_cred_dequeued_at,
    session_turns.t7_forward_start_at,
    session_turns.t8_response_start_at,
    session_turns.t9_response_end_at,
    session_turns.client_protocol,
    session_turns.upstream_protocol,
    session_turns.ir_metadata
   FROM session_turns;
