export PGPAGER=cat
export TERM=dumb
PSQL="psql -U llm_gateway -d llm_gateway -A -F| -t -P pager=off -v ON_ERROR_STOP=0"
echo "===== VERSION ====="
$PSQL -c "SELECT version();"
$PSQL -c "SELECT current_setting('server_version') AS srv, current_database() AS db, pg_postmaster_start_time() AS started, date_trunc('minute', now()-pg_postmaster_start_time()) AS uptime;"
echo "===== EXTENSIONS ====="
$PSQL -c "SELECT extname||' '||extversion FROM pg_extension ORDER BY 1;"
echo "===== CITUS / COLUMNAR PRESENCE ====="
$PSQL -c "SELECT count(*) FROM pg_dist_partition;"
$PSQL -c "SELECT count(*) AS columnar_tables FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE';"
echo "===== DB SIZES ====="
$PSQL -c "SELECT datname||' '||pg_size_pretty(pg_database_size(datname)) FROM pg_database ORDER BY pg_database_size(datname) DESC;"
echo "===== KEY SETTINGS ====="
$PSQL -c "SELECT name||' = '||setting||coalesce(unit,'')||'  ['||source||']' FROM pg_settings WHERE name IN ('shared_buffers','work_mem','maintenance_work_mem','effective_cache_size','max_connections','max_wal_size','min_wal_size','checkpoint_timeout','checkpoint_completion_target','wal_compression','random_page_cost','seq_page_cost','effective_io_concurrency','maintenance_io_concurrency','max_worker_processes','max_parallel_workers','max_parallel_workers_per_gather','max_parallel_maintenance_workers','jit','default_statistics_target','track_io_timing','log_min_duration_statement','autovacuum','autovacuum_vacuum_scale_factor','autovacuum_analyze_scale_factor','autovacuum_naptime','autovacuum_vacuum_insert_threshold','autovacuum_max_workers','default_toast_compression','wal_level','synchronous_commit','fsync','full_page_writes','plan_cache_mode','temp_file_limit','idle_in_transaction_session_timeout','statement_timeout','max_worker_processes','shared_preload_libraries','io_combine_limit','vacuum_buffer_usage_limit','vacuum_cost_limit','log_autovacuum_min_duration','deadlock_timeout','max_locks_per_transaction') ORDER BY 1;"
echo "===== PG_STAT_IO / PG_STAT_CHECKPOINTER ====="
$PSQL -c "SELECT count(*) FROM pg_stat_io;"
$PSQL -c "SELECT num_timed||'|'||num_requested||'|'||write_time||'|'||sync_time||'|'||read_time FROM pg_stat_checkpointer;"
echo "===== PG_STAT_DATABASE ====="
$PSQL -c "SELECT datname||' commits='||xact_commit||' rollbacks='||xact_rollback||' blks_hit='||blks_hit||' blks_read='||blks_read||' tup_ret='||tup_returned||' tup_ins='||tup_inserted||' tup_upd='||tup_updated||' tup_del='||tup_deleted||' conflicts='||conflicts||' temp_files='||temp_files||' temp_bytes='||temp_bytes||' deadlocks='||deadlocks||' blk_read_time_ms='||blk_read_time||' blk_write_time_ms='||blk_write_time FROM pg_stat_database WHERE datname='llm_gateway';"
echo "===== PG_STAT_BGWRITER ====="
$PSQL -c "SELECT 'checkpoints='||checkpoints||' timed='||checkpoints_timed||' buffers_checkpoint='||buffers_checkpoint||' buffers_clean='||buffers_clean||' maxwritten_clean='||maxwritten_clean||' buffers_alloc='||buffers_alloc||' stats_reset='||stats_reset FROM pg_stat_bgwriter;"
echo "===== CONTAINER RESOURCES ====="
nproc
free -m 2>/dev/null | head -3
df -h /var/lib/postgresql/data | tail -2
echo "===== TABLE COUNT BY KIND ====="
$PSQL -c "SELECT c.relkind||' '||CASE c.relkind WHEN 'r' THEN 'table' WHEN 'p' THEN 'part_table' WHEN 'v' THEN 'view' WHEN 'm' THEN 'matview' WHEN 'S' THEN 'sequence' WHEN 'i' THEN 'index' ELSE c.relkind::text END||' = '||count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' GROUP BY 1 ORDER BY 1;"
echo "===== SCHEMA OBJECTS ====="
$PSQL -c "SELECT (SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p')) AS tables, (SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind='i') AS indexes, (SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind='v') AS views, (SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind='m') AS matviews, (SELECT count(*) FROM pg_constraint ch JOIN pg_class c ON c.oid=ch.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public') AS constraints, (SELECT count(*) FROM pg_indexes WHERE schemaname='public') AS pg_indexes;"
echo "===== FUNCTIONS / TRIGGERS / RULES / POLICIES ====="
$PSQL -c "SELECT 'functions='||count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public';"
$PSQL -c "SELECT 'triggers='||count(*) FROM pg_trigger t WHERE NOT tgisinternal;"
$PSQL -c "SELECT 'rules='||count(*) FROM pg_rules WHERE schemaname='public';"
$PSQL -c "SELECT 'rls_policies='||count(*) FROM pg_policies WHERE schemaname='public';"
$PSQL -c "SELECT 'rls_enabled_tables='||count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relrowsecurity;"
