export default {
  title: 'Proxy-Verwaltung',
  tabs: { status: 'Statusübersicht', subscriptions: 'Abonnements', nodes: 'Knoten' },
  status: {
    overview: 'Übersicht', subscriptions: 'Aktive Abonnements', nodes: 'Gesamte Knoten', dialable: 'Wählbare Knoten', healthy: 'Gesunde Knoten', unhealthy: 'Ungesunde Knoten', selectedNode: 'Ausgewählter Knoten', noNodeSelected: 'Kein Knoten ausgewählt',
    swapState: 'Automatischer Wechselstatus', currentNode: 'Aktiver Knoten', lastProbeAt: 'Letzte Prüfung', consecutiveFails: 'Aufeinanderfolgende Fehler', probeInterval: 'Prüfintervall', swapIdle: 'Kein aktiver Knoten', regions: 'Regionsverteilung', policyTitle: 'Auswahlstrategie',
  },
  actions: { batchHealthCheckAll: 'Alle Knoten gesammelt prüfen', forceSwap: 'Wechsel zum besten Knoten erzwingen' },
  regions: { empty: 'Keine Knotendaten', region: 'Region', total: 'Gesamt', dialable: 'Wählbar', active: 'Aktiv', unhealthy: 'Ungesund', banned: 'Ausgeschlossen', avgLatency: 'Durchschn. Latenz', bestNode: 'Bester Knoten' },
  policy: { lbStrategy: 'Lastverteilungsstrategie', affinity: 'Standortaffinität', autoDisableThreshold: 'Schwelle für automatische Deaktivierung', autoDisableEnabled: 'Automatisch deaktivieren', autoRecoverEnabled: 'Automatisch wiederherstellen', swapIntervalMs: 'Wechselintervall (ms)', swapFailThreshold: 'Fehlerschwelle für Wechsel', edit: 'Strategie bearbeiten', editTitle: 'Auswahlstrategie bearbeiten', loading: 'Wird geladen…' },
  subscriptions: { create: 'Neues Abonnement', createTitle: 'Proxy-Abonnement erstellen', name: 'Name', url: 'Abonnement-URL', urlHint: 'Muss mit http:// oder https:// beginnen (Clash-Abonnement)', nodeCount: 'Knoten', status: 'Status', lastFetch: 'Letzte Abfrage', refresh: 'Aktualisieren', notes: 'Notizen', bannedRegions: 'Ausgeschlossene Regionen', bannedRegionsHint: 'Durch Kommas getrennt, z. B. US, JP, HK. Knoten in diesen Regionen werden bei der Auswahl gefiltert.', batchHealthCheck: 'Stapelprüfung', empty: 'Keine Abonnements' },
  nodes: { create: 'Neuer Knoten', createTitle: 'Proxy-Knoten erstellen', subscription: 'Abonnement', selectSubscription: 'Abonnement auswählen', protocolHint: 'Nur HTTP/HTTPS/SOCKS5 unterstützt; trojan/vless müssen über eine lokale Brücke bereitgestellt werden', healthCheck: 'Gesundheitsprüfung', empty: 'Keine Knoten' },
  node: { name: 'Name', protocol: 'Protokoll', server: 'Server', port: 'Port', username: 'Benutzername', password: 'Passwort', location: 'Standort', bannedRegions: 'Ausgeschlossene Regionen', dialable: 'Wählbar', status: 'Status', latency: 'Latenz', failures: 'Aufeinanderfolgende Fehler', healthCheckUrl: 'URL für Gesundheitsprüfung' },
  confirmRefresh: 'Abonnement „{name}“ aktualisieren?', confirmDeleteSub: 'Abonnement „{name}“ und alle seine Knoten löschen?', confirmHealthCheck: 'Gesundheitsprüfung für Knoten „{name}“ ausführen?', confirmDeleteNode: 'Knoten „{name}“ löschen?', confirmBatchAll: 'Stapelprüfung für alle Knoten ausführen? Das überspringt das intelligente Intervall und kann einige Sekunden dauern.', confirmBatchSub: 'Stapelprüfung für alle Knoten in Abonnement „{name}“ ausführen?',
  batchResult: { healthAll: 'Stapelprüfung abgeschlossen: erfolgreich {ok} / fehlgeschlagen {failed} / übersprungen {skipped}', healthSub: 'Stapelprüfung für Abonnement „{name}“: erfolgreich {ok} / fehlgeschlagen {failed}', swap: 'Wechsel zu Knoten erzwungen: {name}', policySaved: 'Strategie gespeichert und dauerhaft übernommen' },
  error: { loadStatusFailed: 'Fehler beim Laden des Status', loadSubsFailed: 'Fehler beim Laden der Abonnements', loadNodesFailed: 'Fehler beim Laden der Knoten', nameUrlRequired: 'Name und URL sind erforderlich', subscribeUrlMustHttp: 'Abonnement-URL muss mit http:// oder https:// beginnen', createSubFailed: 'Fehler beim Erstellen des Abonnements', refreshSubFailed: 'Fehler beim Aktualisieren des Abonnements', deleteSubFailed: 'Fehler beim Löschen des Abonnements', nodeFieldsRequired: 'Name, Server und Abonnement sind erforderlich', protocolNotDialable: 'Nur HTTP/HTTPS/SOCKS5 unterstützt; trojan/vless müssen über eine lokale Brücke bereitgestellt werden', createNodeFailed: 'Fehler beim Erstellen des Knotens', healthCheckFailed: 'Gesundheitsprüfung fehlgeschlagen', deleteNodeFailed: 'Fehler beim Löschen des Knotens', batchHealthFailed: 'Stapelprüfung fehlgeschlagen', swapFailed: 'Erzwungener Wechsel fehlgeschlagen', savePolicyFailed: 'Strategie konnte nicht gespeichert werden', saveSubBanFailed: 'Ausgeschlossene Regionen des Abonnements konnten nicht gespeichert werden', saveNodeBanFailed: 'Ausgeschlossene Regionen des Knotens konnten nicht gespeichert werden' },
}
