package admin

// auto_route_tuning.go — Phase 5 admin endpoints for the tuning feedback loop.
//
// These endpoints let admins review, approve, and apply tuning proposals
// generated by the feedback analyzer (Phase 4), and monitor classification
// accuracy over time.
//
// Endpoints (mounted under /api/admin/auto-route/tuning/*):
//
//	GET    /tuning/proposals            — list proposals (filter by status/category)
//	POST   /tuning/proposals/:id/approve — approve + apply a proposal
//	POST   /tuning/proposals/:id/reject  — reject a proposal (with reason)
//	GET    /tuning/accuracy              — 7-day accuracy dashboard
//
// All routes reuse the existing adminWrap middleware (bearer-token auth).
//
// Security notes (v2.1 audit fix #22):
//   - Internal DB errors are logged via slog and a generic message returned
//     to the client (writeInternalErr). Never echo err.Error() to clients.
//   - approveProposal wraps the entire flow in a single transaction with
//     SELECT ... FOR UPDATE on the proposal row to prevent double-apply
//     races (audit fix #23).
//   - Reject body is bounded by http.MaxBytesReader (audit fix #24).
//   - Query params are allowlisted to prevent probing (audit fix #25).

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/kaixuan/llm-gateway-go/autoroute"
)

// validStatuses and validCategories are allowlists for the proposals
// endpoint query filters. Prevents attackers from probing for arbitrary
// internal values.
var (
	validStatuses   = map[string]bool{"": true, "pending": true, "approved": true, "rejected": true, "applied": true}
	validCategories = map[string]bool{"": true, "keyword_add": true, "weight_adjust": true, "threshold_change": true}
)

// maxRejectBodyBytes caps the body size for the reject endpoint. Generous
// for a rejection reason but tight enough to prevent OOM.
const maxRejectBodyBytes = 64 * 1024

// TuningHandlers serves the Phase 5 tuning feedback endpoints.
// It wraps AutoRouteHandlers to share the DB pool and (optionally)
// the TuningStore for instant-apply after approval.
type TuningHandlers struct {
	parent *AutoRouteHandlers

	analyzer interface {
		AnalyzeOnce(ctx context.Context) error
	}
}

// NewTuningHandlers constructs the handler set. parent provides the DB pool.
func NewTuningHandlers(parent *AutoRouteHandlers) *TuningHandlers {
	return &TuningHandlers{parent: parent}
}

// SetAnalyzer wires the feedback analyzer (for on-demand runs).
func (h *TuningHandlers) SetAnalyzer(a interface {
	AnalyzeOnce(ctx context.Context) error
}) {
	h.analyzer = a
}

// RegisterTuningRoutes mounts the 4 endpoints onto the admin mux.
func (h *TuningHandlers) RegisterTuningRoutes(mux *http.ServeMux, adminWrap func(http.HandlerFunc) http.HandlerFunc) {
	mux.HandleFunc("/api/admin/auto-route/tuning/proposals", adminWrap(h.handleProposals))
	mux.HandleFunc("/api/admin/auto-route/tuning/proposals/", adminWrap(h.handleProposalAction))
	mux.HandleFunc("/api/admin/auto-route/tuning/accuracy", adminWrap(h.handleAccuracy))
}

// handleProposals: GET /tuning/proposals?status=pending&category=keyword_add&limit=50
func (h *TuningHandlers) handleProposals(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		writeJSONErr(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}

	status := r.URL.Query().Get("status")
	if !validStatuses[status] {
		writeJSONErr(w, http.StatusBadRequest, "invalid status filter")
		return
	}
	category := r.URL.Query().Get("category")
	if !validCategories[category] {
		writeJSONErr(w, http.StatusBadRequest, "invalid category filter")
		return
	}
	limit := 50
	if l := r.URL.Query().Get("limit"); l != "" {
		v, err := strconv.Atoi(l)
		if err != nil || v <= 0 || v > 500 {
			writeJSONErr(w, http.StatusBadRequest, "limit must be 1-500")
			return
		}
		limit = v
	}

	query := `
		SELECT id, ts, category, task_type, proposal, evidence, status,
		       reviewed_by, reviewed_at, applied_at, review_note
		FROM tuning_proposals
		WHERE ($1 = '' OR status = $1)
		  AND ($2 = '' OR category = $2)
		ORDER BY ts DESC
		LIMIT $3
	`
	rows, err := h.parent.db.Query(r.Context(), query, status, category, limit)
	if err != nil {
		writeInternalErr(w, err)
		return
	}
	defer rows.Close()

	type proposalRow struct {
		ID         int64           `json:"id"`
		Ts         time.Time       `json:"ts"`
		Category   string          `json:"category"`
		TaskType   *string         `json:"task_type"`
		Proposal   json.RawMessage `json:"proposal"`
		Evidence   json.RawMessage `json:"evidence"`
		Status     string          `json:"status"`
		ReviewedBy *string         `json:"reviewed_by"`
		ReviewedAt *time.Time      `json:"reviewed_at"`
		AppliedAt  *time.Time      `json:"applied_at"`
		ReviewNote *string         `json:"review_note"`
	}

	var results []proposalRow
	for rows.Next() {
		var row proposalRow
		if err := rows.Scan(&row.ID, &row.Ts, &row.Category, &row.TaskType,
			&row.Proposal, &row.Evidence, &row.Status,
			&row.ReviewedBy, &row.ReviewedAt, &row.AppliedAt, &row.ReviewNote); err != nil {
			writeInternalErr(w, err)
			return
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		writeInternalErr(w, err)
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"proposals": results,
		"count":     len(results),
		"filter":    map[string]string{"status": status, "category": category},
	})
}

// handleProposalAction: POST /tuning/proposals/:id/{approve|reject}
func (h *TuningHandlers) handleProposalAction(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		writeJSONErr(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}

	// Parse path: /api/admin/auto-route/tuning/proposals/:id/:action
	path := strings.TrimPrefix(r.URL.Path, "/api/admin/auto-route/tuning/proposals/")
	parts := strings.Split(path, "/")
	if len(parts) != 2 {
		writeJSONErr(w, http.StatusBadRequest, "expected /tuning/proposals/:id/{approve|reject}")
		return
	}

	id, err := strconv.ParseInt(parts[0], 10, 64)
	if err != nil {
		writeJSONErr(w, http.StatusBadRequest, "invalid proposal id")
		return
	}

	action := parts[1]
	switch action {
	case "approve":
		h.approveProposal(w, r, id)
	case "reject":
		h.rejectProposal(w, r, id)
	default:
		// Static message — never echo the user-supplied action value.
		writeJSONErr(w, http.StatusBadRequest, "unknown action (expected approve or reject)")
	}
}

// approveProposal transitions a proposal to 'applied' and writes the
// change to tuning_params. The entire flow is atomic: SELECT FOR UPDATE
// on the proposal row, apply params, update status — all in one tx.
// This prevents double-apply if the second call wins a race.
func (h *TuningHandlers) approveProposal(w http.ResponseWriter, r *http.Request, id int64) {
	ctx := r.Context()

	// Single transaction: locks the proposal row, applies params, updates status.
	tx, err := h.parent.db.Begin(ctx)
	if err != nil {
		writeInternalErr(w, err)
		return
	}
	defer tx.Rollback(ctx) // safe no-op if Commit succeeds

	// Lock the proposal row + fetch its current state.
	var category string
	var taskType *string
	var proposalJSON, evidenceJSON []byte
	var status string
	err = tx.QueryRow(ctx, `
		SELECT category, task_type, proposal, evidence, status
		FROM tuning_proposals
		WHERE id = $1
		FOR UPDATE
	`, id).Scan(&category, &taskType, &proposalJSON, &evidenceJSON, &status)
	if err == pgx.ErrNoRows {
		writeJSONErr(w, http.StatusNotFound, "proposal not found")
		return
	}
	if err != nil {
		writeInternalErr(w, err)
		return
	}

	// Reject if not pending (within the locked tx — no race possible).
	if status != "pending" {
		writeJSONErr(w, http.StatusConflict, "proposal is not in pending status")
		return
	}

	// Parse + apply the proposal to tuning_params, all within the same tx.
	var proposal map[string]any
	if err := json.Unmarshal(proposalJSON, &proposal); err != nil {
		writeJSONErr(w, http.StatusInternalServerError, "invalid proposal JSON")
		return
	}

	if err := applyProposalInTx(ctx, tx, category, proposal); err != nil {
		writeInternalErr(w, err)
		return
	}

	// Mark as applied (still inside the same tx).
	_, err = tx.Exec(ctx, `
		UPDATE tuning_proposals
		SET status = 'applied', applied_at = NOW(), updated_at = NOW()
		WHERE id = $1
	`, id)
	if err != nil {
		writeInternalErr(w, err)
		return
	}

	// Atomic commit — either everything succeeds or everything rolls back.
	if err := tx.Commit(ctx); err != nil {
		writeInternalErr(w, err)
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"id":      id,
		"status":  "applied",
		"message": "proposal applied to tuning_params (takes effect within 5 min)",
	})
}

// rejectProposal transitions a proposal to 'rejected' with an optional note.
// Body is bounded by maxRejectBodyBytes to prevent memory abuse.
func (h *TuningHandlers) rejectProposal(w http.ResponseWriter, r *http.Request, id int64) {
	note := r.URL.Query().Get("reason")
	if note == "" && r.Body != nil {
		// Bound the body size to prevent OOM.
		r.Body = http.MaxBytesReader(w, r.Body, maxRejectBodyBytes)
		var body struct {
			Reason string `json:"reason"`
		}
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			// If body is malformed or too large, treat as no note (still
			// reject the proposal without a reason rather than failing).
			slog.Warn("tuning: reject body decode failed", "proposal_id", id, "error", err)
		} else {
			note = body.Reason
		}
	}

	// Cap the note length to prevent DB bloat.
	if len(note) > 1024 {
		note = note[:1024]
	}

	_, err := h.parent.db.Exec(r.Context(), `
		UPDATE tuning_proposals
		SET status = 'rejected', review_note = $2, reviewed_at = NOW(), updated_at = NOW()
		WHERE id = $1 AND status = 'pending'
	`, id, note)
	if err != nil {
		writeInternalErr(w, err)
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"id":     id,
		"status": "rejected",
		"note":   note,
	})
}

// applyProposalInTx dispatches a proposal application within an existing
// transaction. The transaction (tx) is owned by the caller (approveProposal).
func applyProposalInTx(ctx context.Context, tx pgx.Tx, category string, proposal map[string]any) error {
	switch category {
	case "keyword_add":
		return applyKeywordAddInTx(ctx, tx, proposal)
	case "weight_adjust":
		return applyWeightAdjustInTx(ctx, tx, proposal)
	default:
		return fmt.Errorf("unknown proposal category: %s", category)
	}
}

// applyKeywordAddInTx merges new keywords into the existing tuning_params row
// within the caller's transaction. Uses SELECT FOR UPDATE for row-level
// concurrency safety.
func applyKeywordAddInTx(ctx context.Context, tx pgx.Tx, proposal map[string]any) error {
	key, _ := proposal["key"].(string)
	addRaw, _ := proposal["add"].([]any)
	if key == "" || len(addRaw) == 0 {
		return fmt.Errorf("keyword_add proposal missing key or add fields")
	}

	addStrs := make([]string, 0, len(addRaw))
	for _, a := range addRaw {
		if s, ok := a.(string); ok && s != "" {
			addStrs = append(addStrs, s)
		}
	}
	if len(addStrs) == 0 {
		return fmt.Errorf("keyword_add proposal has no string keywords")
	}

	var currentValue []byte
	err := tx.QueryRow(ctx,
		`SELECT value FROM tuning_params WHERE key = $1 FOR UPDATE`, key,
	).Scan(&currentValue)
	if err != nil {
		return fmt.Errorf("read current keywords: %w", err)
	}

	var existing []string
	if err := json.Unmarshal(currentValue, &existing); err != nil {
		existing = []string{}
	}

	// Merge (deduplicate)
	existingSet := make(map[string]bool, len(existing))
	for _, k := range existing {
		existingSet[k] = true
	}
	for _, k := range addStrs {
		if !existingSet[k] {
			existing = append(existing, k)
			existingSet[k] = true
		}
	}

	mergedJSON, _ := json.Marshal(existing)
	_, err = tx.Exec(ctx, `
		UPDATE tuning_params
		SET value = $2, source = 'feedback', updated_at = NOW(), applied_at = NOW()
		WHERE key = $1
	`, key, mergedJSON)
	if err != nil {
		return fmt.Errorf("update keywords: %w", err)
	}
	return nil
}

// applyWeightAdjustInTx updates a single dimension of a profile weight matrix.
func applyWeightAdjustInTx(ctx context.Context, tx pgx.Tx, proposal map[string]any) error {
	key, _ := proposal["key"].(string)
	dimension, _ := proposal["dimension"].(string)
	newVal, _ := proposal["new"].(float64)
	if key == "" || dimension == "" {
		return fmt.Errorf("weight_adjust proposal missing key or dimension")
	}

	// Whitelist dimension names to prevent arbitrary column writes.
	allowedDimensions := map[string]bool{
		"price": true, "speed": true, "stability": true,
		"match": true, "pressure": true, "context_fit": true,
	}
	if !allowedDimensions[dimension] {
		return fmt.Errorf("unknown weight dimension: %s", dimension)
	}

	var currentValue []byte
	err := tx.QueryRow(ctx,
		`SELECT value FROM tuning_params WHERE key = $1 FOR UPDATE`, key,
	).Scan(&currentValue)
	if err != nil {
		return fmt.Errorf("read current weights: %w", err)
	}

	var weights map[string]float64
	if err := json.Unmarshal(currentValue, &weights); err != nil {
		return fmt.Errorf("parse current weights: %w", err)
	}
	weights[dimension] = newVal

	mergedJSON, _ := json.Marshal(weights)
	_, err = tx.Exec(ctx, `
		UPDATE tuning_params
		SET value = $2, source = 'feedback', updated_at = NOW(), applied_at = NOW()
		WHERE key = $1
	`, key, mergedJSON)
	if err != nil {
		return fmt.Errorf("update weights: %w", err)
	}
	return nil
}

// handleAccuracy: GET /tuning/accuracy?days=7
// Returns a 7-day accuracy dashboard grouped by task_type and classifier.
func (h *TuningHandlers) handleAccuracy(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		writeJSONErr(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}

	days := 7
	if d := r.URL.Query().Get("days"); d != "" {
		v, err := strconv.Atoi(d)
		if err != nil || v <= 0 || v > 90 {
			writeJSONErr(w, http.StatusBadRequest, "days must be 1-90")
			return
		}
		days = v
	}

	// P7.5: pick the appropriate materialised view based on the
	// window size.
	//   days <= 7   → tuning_signals_5m (5-minute buckets, ~3ms)
	//   days 8..90  → tuning_signals_daily (1-day buckets, ~5ms)
	// Falls back to the source table if the view is missing
	// (e.g. fresh deploy where the matview hasn't been created
	// yet). The view ensure runs in ensureTuningSignalsViews on
	// startup, so this fallback is theoretical.
	viewName := "tuning_signals_daily"
	if days <= 7 {
		viewName = "tuning_signals_5m"
	}
	query := `
		SELECT
		    task_type,
		    classifier,
		    SUM(total)::int AS total,
		    SUM(avg_quality * total) / NULLIF(SUM(total), 0) AS avg_quality,
		    SUM(avg_success * total) / NULLIF(SUM(total), 0) AS avg_success,
		    SUM(avg_latency * total) / NULLIF(SUM(total), 0) AS avg_latency,
		    SUM(avg_cost * total) / NULLIF(SUM(total), 0) AS avg_cost,
		    SUM(drift_rate * total) / NULLIF(SUM(total), 0) AS drift_rate
		FROM ` + viewName + `
		WHERE bucket >= NOW() - INTERVAL '1 day' * $1
		GROUP BY task_type, classifier
		ORDER BY task_type, classifier
	`
	rows, err := h.parent.db.Query(r.Context(), query, days)
	if err != nil {
		writeInternalErr(w, err)
		return
	}
	defer rows.Close()

	type accuracyRow struct {
		TaskType   string  `json:"task_type"`
		Classifier string  `json:"classifier"`
		Total      int     `json:"total"`
		AvgQuality float64 `json:"avg_quality"`
		AvgSuccess float64 `json:"avg_success"`
		AvgLatency float64 `json:"avg_latency"`
		AvgCost    float64 `json:"avg_cost"`
		DriftRate  float64 `json:"drift_rate"`
	}

	var results []accuracyRow
	for rows.Next() {
		var row accuracyRow
		if err := rows.Scan(&row.TaskType, &row.Classifier, &row.Total,
			&row.AvgQuality, &row.AvgSuccess, &row.AvgLatency, &row.AvgCost,
			&row.DriftRate); err != nil {
			writeInternalErr(w, err)
			return
		}
		results = append(results, row)
	}
	if err := rows.Err(); err != nil {
		writeInternalErr(w, err)
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"window_days":  days,
		"breakdown":    results,
		"generated_at": time.Now().UTC(),
	})
}


// handleStrategies: GET /tuning/strategies?days=7
//
// Returns a per-strategy A/B comparison breakdown:
//   - Total signal count per strategy
//   - Avg quality, success, latency, cost, drift rate per strategy
//   - Per-(strategy, task_type) breakdown
//
// Strategy values come from the Strategy field on each
// tuning_signals row (set by emitTuningSignal via
// autoroute.AssignStrategy). When A/B is disabled, the
// AssignStrategy helper always returns pattern_layered, so all
// rows have the same strategy label.
func (h *TuningHandlers) handleStrategies(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		writeJSONErr(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}

	days := 7
	if d := r.URL.Query().Get("days"); d != "" {
		v, err := strconv.Atoi(d)
		if err != nil || v <= 0 || v > 90 {
			writeJSONErr(w, http.StatusBadRequest, "days must be 1-90")
			return
		}
		days = v
	}

	// Summary: one row per strategy.
	// Reads the dedicated `strategy` column (P7.1) for index-friendly
	// queries. The COALESCE fallback handles a 0-row window gracefully.
	summaryQuery := `
		SELECT
		    strategy,
		    COUNT(*) AS total,
		    AVG(quality_score) AS avg_quality,
		    AVG(success_score) AS avg_success,
		    AVG(latency_score) AS avg_latency,
		    AVG(cost_score) AS avg_cost,
		    SUM(CASE WHEN drift_flag THEN 1 ELSE 0 END)::float / COUNT(*) AS drift_rate
		FROM tuning_signals
		WHERE ts >= NOW() - INTERVAL '1 day' * $1
		GROUP BY strategy
		ORDER BY strategy
	`
	rows, err := h.parent.db.Query(r.Context(), summaryQuery, days)
	if err != nil {
		writeInternalErr(w, err)
		return
	}
	defer rows.Close()

	type strategyRow struct {
		Strategy   string  `json:"strategy"`
		Total      int     `json:"total"`
		AvgQuality float64 `json:"avg_quality"`
		AvgSuccess float64 `json:"avg_success"`
		AvgLatency float64 `json:"avg_latency"`
		AvgCost    float64 `json:"avg_cost"`
		DriftRate  float64 `json:"drift_rate"`
	}

	var summary []strategyRow
	for rows.Next() {
		var row strategyRow
		if err := rows.Scan(&row.Strategy, &row.Total, &row.AvgQuality,
			&row.AvgSuccess, &row.AvgLatency, &row.AvgCost, &row.DriftRate); err != nil {
			writeInternalErr(w, err)
			return
		}
		summary = append(summary, row)
	}
	if err := rows.Err(); err != nil {
		writeInternalErr(w, err)
		return
	}

	// Per-task-type breakdown per strategy. Uses the strategy
	// column directly (with COALESCE for rows that pre-date P7.1
	// and might still be null — those default to pattern_layered).
	breakdownQuery := `
		SELECT
		    COALESCE(strategy, 'pattern_layered') AS strategy,
		    task_type,
		    COUNT(*) AS total,
		    AVG(quality_score) AS avg_quality,
		    AVG(success_score) AS avg_success
		FROM tuning_signals
		WHERE ts >= NOW() - INTERVAL '1 day' * $1
		GROUP BY strategy, task_type
		ORDER BY strategy, task_type
	`
	rows2, err := h.parent.db.Query(r.Context(), breakdownQuery, days)
	if err != nil {
		writeInternalErr(w, err)
		return
	}
	defer rows2.Close()

	type breakdownRow struct {
		Strategy   string  `json:"strategy"`
		TaskType   string  `json:"task_type"`
		Total      int     `json:"total"`
		AvgQuality float64 `json:"avg_quality"`
		AvgSuccess float64 `json:"avg_success"`
	}
	var breakdown []breakdownRow
	for rows2.Next() {
		var row breakdownRow
		if err := rows2.Scan(&row.Strategy, &row.TaskType, &row.Total,
			&row.AvgQuality, &row.AvgSuccess); err != nil {
			writeInternalErr(w, err)
			return
		}
		breakdown = append(breakdown, row)
	}
	if err := rows2.Err(); err != nil {
		writeInternalErr(w, err)
		return
	}

	// A/B verdict: which strategy wins on avg quality (if both present)
	var verdict string
	if len(summary) >= 2 {
		var baselineQ, patternQ float64
		var baselineN, patternN int
		for _, s := range summary {
			if s.Strategy == "baseline_heuristic" {
				baselineQ, baselineN = s.AvgQuality, s.Total
			}
			if s.Strategy == "pattern_layered" {
				patternQ, patternN = s.AvgQuality, s.Total
			}
		}
		switch {
		case baselineN < 30 || patternN < 30:
			verdict = "insufficient_samples"
		case patternQ > baselineQ+0.02:
			verdict = "pattern_layered_wins"
		case baselineQ > patternQ+0.02:
			verdict = "baseline_heuristic_wins"
		default:
			verdict = "no_significant_difference"
		}
	} else {
		verdict = "ab_test_disabled"
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"window_days":   days,
		"summary":       summary,
		"breakdown":     breakdown,
		"ab_verdict":    verdict,
		"ab_enabled":    autoroute.IsABTestEnabled(),
		"ab_baseline_pct": autoroute.BaselinePctPublic(),
		"generated_at":  time.Now().UTC(),
	})
}
