package admin

import (
	"strings"
	"testing"
	"time"
)

// TestF4ContractFields_SQLShape verifies that the F-4 audit fields
// (http_status, sticky, outbound_model, detail) are present in the SQL
// generated by buildRoutingLogSQL for all three branches.
func TestF4ContractFields_SQLShape(t *testing.T) {
	query, _ := buildRoutingLogSQL(routingLogParams{
		Kind:      "all",
		Result:    "all",
		TimeStart: time.Now().Add(-time.Hour),
		TimeEnd:   time.Now(),
		Limit:     10,
	})

	// All branches must have 21 columns (17 original + 4 F-4 fields)
	// to match the updated RoutingLogEntry struct

	// Routing branch: must include sticky_hit, outbound_model, and detail
	routingBranch := extractBranch(query, "FROM routing_decision_log")
	if !strings.Contains(routingBranch, "rdl.sticky_hit AS sticky") {
		t.Error("routing branch missing: rdl.sticky_hit AS sticky")
	}
	if !strings.Contains(routingBranch, "rdl.outbound_model") {
		t.Error("routing branch missing: rdl.outbound_model")
	}
	if !strings.Contains(routingBranch, "rdl.failure_stage") {
		t.Error("routing branch missing: rdl.failure_stage (for detail)")
	}
	if !strings.Contains(routingBranch, "NULL::int AS http_status") {
		t.Error("routing branch missing: NULL::int AS http_status")
	}

	// Probe branch: must include http_status and detail
	probeBranch := extractBranch(query, "FROM model_probe_runs_with_current_month")
	if !strings.Contains(probeBranch, "mpr.http_status") {
		t.Error("probe branch missing: mpr.http_status")
	}
	if !strings.Contains(probeBranch, "NULL::boolean AS sticky") {
		t.Error("probe branch missing: NULL::boolean AS sticky")
	}
	if !strings.Contains(probeBranch, "NULL::text AS outbound_model") {
		t.Error("probe branch missing: NULL::text AS outbound_model")
	}
	if !strings.Contains(probeBranch, "AS detail") {
		t.Error("probe branch missing: detail column")
	}

	// Audit branch: all F-4 fields must be NULL placeholders
	auditBranch := extractBranch(query, "FROM routing_audit_log")
	requiredNulls := []string{
		"NULL::int AS http_status",
		"NULL::boolean AS sticky",
		"NULL::text AS outbound_model",
	}
	for _, want := range requiredNulls {
		if !strings.Contains(auditBranch, want) {
			t.Errorf("audit branch missing: %s", want)
		}
	}
	if !strings.Contains(auditBranch, "AS detail") {
		t.Error("audit branch missing: detail column")
	}
}

// extractBranch returns the SQL fragment containing a specific FROM clause.
func extractBranch(query, fromClause string) string {
	idx := strings.Index(query, fromClause)
	if idx == -1 {
		return ""
	}
	// Return 500 chars before and after the FROM clause for context
	start := idx - 500
	if start < 0 {
		start = 0
	}
	end := idx + 500
	if end > len(query) {
		end = len(query)
	}
	return query[start:end]
}
