package admin

import (
	"context"
	"encoding/json"
	"log/slog"
	"net/http"
	"strconv"
	"strings"
	"time"
)

// handleModelNameMapping handles model name mapping CRUD operations
// Path: /api/models/name-mapping
func (h *Handler) handleModelNameMapping(w http.ResponseWriter, r *http.Request) {
	if h.db == nil {
		writeError(w, http.StatusServiceUnavailable, "database not configured")
		return
	}

	remaining := r.URL.Path[len("/api/models/name-mapping"):]

	// Block write operations for tenant_admin
	if RequireSuperAdminForWrite(w, r) {
		return
	}

	if remaining == "" {
		switch r.Method {
		case http.MethodGet:
			h.listModelNameMappings(w, r)
		case http.MethodPost:
			h.createModelNameMapping(w, r)
		default:
			writeError(w, http.StatusMethodNotAllowed, "method not allowed")
		}
		return
	}

	// Handle /api/models/name-mapping/sync endpoint
	if remaining == "/sync" && r.Method == http.MethodPost {
		h.syncModelNameMappings(w, r)
		return
	}

	idStr := remaining
	subPath := ""
	for i, c := range remaining {
		if c == '/' {
			idStr = remaining[:i]
			subPath = remaining[i+1:]
			break
		}
	}
	_ = subPath // subPath reserved for future sub-resource handling

	id, err := strconv.Atoi(idStr)
	if err != nil {
		http.NotFound(w, r)
		return
	}

	switch r.Method {
	case http.MethodGet:
		h.getModelNameMapping(w, r, id)
	case http.MethodPut, http.MethodPatch:
		h.updateModelNameMapping(w, r, id)
	case http.MethodDelete:
		h.deleteModelNameMapping(w, r, id)
	default:
		writeError(w, http.StatusMethodNotAllowed, "method not allowed")
	}
}

type modelNameMappingRow struct {
	ID               int       `json:"id"`
	RawModelName     string    `json:"raw_model_name"`
	StandardizedName string    `json:"standardized_name"`
	Description      string    `json:"description,omitempty"`
	AutoGenerated    bool      `json:"auto_generated"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	CreatedBy       string    `json:"created_by,omitempty"`
}

type modelNameMappingListResponse struct {
	Items      []modelNameMappingRow `json:"items"`
	Total      int                  `json:"total"`
	Page       int                  `json:"page"`
	PageSize   int                  `json:"page_size"`
	PageCount  int                  `json:"page_count"`
}

// listModelNameMappings returns paginated list of model name mappings
func (h *Handler) listModelNameMappings(w http.ResponseWriter, r *http.Request) {
	page := queryInt(r, "page", 1)
	pageSize := queryInt(r, "page_size", 50)
	search := queryString(r, "search")

	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 200 {
		pageSize = 50
	}
	offset := (page - 1) * pageSize

	ctx, cancel := context.WithTimeout(r.Context(), 10*time.Second)
	defer cancel()

	// Count query
	countQuery := `SELECT COUNT(*) FROM public.model_name_mapping WHERE 1=1`
	countArgs := []any{}

	if search != "" {
		countQuery += ` AND (raw_model_name ILIKE $1 OR standardized_name ILIKE $1)`
		countArgs = append(countArgs, "%"+search+"%")
	}

	var total int
	err := h.db.QueryRow(ctx, countQuery, countArgs...).Scan(&total)
	if err != nil {
		slog.Warn("model_name_mapping count failed", "error", err)
		writeJSON(w, http.StatusOK, map[string]any{"items": []any{}, "total": 0, "error": err.Error()})
		return
	}

	// List query
	listQuery := `
		SELECT id, raw_model_name, standardized_name, 
		       COALESCE(description, '') as description,
		       COALESCE(auto_generated, FALSE) as auto_generated,
		       created_at, updated_at,
		       COALESCE(created_by, '') as created_by
		FROM public.model_name_mapping WHERE 1=1`
	listArgs := []any{}
	listArgIdx := 1

	if search != "" {
		listQuery += ` AND (raw_model_name ILIKE $` + strconv.Itoa(listArgIdx) + ` OR standardized_name ILIKE $` + strconv.Itoa(listArgIdx) + `)`
		listArgs = append(listArgs, "%"+search+"%")
		listArgIdx++
	}

	listQuery += ` ORDER BY updated_at DESC LIMIT $` + strconv.Itoa(listArgIdx) + ` OFFSET $` + strconv.Itoa(listArgIdx+1)
	listArgs = append(listArgs, pageSize, offset)

	rows, err := h.db.Query(ctx, listQuery, listArgs...)
	if err != nil {
		slog.Warn("model_name_mapping list failed", "error", err)
		writeJSON(w, http.StatusOK, map[string]any{"items": []any{}, "total": total, "error": err.Error()})
		return
	}
	defer rows.Close()

	items := make([]modelNameMappingRow, 0)
	for rows.Next() {
		var item modelNameMappingRow
		if err := rows.Scan(
			&item.ID, &item.RawModelName, &item.StandardizedName,
			&item.Description, &item.AutoGenerated,
			&item.CreatedAt, &item.UpdatedAt, &item.CreatedBy,
		); err != nil {
			continue
		}
		items = append(items, item)
	}

	pageCount := (total + pageSize - 1) / pageSize
	if pageCount < 1 {
		pageCount = 1
	}

	writeJSON(w, http.StatusOK, modelNameMappingListResponse{
		Items:     items,
		Total:     total,
		Page:      page,
		PageSize:  pageSize,
		PageCount: pageCount,
	})
}

type createModelNameMappingRequest struct {
	RawModelName     string `json:"raw_model_name"`
	StandardizedName string `json:"standardized_name"`
	Description      string `json:"description,omitempty"`
}

// createModelNameMapping creates a new model name mapping
func (h *Handler) createModelNameMapping(w http.ResponseWriter, r *http.Request) {
	var req createModelNameMappingRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON in request body")
		return
	}

	req.RawModelName = strings.TrimSpace(req.RawModelName)
	req.StandardizedName = strings.TrimSpace(req.StandardizedName)

	if req.RawModelName == "" || req.StandardizedName == "" {
		writeError(w, http.StatusBadRequest, "raw_model_name and standardized_name are required")
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 10*time.Second)
	defer cancel()

	var id int
	err := h.db.QueryRow(ctx, `
		INSERT INTO public.model_name_mapping (raw_model_name, standardized_name, description, auto_generated, created_by)
		VALUES ($1, $2, $3, FALSE, $4)
		ON CONFLICT (raw_model_name) DO UPDATE 
			SET standardized_name = EXCLUDED.standardized_name,
			    description = EXCLUDED.description,
			    auto_generated = FALSE,
			    updated_at = now()
		RETURNING id
	`, req.RawModelName, req.StandardizedName, req.Description, getUsername(r)).Scan(&id)
	if err != nil {
		slog.Warn("create model_name_mapping failed", "error", err)
		writeError(w, http.StatusInternalServerError, "insert failed")
		return
	}

	writeJSON(w, http.StatusCreated, map[string]any{"id": id, "message": "created"})
}

// getModelNameMapping returns a single model name mapping
func (h *Handler) getModelNameMapping(w http.ResponseWriter, r *http.Request, id int) {
	ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
	defer cancel()

	var item modelNameMappingRow
	err := h.db.QueryRow(ctx, `
		SELECT id, raw_model_name, standardized_name,
		       COALESCE(description, '') as description,
		       COALESCE(auto_generated, FALSE) as auto_generated,
		       created_at, updated_at,
		       COALESCE(created_by, '') as created_by
		FROM public.model_name_mapping WHERE id = $1
	`, id).Scan(
		&item.ID, &item.RawModelName, &item.StandardizedName,
		&item.Description, &item.AutoGenerated,
		&item.CreatedAt, &item.UpdatedAt, &item.CreatedBy,
	)
	if err != nil {
		writeError(w, http.StatusNotFound, "not found")
		return
	}

	writeJSON(w, http.StatusOK, item)
}

type updateModelNameMappingRequest struct {
	RawModelName     *string `json:"raw_model_name,omitempty"`
	StandardizedName *string `json:"standardized_name,omitempty"`
	Description      *string `json:"description,omitempty"`
}

// updateModelNameMapping updates an existing model name mapping
func (h *Handler) updateModelNameMapping(w http.ResponseWriter, r *http.Request, id int) {
	var req updateModelNameMappingRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON in request body")
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 10*time.Second)
	defer cancel()

	// Build dynamic update query
	setClauses := []string{}
	args := []any{}
	argIdx := 1

	if req.RawModelName != nil {
		setClauses = append(setClauses, "raw_model_name = $"+strconv.Itoa(argIdx))
		args = append(args, *req.RawModelName)
		argIdx++
	}
	if req.StandardizedName != nil {
		setClauses = append(setClauses, "standardized_name = $"+strconv.Itoa(argIdx))
		args = append(args, *req.StandardizedName)
		argIdx++
	}
	if req.Description != nil {
		setClauses = append(setClauses, "description = $"+strconv.Itoa(argIdx))
		args = append(args, *req.Description)
		argIdx++
	}

	if len(setClauses) == 0 {
		writeError(w, http.StatusBadRequest, "nothing to update")
		return
	}

	// If raw_model_name changed, we need to update unique constraint
	// Since we use raw_model_name as the unique key, we need to delete and re-insert
	if req.RawModelName != nil {
		// Get current mapping
		var currentRaw, currentStd, currentDesc string
		err := h.db.QueryRow(ctx, "SELECT raw_model_name, standardized_name, COALESCE(description,'') FROM model_name_mapping WHERE id = $1", id).Scan(&currentRaw, &currentStd, &currentDesc)
		if err != nil {
			writeError(w, http.StatusNotFound, "not found")
			return
		}

		newRaw := *req.RawModelName
		if req.StandardizedName != nil {
			newRaw = *req.StandardizedName
		}

		// Delete old and insert new
		_, err = h.db.Exec(ctx, "DELETE FROM model_name_mapping WHERE id = $1", id)
		if err != nil {
			writeError(w, http.StatusInternalServerError, "delete failed")
			return
		}

		var newID int
		err = h.db.QueryRow(ctx, `
			INSERT INTO model_name_mapping (raw_model_name, standardized_name, description, auto_generated, created_by)
			VALUES ($1, $2, $3, FALSE, $4)
			ON CONFLICT (raw_model_name) DO NOTHING
			RETURNING id
		`, newRaw, currentStd, currentDesc, getUsername(r)).Scan(&newID)
		if err != nil {
			writeError(w, http.StatusInternalServerError, "insert failed")
			return
		}
		if newID == 0 {
			writeError(w, http.StatusConflict, "raw_model_name already exists")
			return
		}

		writeJSON(w, http.StatusOK, map[string]any{"id": newID, "message": "updated"})
		return
	}

	setClauses = append(setClauses, "updated_at = now()")
	args = append(args, id)

	query := "UPDATE model_name_mapping SET " + joinStrings(setClauses, ", ") + " WHERE id = $" + strconv.Itoa(argIdx)
	_, updateErr := h.db.Exec(ctx, query, args...)
	if updateErr != nil {
		slog.Warn("update model_name_mapping failed", "error", updateErr)
		writeError(w, http.StatusInternalServerError, "update failed")
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{"message": "updated"})
}

// deleteModelNameMapping deletes a model name mapping
func (h *Handler) deleteModelNameMapping(w http.ResponseWriter, r *http.Request, id int) {
	ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
	defer cancel()

	// Check if auto-generated (only allow deletion of manual entries)
	var autoGenerated bool
	err := h.db.QueryRow(ctx, "SELECT COALESCE(auto_generated, FALSE) FROM model_name_mapping WHERE id = $1", id).Scan(&autoGenerated)
	if err != nil {
		writeError(w, http.StatusNotFound, "not found")
		return
	}

	if autoGenerated {
		writeError(w, http.StatusForbidden, "cannot delete auto-generated mapping")
		return
	}

	result, err := h.db.Exec(ctx, "DELETE FROM model_name_mapping WHERE id = $1", id)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "delete failed")
		return
	}

	if result.RowsAffected() == 0 {
		writeError(w, http.StatusNotFound, "not found")
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{"message": "deleted"})
}

// syncModelNameMappings syncs mappings from provider_models.standardized_name
func (h *Handler) syncModelNameMappings(w http.ResponseWriter, r *http.Request) {
	ctx, cancel := context.WithTimeout(r.Context(), 30*time.Second)
	defer cancel()

	// Sync from provider_models where standardized_name is set
	tag1, err := h.db.Exec(ctx, `
		INSERT INTO public.model_name_mapping (raw_model_name, standardized_name, auto_generated, description)
		SELECT DISTINCT pm.raw_model_name, pm.standardized_name, TRUE, 'Auto-synced from provider_models.standardized_name'
		FROM public.provider_models pm
		WHERE pm.standardized_name IS NOT NULL 
		  AND pm.standardized_name != ''
		  AND pm.standardized_name != pm.raw_model_name
		ON CONFLICT (raw_model_name) DO UPDATE 
		    SET standardized_name = EXCLUDED.standardized_name,
		        updated_at = now(),
		        auto_generated = TRUE
	`)
	if err != nil {
		slog.Warn("sync model_name_mapping from provider_models failed", "error", err)
		writeError(w, http.StatusInternalServerError, "sync failed")
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"message":          "synced",
		"provider_models":  tag1.RowsAffected(),
	})
}

// joinStrings joins strings with a separator (simple utility)
func joinStrings(strs []string, sep string) string {
	if len(strs) == 0 {
		return ""
	}
	result := strs[0]
	for i := 1; i < len(strs); i++ {
		result += sep + strs[i]
	}
	return result
}
