package compression

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"time"
)

// hashTenantForSanitizeKey mirrors security/sanitize.HashTenant. It is
// duplicated here because security/sanitize imports compression (via
// SanitizeStats), so compression cannot import it back without a cycle.
// The cross-layer consistency is pinned by TestSessionSanitizeRedisKeyMatches
// in security/sanitize, which exercises both builders with identical inputs.
//
// T11-P0 v2 fix: the cascade delete in SessionCache.Invalidate previously
// passed the raw tenantID into SessionSanitizeRedisKey, whose parameter is
// the tenantHash. The write side (smart_sani_guard.go) hashes first, so the
// keys never matched and the deletes were silent no-ops — leaking stale
// sanitize maps/offsets until TTL expiry. Mirror HashTenant here so Invalidate
// can derive the same hash as the writer.
func hashTenantForSanitizeKey(tenantID string) string {
	if tenantID == "" {
		tenantID = "_unknown"
	}
	sum := sha256.Sum256([]byte(tenantID))
	return hex.EncodeToString(sum[:8])
}

// SanitizeInfo is the per-request bridge between the HTTP sanitize
// middleware (security/sanitize) and the three-tier session cache (SC-1,
// docs/修订0811/19). The middleware stashes it in the request context after
// replacing sensitive values with placeholders; the session compressor
// persists it into SessionState so the v8 L3 fields (SanitizeMapRef /
// SanitizeStats) stop being write-orphaned.
//
// Defined here (not in security/sanitize) because that package already
// imports compression for SanitizeStats — the context plumbing must live on
// the compression side to keep the dependency one-directional.
type SanitizeInfo struct {
	RawSnapshot       MessageSnapshot
	SanitizedSnapshot MessageSnapshot
	MapGeneration     string
	// MapRef is the Redis key holding the placeholder→plaintext map for the
	// session ("session:{tenantHash}:{id}:sanitize"). Empty when this
	// request has no persistent dictionary (for example, Redis is disabled).
	MapRef string
	// Stats summarizes the placeholders generated by THIS request (cumulative
	// counts live in the Redis hash itself).
	Stats SanitizeStats
	// MessageRefs records message-level provenance without retaining plaintext.
	MessageRefs []SanitizedMessageRef
}

// SanitizedMessageRef links one message before and after sanitization. Hashes
// are fingerprints only; raw message content and sensitive values never cross
// the sanitizer/compression boundary.
//
// ⚠️ COORDINATE SPACE (2026-10-03, audit 196号): RawIndex/SanitizedIndex index
// the **client request body's** message array. Sanitization rewrites bytes in
// place and never reorders or re-lengths that array, so the two indexes are
// always the same client-array position (they are assigned from one loop
// counter in security/sanitize/input_protocols.go:188).
//
// They are NOT comparable with AlignmentInfo.OriginalIndex, which indexes the
// **assembled outbound** array (diff.go:142-144 assembles `lastMsgs ++
// deltaTail`), and the two differ by a session-state-dependent offset — after a
// compression the assembled body is shorter than the client's history, so the
// same message sits at different positions. The hashes are not a fallback
// either: RawHash/SanitizedHash are MessageFingerprint (full 64-hex sha256 over
// json.Compact output, key order preserved) while AlignmentInfo.Hash is msgHash
// (32-hex, sha256 over Unmarshal+Marshal output, Go sorts object keys).
//
// ⚠️ CORRECTION (2026-10-03, audit 216号): the sentence that used to stand
// here read "Today this costs nothing because MessageRefs has no production
// consumer". **That was wrong, and wrong in the dangerous direction.**
// MessageRefs DOES have a production consumer and is persisted on every
// request: buildOutboundProvenance (domains/streaming/request_log_pipeline.go:1498)
// reads SanitizeInfo.MessageRefs and emits `sanitize_message_refs`, called from
// handler.go:4017 (chat, with AlignmentMap), responses.go:272 and
// messages.go:262 (both pass alignment=nil). The product lands in
// request_logs.compression_meta, and sessions_v2 reads it back at
// domains/session/v2/cache_v2.go:803.
//
// What is actually missing is narrower and must be stated exactly:
// **both sides are persisted, but nothing JOINS them.** The trap is the first
// consumer that tries to join, not a consumer's absence — the data is in the
// database today and will stay there.
//
// Why the old wording mattered: "no production consumer" invites the reading
// "the provenance data is never persisted, so the seam cannot hurt anyone".
// The truth is the reverse — the data is persisted, so the seam is reachable by
// anyone who writes the join later, and it will then silently answer "where did
// original message N go?" from the wrong row.
//
// One more correction, about this very edit: 216号's first draft of this comment
// said the old sentence had "already drifted once", implying it was once true
// and went stale. That was wrong too. 196号 wrote the sentence on 2026-10-03;
// 80号's producer/consumer verification was published 2026-10-01. **Both sit in
// the same docs/全面审计v3 tree, and the sentence contradicted a conclusion
// that was already on disk when it was written.** It was wrong at birth, not
// stale. (80号 verified the chain; 216号 re-verified it on current HEAD.)
//
// Both coordinate/hash facts above are pinned by provenance_seam_pin_test.go,
// which 216号 also re-verified still fails when diff.go's assembly order is
// inverted — i.e. the pin has real discriminating power.
type SanitizedMessageRef struct {
	RawIndex         int    `json:"raw_index"`
	SanitizedIndex   int    `json:"sanitized_index"`
	RawHash          string `json:"raw_hash"`
	SanitizedHash    string `json:"sanitized_hash"`
	Changed          bool   `json:"changed"`
	PlaceholderCount int    `json:"placeholder_count,omitempty"`
}

// MessageSnapshot is the metadata contract for a message-array snapshot. It
// deliberately contains only a body fingerprint and counts, never the body.
type MessageSnapshot struct {
	Hash          string `json:"hash,omitempty"`
	MessageCount  int    `json:"message_count,omitempty"`
	TokenEstimate int    `json:"token_estimate,omitempty"`
}

// IsZero reports whether the snapshot contains no body fingerprint or counts.
func (s MessageSnapshot) IsZero() bool {
	return s.Hash == "" && s.MessageCount == 0 && s.TokenEstimate == 0
}

// SnapshotForBody returns a privacy-safe snapshot of a JSON request body.
func SnapshotForBody(body []byte) MessageSnapshot {
	if len(body) == 0 {
		return MessageSnapshot{}
	}
	return MessageSnapshot{
		Hash:          sha256Hex(body),
		MessageCount:  countMessages(body),
		TokenEstimate: estimateBodyTokens(body),
	}
}

// MessageFingerprint returns a stable fingerprint for one serialized message.
func MessageFingerprint(message []byte) string { return sha256Hex(message) }

type sanitizeInfoCtxKey struct{}

// WithSanitizeInfo attaches the sanitize bridge info to the request context.
func WithSanitizeInfo(ctx context.Context, info SanitizeInfo) context.Context {
	return context.WithValue(ctx, sanitizeInfoCtxKey{}, info)
}

// SanitizeInfoFromContext reads the bridge info; ok=false when the request
// carried no sanitization (middleware absent or nothing matched).
func SanitizeInfoFromContext(ctx context.Context) (SanitizeInfo, bool) {
	info, ok := ctx.Value(sanitizeInfoCtxKey{}).(SanitizeInfo)
	return info, ok
}

func sanitizeGeneration(ctx context.Context) string {
	info, _ := SanitizeInfoFromContext(ctx)
	return info.MapGeneration
}

func sanitizeGenerationMatches(ctx context.Context, cached string) bool {
	current := sanitizeGeneration(ctx)
	return current == cached
}

// BuildSanitizeInfo derives SanitizeInfo from a placeholder→plaintext map.
// Placeholder counts are classified by parsing the placeholder token itself,
// so callers that merge maps across messages (the HTTP middleware) get the
// same shape as security/sanitize.BuildSanitizeStats without needing the
// per-message Fragments slice.
//
// T11-P0: tenantHash 拼入 MapRef，与写入侧 SanitizeRedisKey 对齐。
func BuildSanitizeInfo(tenantHash, sessionID string, placeholderTypeOf func(placeholder string) (string, bool), sm map[string]struct{}) SanitizeInfo {
	info := SanitizeInfo{
		Stats: SanitizeStats{SanitizedAt: time.Now().Unix()},
	}
	if len(sm) == 0 {
		return info
	}
	if tenantHash == "" {
		info.MapRef = SessionSanitizeRedisKey(sessionID)
	} else {
		info.MapRef = SessionSanitizeRedisKey(tenantHash, sessionID)
	}
	info.Stats.PlaceholderCount = len(sm)
	for ph := range sm {
		typ, ok := placeholderTypeOf(ph)
		if !ok {
			continue
		}
		switch typ {
		case "phone":
			info.Stats.PhoneCount++
		case "email":
			info.Stats.EmailCount++
		case "id_card":
			info.Stats.IDCardCount++
		case "credit_card":
			info.Stats.CreditCardCount++
		case "secret":
			info.Stats.SecretCount++
		default:
			// Every placeholder must land in exactly one bucket, otherwise the
			// named counts do not add up to PlaceholderCount.
			info.Stats.OtherCount++
		}
	}
	return info
}

// SessionSanitizeRedisKey mirrors security/sanitize.SanitizeRedisKey. The
// format is duplicated by necessity (that package imports this one); the
// cross-layer consistency is pinned by TestSessionSanitizeRedisKeyMatches in
// security/sanitize.
//
// T11-P0 v2: key 增加 tenantHash 段（session:{tenantHash}:{sessionID}:sanitize），
// 跨租户隔离写入/读取。tenantHash 由 caller 通过 HashTenant 派生；本函数不做
// 二次 fallback（与 security/sanitize 行为一致）。
func SessionSanitizeRedisKey(parts ...string) string {
	if len(parts) >= 2 {
		return fmt.Sprintf("session:%s:%s:sanitize", parts[0], parts[1])
	}
	if len(parts) == 1 {
		return fmt.Sprintf("session:%s:sanitize", parts[0])
	}
	return ""
}

// SessionSanitizeOffsetRedisKey mirrors security/sanitize.SanitizeOffsetRedisKey.
// T11-P0 v2：同上，tenantHash 进入 key。
func SessionSanitizeOffsetRedisKey(parts ...string) string {
	if len(parts) >= 2 {
		return fmt.Sprintf("session:%s:%s:sanitize:offsets", parts[0], parts[1])
	}
	if len(parts) == 1 {
		return fmt.Sprintf("session:%s:sanitize:offsets", parts[0])
	}
	return ""
}
