package compression

import (
	"context"
	"fmt"
	"time"
)

// SanitizeInfo is the per-request bridge between the HTTP sanitize
// middleware (security/sanitize) and the three-tier session cache (SC-1,
// docs/修订0811/19). The middleware stashes it in the request context after
// replacing sensitive values with placeholders; the session compressor
// persists it into SessionState so the v8 L3 fields (SanitizeMapRef /
// SanitizeStats) stop being write-orphaned.
//
// Defined here (not in security/sanitize) because that package already
// imports compression for SanitizeStats — the context plumbing must live on
// the compression side to keep the dependency one-directional.
type SanitizeInfo struct {
	// MapRef is the Redis key holding the placeholder→plaintext map for the
	// session ("session:{id}:sanitize"). Empty when this request produced no
	// new placeholders.
	MapRef string
	// Stats summarizes the placeholders generated by THIS request (cumulative
	// counts live in the Redis hash itself).
	Stats SanitizeStats
}

type sanitizeInfoCtxKey struct{}

// WithSanitizeInfo attaches the sanitize bridge info to the request context.
func WithSanitizeInfo(ctx context.Context, info SanitizeInfo) context.Context {
	return context.WithValue(ctx, sanitizeInfoCtxKey{}, info)
}

// SanitizeInfoFromContext reads the bridge info; ok=false when the request
// carried no sanitization (middleware absent or nothing matched).
func SanitizeInfoFromContext(ctx context.Context) (SanitizeInfo, bool) {
	info, ok := ctx.Value(sanitizeInfoCtxKey{}).(SanitizeInfo)
	return info, ok
}

// BuildSanitizeInfo derives SanitizeInfo from a placeholder→plaintext map.
// Placeholder counts are classified by parsing the placeholder token itself,
// so callers that merge maps across messages (the HTTP middleware) get the
// same shape as security/sanitize.BuildSanitizeStats without needing the
// per-message Fragments slice.
func BuildSanitizeInfo(sessionID string, placeholderTypeOf func(placeholder string) (string, bool), sm map[string]struct{}) SanitizeInfo {
	info := SanitizeInfo{
		Stats: SanitizeStats{SanitizedAt: time.Now().Unix()},
	}
	if len(sm) == 0 {
		return info
	}
	info.MapRef = SessionSanitizeRedisKey(sessionID)
	info.Stats.PlaceholderCount = len(sm)
	for ph := range sm {
		typ, ok := placeholderTypeOf(ph)
		if !ok {
			continue
		}
		switch typ {
		case "phone":
			info.Stats.PhoneCount++
		case "email":
			info.Stats.EmailCount++
		case "id_card":
			info.Stats.IDCardCount++
		case "credit_card":
			info.Stats.CreditCardCount++
		case "secret":
			info.Stats.SecretCount++
		}
	}
	return info
}

// SessionSanitizeRedisKey mirrors security/sanitize.SanitizeRedisKey. The
// format is duplicated by necessity (that package imports this one); the
// cross-layer consistency is pinned by TestSessionSanitizeRedisKeyMatches in
// security/sanitize.
func SessionSanitizeRedisKey(sessionID string) string {
	return fmt.Sprintf("session:%s:sanitize", sessionID)
}

// SessionSanitizeOffsetRedisKey mirrors security/sanitize.SanitizeOffsetRedisKey.
func SessionSanitizeOffsetRedisKey(sessionID string) string {
	return fmt.Sprintf("session:%s:sanitize:offsets", sessionID)
}
