#!/usr/bin/env bash
# ============================================================================
# scripts/local-host-deploy.sh — 本机版本化部署 / 回退 / 状态 (245 风格)
#
# 学习 245 部署 (/opt/llm-gateway-go/releases/<v>/{gateway,web,version.json,...})
# 的"atomic symlink 切换 + 验证后才算 verified + 自动 prune 旧版本"模型,
# 但跑在本地 macOS 上 —— 直接 host 启动 gateway 二进制, 不走 systemd。
#
# 目录布局: see scripts/local-host-layout-helper.sh
#
# 用法:
#   bash scripts/local-host-deploy.sh deploy           # 编译并部署当前 HEAD
#   bash scripts/local-host-deploy.sh deploy --keep N  # 保留 N 个 verified 版本
#   bash scripts/local-host-deploy.sh start            # 启动当前 active
#   bash scripts/local-host-deploy.sh stop             # 停止当前进程
#   bash scripts/local-host-deploy.sh restart          # 重启当前 active
#   bash scripts/local-host-deploy.sh status           # 进程 + healthz + 当前版本
#   bash scripts/local-host-deploy.sh list             # 所有 bundle + 标记 active/verified
#   bash scripts/local-host-deploy.sh rollback <ver>   # 回退到指定 verified 版本
#   bash scripts/local-host-deploy.sh logs [N]         # tail -n N ~/Downloads/llm-gateway-files/logs/gateway.stdout.log
#   bash scripts/local-host-deploy.sh verify           # 重跑 L1 验证 (不重启)
#   bash scripts/local-host-deploy.sh cleanup          # 停止并删除当前 active bundle
#   bash scripts/local-host-deploy.sh env              # 输出当前 active 的 env (供 source)
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=local-host-layout-helper.sh
source "$SCRIPT_DIR/local-host-layout-helper.sh"

# ── Colors ───────────────────────────────────────────────────────────────
RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'
BLUE=$'\033[0;34m'; CYAN=$'\033[0;36m'; NC=$'\033[0m'
log()   { echo -e "${BLUE}[lh-deploy]${NC} $*"; }
ok()    { echo -e "${GREEN}  ✓${NC} $*"; }
warn()  { echo -e "${YELLOW}  ⚠${NC} $*"; }
err()   { echo -e "${RED}  ✗${NC} $*" >&2; }
section()  { echo -e "\n${CYAN}━━━ $* ━━━${NC}"; }

# ── Defaults ──────────────────────────────────────────────────────────────
KEEP_VERIFIED=3
PORT=8781
ACTION="${1:-}"

# ── Parse args ────────────────────────────────────────────────────────────
shift || true
while [[ $# -gt 0 ]]; do
  case "$1" in
    --keep) KEEP_VERIFIED="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --root) LLM_GATEWAY_FILES_ROOT="$2"; export LLM_GATEWAY_FILES_ROOT; shift 2 ;;
    -h|--help)
      sed -n '2,30p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) err "unknown arg: $1"; exit 1 ;;
  esac
done

# ── Pre-flight ────────────────────────────────────────────────────────────
lh_require_root >/dev/null

# Try to discover the local PG password from env-injector. Fall back to
# kxpass (the r112 compose default) only if no secret is loaded.
if [[ -z "${COMMON_PG_SUPERUSER_PASS:-}" ]]; then
  # shellcheck disable=SC1090 # loader path is env-dependent (per-machine), shellcheck can't follow it
  source ~/workspace/ai-native-tools/envs/loader.sh --project llm-gateway-go --server 115.29.212.252 2>/dev/null || true
fi
LOCAL_PG_PASS="${COMMON_PG_SUPERUSER_PASS:-kxpass}"

# Load version.json SSOT (git_tag + build_seq + git_sha → version string).
VERSION_JSON="$PROJECT_ROOT/version.json"
if [[ ! -f "$VERSION_JSON" ]]; then
  err "version.json not found at $VERSION_JSON"
  exit 1
fi
GIT_TAG=$(python3 -c "import json;print(json.load(open('$VERSION_JSON'))['git_tag'])")
BUILD_SEQ=$(python3 -c "import json;print(json.load(open('$VERSION_JSON'))['build_seq'])")
GIT_SHA=$(python3 -c "import json;print(json.load(open('$VERSION_JSON'))['git_sha'])")
VERSION="${GIT_TAG}.${BUILD_SEQ}"

log "version: $VERSION  (git_tag=$GIT_TAG build_seq=$BUILD_SEQ git_sha=$GIT_SHA)"

# ── Env contract (mirrors local-deploy-test.sh gateway_env()) ─────────────
# These are written into each bundle's env.sh so the runner sources the right
# values without leaking secrets through /tmp.
emit_env_block() {
  local bundle_dir=$1
  cat >"$bundle_dir/env.sh" <<ENVEOF
# Auto-generated by scripts/local-host-deploy.sh for $VERSION
export LLM_GATEWAY_LISTEN=":$PORT"
export LLM_GATEWAY_ENV="\${LLM_GATEWAY_ENV:-local}"
export LOG_LEVEL="\${LOG_LEVEL:-info}"
export LLM_GATEWAY_DATABASE_URL="\${LLM_GATEWAY_DATABASE_URL:-postgres://llm_gateway:${LOCAL_PG_PASS}@127.0.0.1:5432/llm_gateway?sslmode=disable}"
export LLM_GATEWAY_REDIS_ADDR="\${LLM_GATEWAY_REDIS_ADDR:-127.0.0.1:16379}"
export LLM_GATEWAY_REDIS_PASSWORD="\${LLM_GATEWAY_REDIS_PASSWORD:-}"
export LLM_GATEWAY_CREDENTIAL_ENCRYPTION_KEY="\${LLM_GATEWAY_CREDENTIAL_ENCRYPTION_KEY:-AwoRGB8mLTQ7QklQV15lbHN6gYiPlp2kq7K5wMfO1dw}"
export LLM_GATEWAY_JWT_SECRET="\${LLM_GATEWAY_JWT_SECRET:-local-dev-secret-do-not-use-in-production-12345678}"
export LLM_GATEWAY_ADMIN_API_KEY="\${LLM_GATEWAY_ADMIN_API_KEY:-local-admin-test-token-do-not-use-in-production}"
export LLM_GATEWAY_CORS_ORIGINS="\${LLM_GATEWAY_CORS_ORIGINS:-*}"
export LLM_GATEWAY_ATTACHMENT_DIR="$(lh_layout_vars | sed -n 's/^attachments_dir=//p')"
export LLM_GATEWAY_BACKUP_DIR="$(lh_layout_vars | sed -n 's/^backups_dir=//p')"
export LLM_GATEWAY_RAW_LOG_DIR="$(lh_layout_vars | sed -n 's/^raw_logs_dir=//p')"
export LLM_GATEWAY_UPSTREAM="\${LLM_GATEWAY_UPSTREAM:-http://localhost:18080}"
export LLM_GATEWAY_SEED_ADMIN_PASSWORD="\${LLM_GATEWAY_SEED_ADMIN_PASSWORD:-Veritrans&9527}"
export LLM_GATEWAY_SYSTEM_MONITOR_ENABLED="\${LLM_GATEWAY_SYSTEM_MONITOR_ENABLED:-true}"
export OPS_NODE_REGION="\${OPS_NODE_REGION:-local}"
export OPS_COLLECT_URL="\${OPS_COLLECT_URL:-https://llm.kxpms.cn}"
export LLM_GATEWAY_STATIC_DIR="\${LLM_GATEWAY_STATIC_DIR:-./web}"
ENVEOF
  chmod 0600 "$bundle_dir/env.sh"
}

# Per-bundle run scripts. start.sh does the binary launch; stop.sh SIGTERMs and
# waits for the port to free. Both source env.sh so the binary sees the same
# environment as the active bundle.
emit_run_scripts() {
  local bundle_dir=$1
  local vars logs_dir pid_file
  vars=$(lh_layout_vars)
  logs_dir=$(echo "$vars" | sed -n 's/^logs_dir=//p')
  pid_file=$(echo "$vars" | sed -n 's/^pid_file=//p')

  cat >"$bundle_dir/start.sh" <<SCRIPTEOF
#!/usr/bin/env bash
# Auto-generated by scripts/local-host-deploy.sh for $VERSION
set -euo pipefail
BUNDLE_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
LOGS_DIR="$logs_dir"
PID_FILE="$pid_file"
PORT="$PORT"
VERSION="$VERSION"
LOG_FILE="\${LOGS_DIR}/gateway.stdout.log"
ERR_FILE="\${LOGS_DIR}/gateway.stderr.log"
mkdir -p "\$LOGS_DIR"

# Stop any existing instance first (idempotent)
if [[ -f "\$PID_FILE" ]] && kill -0 "\$(cat "\$PID_FILE")" 2>/dev/null; then
  echo "[start] killing existing PID \$(cat "\$PID_FILE")"
  kill "\$(cat "\$PID_FILE")" 2>/dev/null || true
  for _ in {1..20}; do kill -0 "\$(cat "\$PID_FILE")" 2>/dev/null || break; sleep 0.25; done
fi

# shellcheck disable=SC1091
source "\$BUNDLE_DIR/env.sh"

cd "\$BUNDLE_DIR"
nohup "./gateway" >"\$LOG_FILE" 2>>"\$ERR_FILE" &
echo \$! > "\$PID_FILE"
echo \$PORT > "\${PID_FILE%.pid}.port"
chmod 0600 "\$PID_FILE"
echo "[start] \$VERSION launched PID=\$! port=\$PORT"

# Wait for /healthz
for _ in {1..60}; do
  if curl -fsS --max-time 2 "http://127.0.0.1:\$PORT/healthz" >/dev/null 2>&1; then
    echo "[start] healthz OK"
    exit 0
  fi
  sleep 1
done
echo "[start] WARN healthz did not respond in 60s (see \$LOG_FILE)" >&2
exit 1
SCRIPTEOF
  chmod 0755 "$bundle_dir/start.sh"

  cat >"$bundle_dir/stop.sh" <<SCRIPTEOF
#!/usr/bin/env bash
# Auto-generated by scripts/local-host-deploy.sh for $VERSION
set -euo pipefail
PID_FILE="$pid_file"
PORT="$PORT"
if [[ ! -f "\$PID_FILE" ]]; then echo "[stop] no PID file"; exit 0; fi
PID="\$(cat "\$PID_FILE")"
if ! kill -0 "\$PID" 2>/dev/null; then echo "[stop] PID \$PID not running"; rm -f "\$PID_FILE"; exit 0; fi
echo "[stop] sending SIGTERM to \$PID"
kill "\$PID"
for _ in {1..30}; do
  if ! curl -fsS --max-time 1 "http://127.0.0.1:\$PORT/healthz" >/dev/null 2>&1; then
    rm -f "\$PID_FILE"
    echo "[stop] port \$PORT released"
    exit 0
  fi
  kill -0 "\$PID" 2>/dev/null || { rm -f "\$PID_FILE"; echo "[stop] process gone"; exit 0; }
  sleep 1
done
echo "[stop] port still serving after 30s, escalating to SIGKILL"
kill -9 "\$PID" 2>/dev/null || true
rm -f "\$PID_FILE"
SCRIPTEOF
  chmod 0755 "$bundle_dir/stop.sh"

  cat >"$bundle_dir/status.sh" <<SCRIPTEOF
#!/usr/bin/env bash
# Auto-generated by scripts/local-host-deploy.sh for $VERSION
set -euo pipefail
PID_FILE="$pid_file"
PORT="$PORT"
VERSION="$VERSION"
echo "version: \$VERSION"
if [[ -f "\$PID_FILE" ]]; then
  PID="\$(cat "\$PID_FILE")"
  if kill -0 "\$PID" 2>/dev/null; then
    echo "pid: \$PID (alive)"
  else
    echo "pid: \$PID (stale)"
  fi
else
  echo "pid: (not running)"
fi
if curl -fsS --max-time 2 "http://127.0.0.1:\$PORT/healthz" 2>/dev/null; then
  echo "health: OK"
else
  echo "health: UNREACHABLE"
fi
SCRIPTEOF
  chmod 0755 "$bundle_dir/status.sh"

  cat >"$bundle_dir/logs.sh" <<SCRIPTEOF
#!/usr/bin/env bash
# Auto-generated by scripts/local-host-deploy.sh for $VERSION
exec tail -n "\${1:-50}" -f "$logs_dir/gateway.stdout.log"
SCRIPTEOF
  chmod 0755 "$bundle_dir/logs.sh"
}

# ── Build pipeline ────────────────────────────────────────────────────────
build_backend() {
  local bin_out=$1
  log "go build -o $bin_out ./cmd/gateway"
  (cd "$PROJECT_ROOT" && CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o "$bin_out" ./cmd/gateway)
}

build_frontend() {
  # shellcheck disable=SC2034 # `dist` is kept for the public function signature even though the build path doesn't currently take it.
  local dist=$1
  log "npm run build (web/)"
  if [[ -d "$PROJECT_ROOT/web" ]]; then
    (cd "$PROJECT_ROOT/web" && npm run build) >/dev/null
  fi
}

# ── Commands ──────────────────────────────────────────────────────────────

cmd_deploy() {
  section "deploy $VERSION (build_seq=$BUILD_SEQ keep=$KEEP_VERIFIED)"

  local vars bin_dir bundle_dir
  vars=$(lh_layout_vars)
  bin_dir=$(echo "$vars" | sed -n 's/^bin_dir=//p')
  bundle_dir="$bin_dir/$VERSION"

  if [[ -d "$bundle_dir" ]]; then
    warn "bundle $VERSION already exists at $bundle_dir — re-deploying in place"
    rm -rf "$bundle_dir"
  fi
  mkdir -p "$bundle_dir"

  # Build
  build_backend "$bundle_dir/gateway"
  build_frontend "$PROJECT_ROOT/web/dist"

  # Stage
  cp -R "$PROJECT_ROOT/web/dist/." "$bundle_dir/web/"
  cp "$PROJECT_ROOT/version.json" "$bundle_dir/version.json"
  printf '%s\n' "$VERSION" > "$bundle_dir/VERSION"
  if [[ -d "$PROJECT_ROOT/configs" ]]; then
    cp -R "$PROJECT_ROOT/configs" "$bundle_dir/configs"
  fi

  # Bundle scripts + env
  emit_env_block "$bundle_dir"
  emit_run_scripts "$bundle_dir"

  # Manifest + verify
  lh_stage_release "$bundle_dir" "$VERSION"
  lh_verify_bundle "$bundle_dir"
  ok "bundle staged + SHA256SUMS verified"

  # Atomic switch (updates `current` + top-level shortcuts)
  lh_atomic_switch "$VERSION"
  ok "active symlink → $VERSION"

  # Start
  log "starting gateway..."
  "$bundle_dir/start.sh"

  # Mark verified if healthz passes
  local health_url="http://127.0.0.1:$PORT/healthz"
  if curl -fsS --max-time 5 "$health_url" >/dev/null 2>&1; then
    lh_mark_verified "$VERSION"
    ok "$VERSION marked verified"
  else
    warn "healthz did not respond — leaving verified=false (rollback candidates may include this version after manual verification)"
  fi

  # Prune old verified bundles
  log "pruning (keep=$KEEP_VERIFIED verified bundles + active)..."
  local keep_set
  keep_set=$(lh_prune_releases "$KEEP_VERIFIED")
  ok "retained: $keep_set"

  log "deployment complete — current=$VERSION port=$PORT"
}

cmd_start() {
  local bundle_dir
  bundle_dir=$(lh_bundle_dir "$(lh_active_version)")
  if [[ ! -d "$bundle_dir" ]]; then
    err "no active bundle; run 'deploy' first"
    exit 1
  fi
  "$bundle_dir/start.sh"
}

cmd_stop() {
  local bundle_dir
  bundle_dir=$(lh_bundle_dir "$(lh_active_version)")
  if [[ ! -d "$bundle_dir" ]]; then err "no active bundle"; exit 1; fi
  "$bundle_dir/stop.sh"
}

cmd_restart() {
  cmd_stop || true
  cmd_start
}

cmd_status() {
  local active
  active=$(lh_active_version)
  if [[ -z "$active" ]]; then
    echo "active: (none)"
    return 0
  fi
  local bundle_dir
  bundle_dir=$(lh_bundle_dir "$active")
  "$bundle_dir/status.sh"
}

cmd_list() {
  local bin_dir active
  bin_dir=$(lh_layout_vars | sed -n 's/^bin_dir=//p')
  active=$(lh_active_version)
  printf '%-25s  %-12s  %-22s  %s\n' "VERSION" "STATE" "VERIFIED_AT" "PATH"
  for entry in "$bin_dir"/*; do
    [[ -e "$entry" ]] || continue
    local base
    base=$(basename "$entry")
    [[ "$base" == "current" ]] && continue
    [[ -L "$entry" ]] && continue
    [[ -d "$entry" ]] || continue
    local v meta state ts d
    d="$entry"
    v="$base"
    meta="$d/deployment.json"
    if [[ "$v" == "$active" ]]; then
      state="active"
    else
      state="inactive"
    fi
    if [[ -f "$meta" ]]; then
      if grep -q '"verified":[[:space:]]*true' "$meta"; then
        ts=$(grep -o '"verified_at"[[:space:]]*:[[:space:]]*"[^"]*"' "$meta" | head -1 | sed 's/.*"verified_at"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
        [[ -n "$ts" ]] && state="$state+verified"
      else
        state="$state+unverified"
      fi
    else
      state="$state+no-meta"
    fi
    printf '%-25s  %-22s  %-22s  %s\n' "$v" "$state" "${ts:-—}" "$d"
  done
}

cmd_rollback() {
  local target=${1:-}
  if [[ -z "$target" ]]; then
    err "rollback requires a version argument (use 'list' to see available)"
    exit 1
  fi
  local bundle_dir
  bundle_dir=$(lh_bundle_dir "$target")
  if [[ ! -d "$bundle_dir" ]]; then
    err "bundle not found: $target"
    exit 1
  fi
  section "rollback → $target"
  lh_rollback_to "$target" || { err "rollback refused (see helper for reasons)"; exit 1; }
  ok "active symlink → $target"
  cmd_stop || true
  cmd_start
  lh_mark_verified "$target"
  ok "$target re-verified"
}

cmd_logs() {
  local vars logs_dir
  vars=$(lh_layout_vars)
  logs_dir=$(echo "$vars" | sed -n 's/^logs_dir=//p')
  local lines=${1:-50}
  tail -n "$lines" -f "$logs_dir/gateway.stdout.log"
}

cmd_verify() {
  local health_url="http://127.0.0.1:$PORT/healthz"
  log "GET $health_url"
  curl -fsS --max-time 5 "$health_url" | python3 -m json.tool
}

cmd_cleanup() {
  local active
  active=$(lh_active_version)
  if [[ -z "$active" ]]; then warn "no active bundle"; return 0; fi
  warn "this will STOP and DELETE bundle $active"
  read -rp "continue? [y/N] " yn
  [[ "$yn" =~ ^[Yy]$ ]] || { echo "aborted"; exit 1; }
  cmd_stop || true
  local bundle_dir
  bundle_dir=$(lh_bundle_dir "$active")
  rm -rf "$bundle_dir"
  ok "deleted $bundle_dir"
}

cmd_env() {
  local active
  active=$(lh_active_version)
  if [[ -z "$active" ]]; then err "no active bundle"; exit 1; fi
  local bundle_dir
  bundle_dir=$(lh_bundle_dir "$active")
  cat "$bundle_dir/env.sh"
}

# ── Dispatch ──────────────────────────────────────────────────────────────
case "$ACTION" in
  deploy)   cmd_deploy ;;
  start)    cmd_start ;;
  stop)     cmd_stop ;;
  restart)  cmd_restart ;;
  status)   cmd_status ;;
  list)     cmd_list ;;
  rollback) cmd_rollback "${1:-}" ;;
  logs)     cmd_logs "${1:-50}" ;;
  verify)   cmd_verify ;;
  cleanup)  cmd_cleanup ;;
  env)      cmd_env ;;
  *)        err "unknown action: $ACTION"; exit 1 ;;
esac
