#!/usr/bin/env bash
# ============================================================================
# scripts/local-host-deploy-bluegreen.sh — 本地蓝绿无缝部署
#
# 实现 < 2 秒的零停机部署切换，通过：
#   1. 在候选端口预热新版本（旧版本继续服务）
#   2. 探测候选实例 healthz + readyz
#   3. 原子切换 Nginx upstream
#   4. 异步 drain 旧实例
#
# 依赖:
#   - Nginx 已通过 scripts/setup-local-nginx.sh 初始化
#   - PostgreSQL + Redis 已启动
#
# 用法:
#   bash scripts/local-host-deploy-bluegreen.sh deploy          # 蓝绿部署
#   bash scripts/local-host-deploy-bluegreen.sh rollback <ver> # 蓝绿回滚
#   bash scripts/local-host-deploy-bluegreen.sh status         # 查看状态
#   bash scripts/local-host-deploy-bluegreen.sh switch <port>  # 手动切换端口
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=local-host-layout-helper.sh
source "$SCRIPT_DIR/local-host-layout-helper.sh"

# ── Colors ───────────────────────────────────────────────────────────────
RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'
BLUE=$'\033[0;34m'; CYAN=$'\033[0;36m'; MAGENTA=$'\033[0;35m'; NC=$'\033[0m'
log()     { echo -e "${BLUE}[bg-deploy]${NC} $*"; }
ok()      { echo -e "${GREEN}  ✓${NC} $*"; }
warn()    { echo -e "${YELLOW}  ⚠${NC} $*"; }
err()     { echo -e "${RED}  ✗${NC} $*" >&2; }
section() { echo -e "\n${CYAN}━━━ $* ━━━${NC}"; }
timing()  { echo -e "${MAGENTA}  ⏱${NC} $*"; }

# ── 配置 ─────────────────────────────────────────────────────────────────
KEEP_VERIFIED=3
ACTION="${1:-}"

# Runtime secrets are intentionally supplied by the caller. Do not source an
# out-of-repository loader or fall back to deployable credentials here.

# 加载版本信息
VERSION_JSON="$PROJECT_ROOT/version.json"
[[ -f "$VERSION_JSON" ]] || { err "version.json not found"; exit 1; }

GIT_TAG=$(python3 -c "import json;print(json.load(open('$VERSION_JSON'))['git_tag'])")
BUILD_SEQ=$(python3 -c "import json;print(json.load(open('$VERSION_JSON'))['build_seq'])")
GIT_SHA=$(python3 -c "import json;print(json.load(open('$VERSION_JSON'))['git_sha'])")
VERSION="${GIT_TAG}.${BUILD_SEQ}"

# ── 环境变量生成 ──────────────────────────────────────────────────────────
emit_env_block() {
  local bundle_dir=$1
  local port=$2
  local vars attach_dir backup_dir raw_log_dir
  vars=$(lh_layout_vars)
  attach_dir=$(echo "$vars" | sed -n 's/^attachments_dir=//p')
  backup_dir=$(echo "$vars" | sed -n 's/^backups_dir=//p')
  raw_log_dir=$(echo "$vars" | sed -n 's/^raw_logs_dir=//p')
  
  cat >"$bundle_dir/env.sh" <<ENVEOF
# Auto-generated by scripts/local-host-deploy-bluegreen.sh for $VERSION
export LLM_GATEWAY_LISTEN=":$port"
export LLM_GATEWAY_RUNTIME_ROLE="${LLM_GATEWAY_RUNTIME_ROLE:-active}"
export LLM_GATEWAY_ENV="\${LLM_GATEWAY_ENV:-local}"
export LOG_LEVEL="\${LOG_LEVEL:-info}"
export LLM_GATEWAY_DATABASE_URL="\${LLM_GATEWAY_DATABASE_URL:?LLM_GATEWAY_DATABASE_URL must be set}"
export LLM_GATEWAY_REDIS_ADDR="\${LLM_GATEWAY_REDIS_ADDR:-127.0.0.1:6379}"
export LLM_GATEWAY_REDIS_PASSWORD="\${LLM_GATEWAY_REDIS_PASSWORD:-}"
export LLM_GATEWAY_CREDENTIAL_ENCRYPTION_KEY="\${LLM_GATEWAY_CREDENTIAL_ENCRYPTION_KEY:?LLM_GATEWAY_CREDENTIAL_ENCRYPTION_KEY must be set}"
export LLM_GATEWAY_JWT_SECRET="\${LLM_GATEWAY_JWT_SECRET:?LLM_GATEWAY_JWT_SECRET must be set}"
export LLM_GATEWAY_ADMIN_API_KEY="\${LLM_GATEWAY_ADMIN_API_KEY:?LLM_GATEWAY_ADMIN_API_KEY must be set}"
export LLM_GATEWAY_CORS_ORIGINS="\${LLM_GATEWAY_CORS_ORIGINS:-*}"
export LLM_GATEWAY_ATTACHMENT_DIR="\${LLM_GATEWAY_ATTACHMENT_DIR:-$attach_dir}"
export LLM_GATEWAY_BACKUP_DIR="\${LLM_GATEWAY_BACKUP_DIR:-$backup_dir}"
export LLM_GATEWAY_RAW_LOG_DIR="\${LLM_GATEWAY_RAW_LOG_DIR:-$raw_log_dir}"
export LLM_GATEWAY_UPSTREAM="\${LLM_GATEWAY_UPSTREAM:-http://localhost:18080}"
export LLM_GATEWAY_SEED_ADMIN_PASSWORD="\${LLM_GATEWAY_SEED_ADMIN_PASSWORD:?LLM_GATEWAY_SEED_ADMIN_PASSWORD must be set}"

export LLM_GATEWAY_SYSTEM_MONITOR_ENABLED="\${LLM_GATEWAY_SYSTEM_MONITOR_ENABLED:-true}"
export OPS_NODE_REGION="\${OPS_NODE_REGION:-local}"
export OPS_COLLECT_URL="\${OPS_COLLECT_URL:-}"
export LLM_GATEWAY_STATIC_DIR="\${LLM_GATEWAY_STATIC_DIR:-./web}"
ENVEOF
  chmod 0600 "$bundle_dir/env.sh"
}

# ── 启动脚本生成 ──────────────────────────────────────────────────────────
emit_start_script() {
  local bundle_dir=$1
  local port=$2
  local vars logs_dir run_dir
  vars=$(lh_layout_vars)
  logs_dir=$(echo "$vars" | sed -n 's/^logs_dir=//p')
  run_dir=$(echo "$vars" | sed -n 's/^run_dir=//p')
  
  cat >"$bundle_dir/start.sh" <<SCRIPTEOF
#!/usr/bin/env bash
set -euo pipefail
BUNDLE_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
LOGS_DIR="$logs_dir"
RUN_DIR="$run_dir"
PORT="$port"
VERSION="$VERSION"
PID_FILE="\${RUN_DIR}/gateway-\${PORT}.pid"
LOG_FILE="\${LOGS_DIR}/gateway-\${PORT}.stdout.log"
ERR_FILE="\${LOGS_DIR}/gateway-\${PORT}.stderr.log"

mkdir -p "\$LOGS_DIR" "\$RUN_DIR"

# 检查是否已在运行
if [[ -f "\$PID_FILE" ]] && kill -0 "\$(cat "\$PID_FILE")" 2>/dev/null; then
  echo "[start] already running on port \$PORT (PID \$(cat "\$PID_FILE"))"
  exit 0
fi

# 检查端口是否被占用
if lsof -Pi :\$PORT -sTCP:LISTEN -t >/dev/null 2>&1; then
  echo "[start] ERROR: port \$PORT already in use by another process" >&2
  lsof -Pi :\$PORT -sTCP:LISTEN >&2
  exit 1
fi

# shellcheck disable=SC1091
source "\$BUNDLE_DIR/env.sh"

cd "\$BUNDLE_DIR"
nohup "./gateway" >"\$LOG_FILE" 2>>"\$ERR_FILE" &
echo \$! > "\$PID_FILE"
chmod 0600 "\$PID_FILE"
echo "[start] \$VERSION launched on :\$PORT (PID \$!)"

# 等待 healthz
for i in {1..60}; do
  if curl -fsS --max-time 2 "http://127.0.0.1:\$PORT/healthz" >/dev/null 2>&1; then
    echo "[start] healthz OK after \${i}s"
    exit 0
  fi
  sleep 1
done

echo "[start] WARNING: healthz did not respond in 60s" >&2
exit 1
SCRIPTEOF
  chmod 0755 "$bundle_dir/start.sh"
}

# ── 停止脚本生成 ──────────────────────────────────────────────────────────
emit_stop_script() {
  local bundle_dir=$1
  local port=$2
  local run_dir
  run_dir=$(lh_layout_vars | sed -n 's/^run_dir=//p')
  
  cat >"$bundle_dir/stop.sh" <<SCRIPTEOF
#!/usr/bin/env bash
set -euo pipefail
PORT="$port"
PID_FILE="$run_dir/gateway-\${PORT}.pid"

if [[ ! -f "\$PID_FILE" ]]; then
  echo "[stop] no PID file for port \$PORT"
  exit 0
fi

PID="\$(cat "\$PID_FILE")"
if ! kill -0 "\$PID" 2>/dev/null; then
  echo "[stop] PID \$PID not running"
  rm -f "\$PID_FILE"
  exit 0
fi

echo "[stop] sending SIGTERM to PID \$PID (port \$PORT)"
kill "\$PID"

# 等待端口释放（最多 30s）
for i in {1..30}; do
  if ! lsof -Pi :\$PORT -sTCP:LISTEN -t >/dev/null 2>&1; then
    rm -f "\$PID_FILE"
    echo "[stop] port \$PORT released after \${i}s"
    exit 0
  fi
  sleep 1
done

echo "[stop] port \$PORT still in use after 30s, escalating to SIGKILL"
kill -9 "\$PID" 2>/dev/null || true
rm -f "\$PID_FILE"
SCRIPTEOF
  chmod 0755 "$bundle_dir/stop.sh"
}

# ── 构建流程 ──────────────────────────────────────────────────────────────
build_backend() {
  local bin_out=$1
  log "go build -o $bin_out ./cmd/gateway"
  (cd "$PROJECT_ROOT" && CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o "$bin_out" ./cmd/gateway)
}

build_frontend() {
  log "npm run build (web/)"
  if [[ -d "$PROJECT_ROOT/web/node_modules" ]]; then
    (cd "$PROJECT_ROOT/web" && npm run build) >/dev/null
  else
    warn "web/node_modules missing, skipping frontend build"
  fi
}

# ── 验证版本身份 ──────────────────────────────────────────────────────────
verify_version_identity() {
  local port=$1
  local expected_version=$2
  local version_url="http://127.0.0.1:${port}/version"
  
  local body
  if ! body=$(curl -fsS --max-time 5 "$version_url" 2>&1); then
    err "Failed to fetch /version from port $port: $body"
    return 1
  fi
  
  local actual_version
  actual_version=$(echo "$body" | python3 -c "import sys,json;print(json.load(sys.stdin).get('version',''))" 2>/dev/null || echo "")
  
  if [[ "$actual_version" != "$expected_version" ]]; then
    err "Version mismatch: expected=$expected_version, got=$actual_version"
    return 1
  fi
  
  ok "Version identity verified: $expected_version"
  return 0
}

# ── 核心部署流程 ──────────────────────────────────────────────────────────
cmd_deploy() {
  section "blue-green deploy $VERSION (seq=$BUILD_SEQ)"
  
  local deploy_start
  deploy_start=$(date +%s)
  
  # 1. 确定端口
  local active_port candidate_port
  active_port=$(lh_active_port)
  candidate_port=$(lh_candidate_port)
  
  log "Active port: $active_port, Candidate port: $candidate_port"
  
  # 2. 构建 bundle
  local vars bin_dir bundle_dir
  vars=$(lh_layout_vars)
  bin_dir=$(echo "$vars" | sed -n 's/^bin_dir=//p')
  bundle_dir="$bin_dir/$VERSION"
  
  if [[ -d "$bundle_dir" ]]; then
    warn "Bundle $VERSION already exists, rebuilding..."
    rm -rf "$bundle_dir"
  fi
  mkdir -p "$bundle_dir"
  
  section "[1/8] Build backend + frontend"
  build_backend "$bundle_dir/gateway"
  build_frontend
  
  # 3. Stage bundle
  section "[2/8] Stage bundle"
  cp -R "$PROJECT_ROOT/web/dist/." "$bundle_dir/web/" 2>/dev/null || mkdir -p "$bundle_dir/web"
  cp "$PROJECT_ROOT/version.json" "$bundle_dir/version.json"
  printf '%s\n' "$VERSION" > "$bundle_dir/VERSION"
  
  emit_env_block "$bundle_dir" "$candidate_port"
  emit_start_script "$bundle_dir" "$candidate_port"
  emit_stop_script "$bundle_dir" "$candidate_port"
  
  lh_stage_release "$bundle_dir" "$VERSION"
  lh_verify_bundle "$bundle_dir"
  ok "Bundle staged and verified"
  
  # 4. 启动候选实例（并行，不阻塞旧实例）
  section "[3/8] Start candidate on port $candidate_port"
  local candidate_start
  candidate_start=$(date +%s)
  
  "$bundle_dir/start.sh" &
  local start_pid=$!
  
  # 等待启动（最多 60s）
  if ! wait "$start_pid"; then
    err "Candidate failed to start"
    return 1
  fi
  
  local candidate_ready
  candidate_ready=$(date +%s)
  local warmup_time=$((candidate_ready - candidate_start))
  timing "Candidate warmup: ${warmup_time}s"
  
  # 5. 探测候选实例
  section "[4/8] Probe candidate health"
  if ! lh_wait_port_ready "$candidate_port" 60; then
    err "Candidate healthz/readyz failed after 60s"
    "$bundle_dir/stop.sh" || true
    return 1
  fi
  ok "Candidate healthz + readyz OK"
  
  # 6. 验证版本身份
  section "[5/8] Verify version identity"
  if ! verify_version_identity "$candidate_port" "v$GIT_TAG"; then
    err "Version identity mismatch"
    "$bundle_dir/stop.sh" || true
    return 1
  fi
  
  # 7. 原子切换 Nginx upstream（关键：< 2s）
  section "[6/8] Atomic Nginx switch"
  local switch_start switch_end switch_ms
  switch_start=$(date +%s%N 2>/dev/null || python3 -c 'import time; print(int(time.time() * 1e9))')
  
  if ! lh_switch_nginx_upstream "$candidate_port"; then
    err "Nginx switch failed"
    "$bundle_dir/stop.sh" || true
    return 1
  fi
  
  switch_end=$(date +%s%N 2>/dev/null || python3 -c 'import time; print(int(time.time() * 1e9))')
  switch_ms=$(( (switch_end - switch_start) / 1000000 ))
  
  ok "Nginx switched to port $candidate_port"
  timing "Switch duration: ${switch_ms}ms"
  
  if (( switch_ms > 2000 )); then
    warn "Switch exceeded 2s target (${switch_ms}ms)"
  else
    ok "Switch SLO met: ${switch_ms}ms < 2000ms ✓"
  fi
  
  # 8. 验证切换生效
  section "[7/8] Verify Nginx serving candidate"
  sleep 1  # 给 Nginx reload 一点时间
  
  if ! lh_verify_nginx_serving "$candidate_port"; then
    err "Nginx not serving candidate after switch"
    warn "Attempting rollback..."
    lh_switch_nginx_upstream "$active_port" || true
    "$bundle_dir/stop.sh" || true
    return 1
  fi
  ok "Nginx is serving candidate"
  
  # 9. 更新状态指针
  section "[8/8] Finalize deployment"
  lh_atomic_switch "$VERSION"
  lh_set_active_port "$candidate_port"
  lh_mark_verified "$VERSION"
  ok "Deployment state updated"
  
  # 10. 异步 drain 旧实例（不阻塞部署完成）
  (
    log "Draining old instance on port $active_port (async, 5s grace period)..."
    sleep 5
    lh_stop_port "$active_port"
    ok "Old instance drained"
  ) &
  
  local deploy_end
  deploy_end=$(date +%s)
  local total_time=$((deploy_end - deploy_start))
  
  echo ""
  ok "✅ Deployment complete!"
  echo ""
  echo "  Version:        $VERSION"
  echo "  Active port:    $candidate_port"
  echo "  Total time:     ${total_time}s"
  echo "  Switch time:    ${switch_ms}ms"
  echo "  Warmup time:    ${warmup_time}s"
  echo ""
  echo "Access: curl http://localhost:$(lh_layout_vars | grep -E '^' | grep nginx || echo 8781)/healthz"
  echo "Rollback: bash $0 rollback <version>"
  echo ""
  
  # Prune old releases
  log "Pruning old releases (keep=$KEEP_VERIFIED)..."
  local kept
  kept=$(lh_prune_releases "$KEEP_VERIFIED")
  ok "Retained: $kept"
}

# ── 回滚流程 ──────────────────────────────────────────────────────────────
cmd_rollback() {
  local target=${2:-}
  [[ -n "$target" ]] || { err "Rollback requires target version"; echo "Usage: $0 rollback <version>"; exit 1; }
  
  section "blue-green rollback → $target"
  
  local rollback_start
  rollback_start=$(date +%s)
  
  # 1. 确定端口
  local active_port candidate_port
  active_port=$(lh_active_port)
  candidate_port=$(lh_candidate_port)
  
  log "Active: $active_port, Rollback target will use: $candidate_port"
  
  # 2. 验证目标版本
  local bundle_dir
  bundle_dir=$(lh_bundle_dir "$target")
  [[ -d "$bundle_dir" ]] || { err "Bundle not found: $target"; exit 1; }
  
  local meta="$bundle_dir/deployment.json"
  if ! grep -q '"verified":[[:space:]]*true' "$meta"; then
    err "Target version $target is not verified"
    exit 1
  fi
  
  # 3. 重新生成脚本（使用候选端口）
  log "Regenerating scripts for port $candidate_port..."
  emit_env_block "$bundle_dir" "$candidate_port"
  emit_start_script "$bundle_dir" "$candidate_port"
  emit_stop_script "$bundle_dir" "$candidate_port"
  
  # 4. 启动目标版本
  section "Starting rollback target on port $candidate_port"
  "$bundle_dir/start.sh"
  
  if ! lh_wait_port_ready "$candidate_port" 60; then
    err "Rollback target failed health checks"
    "$bundle_dir/stop.sh" || true
    exit 1
  fi
  ok "Rollback target ready"
  
  # 5. 原子切换
  section "Switching Nginx to rollback target"
  local switch_start switch_end switch_ms
  switch_start=$(date +%s%N 2>/dev/null || python3 -c 'import time; print(int(time.time() * 1e9))')
  
  if ! lh_switch_nginx_upstream "$candidate_port"; then
    err "Nginx switch failed during rollback"
    "$bundle_dir/stop.sh" || true
    exit 1
  fi
  
  switch_end=$(date +%s%N 2>/dev/null || python3 -c 'import time; print(int(time.time() * 1e9))')
  switch_ms=$(( (switch_end - switch_start) / 1000000 ))
  
  ok "Nginx switched (${switch_ms}ms)"
  
  # 6. 更新指针
  lh_atomic_switch "$target"
  lh_set_active_port "$candidate_port"
  lh_mark_verified "$target"
  
  # 7. 停止旧实例
  lh_stop_port "$active_port"
  
  local rollback_end
  rollback_end=$(date +%s)
  local total_time=$((rollback_end - rollback_start))
  
  echo ""
  ok "✅ Rollback complete!"
  echo ""
  echo "  Rolled back to: $target"
  echo "  Active port:    $candidate_port"
  echo "  Total time:     ${total_time}s"
  echo "  Switch time:    ${switch_ms}ms"
  echo ""
}

# ── 状态查看 ──────────────────────────────────────────────────────────────
cmd_status() {
  section "Blue-Green Deployment Status"
  
  local active_port candidate_port active_version
  active_port=$(lh_active_port)
  candidate_port=$(lh_candidate_port)
  active_version=$(lh_active_version)
  
  echo ""
  echo "Active version:     ${active_version:-<none>}"
  echo "Active port:        $active_port"
  echo "Candidate port:     $candidate_port"
  echo "Nginx proxy port:   $(lh_layout_vars | grep -o 'nginx.*' || echo '8781')"
  echo ""
  
  # 检查各端口状态
  for port in "$active_port" "$candidate_port"; do
    if lh_port_in_use "$port"; then
      if curl -fsS --max-time 2 "http://127.0.0.1:${port}/healthz" >/dev/null 2>&1; then
        ok "Port $port: ✓ healthy"
      else
        warn "Port $port: running but unhealthy"
      fi
    else
      echo "  Port $port: idle"
    fi
  done
  
  echo ""
  
  # Nginx 状态
  local nginx_root
  nginx_root=$(lh_nginx_root)
  if [[ -f "$nginx_root/nginx.pid" ]] && kill -0 "$(cat "$nginx_root/nginx.pid")" 2>/dev/null; then
    ok "Nginx: running"
    
    if curl -fsS --max-time 2 "http://127.0.0.1:8781/healthz" >/dev/null 2>&1; then
      ok "Nginx proxy: healthy"
    else
      warn "Nginx proxy: not responding"
    fi
  else
    err "Nginx: not running (run: bash scripts/setup-local-nginx.sh)"
  fi
  
  echo ""
}

# ── 手动切换端口 ──────────────────────────────────────────────────────────
cmd_switch() {
  local target_port=${2:-}
  [[ -n "$target_port" ]] || { err "Switch requires target port"; echo "Usage: $0 switch <port>"; exit 1; }
  
  section "Manual switch to port $target_port"
  
  if ! lh_port_in_use "$target_port"; then
    err "Port $target_port is not in use"
    exit 1
  fi
  
  if ! curl -fsS --max-time 2 "http://127.0.0.1:${target_port}/healthz" >/dev/null 2>&1; then
    err "Port $target_port is not healthy"
    exit 1
  fi
  
  if ! lh_switch_nginx_upstream "$target_port"; then
    err "Nginx switch failed"
    exit 1
  fi
  
  lh_set_active_port "$target_port"
  ok "Switched to port $target_port"
}

# ── 主逻辑 ────────────────────────────────────────────────────────────────
lh_require_root >/dev/null

case "$ACTION" in
  deploy)
    cmd_deploy
    ;;
  rollback)
    cmd_rollback "$@"
    ;;
  status)
    cmd_status
    ;;
  switch)
    cmd_switch "$@"
    ;;
  -h|--help)
    sed -n '2,16p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 0
    ;;
  *)
    err "Unknown action: $ACTION"
    echo "Usage: $0 {deploy|rollback|status|switch}"
    exit 1
    ;;
esac
