#!/usr/bin/env bash
# ============================================================================
# scripts/local-docker-up.sh — 本机 Docker 全栈一键部署
#
# 2026-09-02 install layout 规范化：复用 installer/templates/compose.yml（含 PG/
# Redis/Gateway 全栈），仅在 INSTALL_ROOT 下做 bind-mount；守护由 Docker Engine
# + Compose restart: unless-stopped 自动承担（不另建进程）。
#
# 设计原则：
#   - 不破坏现存 ~/Downloads/llm-gateway-files（旧实例继续工作）
#   - 新建按 OS 默认: macOS=~/kaixuan/llm-gateway; Linux=/opt/kaixuan/llm-gateway
#   - 复用现有的 installer/templates/compose.yml（含 logging/10MB rotate +
#     healthcheck 等已完善的 compose 段），无需新写一份
#
# 用法:
#   bash scripts/local-docker-up.sh                       # 探测默认 INSTALL_ROOT
#   INSTALL_ROOT=~/kaixuan/llm-gateway bash scripts/local-docker-up.sh
#   LLM_GATEWAY_HOME=~/kaixuan/llm-gateway bash scripts/local-docker-up.sh
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=local-host-layout-helper.sh
source "$SCRIPT_DIR/local-host-layout-helper.sh"

# ── 颜色 ──────────────────────────────────────────────────────────────────
RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'; BLUE=$'\033[0;34m'; NC=$'\033[0m'
log()  { echo -e "${BLUE}[docker-up]${NC} $*"; }
ok()   { echo -e "${GREEN}  ✓${NC} $*"; }
warn() { echo -e "${YELLOW}  ⚠${NC} $*"; }
err()  { echo -e "${RED}  ✗${NC} $*" >&2; }

# ── 探测前置 ──────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || { err "docker 未安装"; exit 1; }
docker compose version >/dev/null 2>&1 || { err "docker compose plugin 缺失"; exit 1; }

INSTALL_ROOT="${INSTALL_ROOT:-${LLM_GATEWAY_HOME:-$(lh_root)}}"
export LLM_GATEWAY_HOME="$INSTALL_ROOT"
export INSTALL_ROOT

log "INSTALL_ROOT=$INSTALL_ROOT"

# ── 目录准备 ──────────────────────────────────────────────────────────────
mkdir -p \
  "$INSTALL_ROOT/attachments" \
  "$INSTALL_ROOT/backups" \
  "$INSTALL_ROOT/app/logs" \
  "$INSTALL_ROOT/raw-logs" \
  "$INSTALL_ROOT/run" \
  "$INSTALL_ROOT/postgres/data" \
  "$INSTALL_ROOT/redis/data"

# 软链复用老 attachments (若有现存实例，避免重复占盘)
OLD_ROOT="$HOME/Downloads/llm-gateway-files"
if [[ "$INSTALL_ROOT" != "$OLD_ROOT" ]] \
   && [[ -d "$OLD_ROOT/attachments" ]] \
   && [[ ! -e "$INSTALL_ROOT/attachments" || -L "$INSTALL_ROOT/attachments" ]]; then
  if [[ ! -L "$INSTALL_ROOT/attachments" ]]; then
    rmdir "$INSTALL_ROOT/attachments" 2>/dev/null || true
    ln -s "$OLD_ROOT/attachments" "$INSTALL_ROOT/attachments"
    ok "复用现存 attachments → $OLD_ROOT/attachments"
  fi
fi

# ── 生成 compose.yml 与 .env（如未存在） ────────────────────────────────
COMPOSE_FILE="$INSTALL_ROOT/compose.yml"
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-llm-gateway-go-local}"
ENV_FILE="$INSTALL_ROOT/.env"

if [[ ! -f "$COMPOSE_FILE" ]]; then
  log "生成 $COMPOSE_FILE（来自 installer/templates/compose.yml）"
  cp "$PROJECT_ROOT/installer/templates/compose.yml" "$COMPOSE_FILE"
fi

if [[ ! -f "$ENV_FILE" ]]; then
  log "生成 $ENV_FILE（chmod 0600）"
  umask 077
  cat > "$ENV_FILE" <<'ENVEOF'
# Auto-generated by scripts/local-docker-up.sh
POSTGRES_PASSWORD=changeme
REDIS_PASSWORD=
APP_PORT=8781
APP_IMAGE_TAG=local
# 存储路径必须指向 compose.yml（installer/templates/compose.yml）挂载的
# 容器路径；缺省值会写进容器临时层、容器重建即丢失（incident 2026-09-05）。
LLM_GATEWAY_ATTACHMENT_DIR=/opt/llm-gateway-go/data/attachments
LLM_GATEWAY_PERSISTENT_LOG_DIR=/var/log/llm-gateway
ENVEOF
  chmod 0600 "$ENV_FILE"
  warn ".env 已生成，请编辑设置 POSTGRES_PASSWORD 后再次执行"
fi

# ── 启动 ──────────────────────────────────────────────────────────────────
log "docker compose up -d ..."
docker compose --project-directory "$INSTALL_ROOT" -p "$COMPOSE_PROJECT_NAME" -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d

# ── 健康检查 ──────────────────────────────────────────────────────────────
APP_PORT="${APP_PORT:-8781}"
log "等待 healthz ..."
for i in {1..60}; do
  if curl -fsS --max-time 2 "http://127.0.0.1:${APP_PORT}/healthz" >/dev/null 2>&1; then
    ok "gateway healthz OK (after ${i}s)"
    break
  fi
  sleep 1
  if [[ $i -eq 60 ]]; then
    err "healthz 60s 内未响应"
    docker compose --project-directory "$INSTALL_ROOT" -p "$COMPOSE_PROJECT_NAME" -f "$COMPOSE_FILE" --env-file "$ENV_FILE" ps
    exit 1
  fi
done

# ── 总结 ──────────────────────────────────────────────────────────────────
echo ""
ok "Docker 全栈已就绪"
echo ""
echo "  安装根:    $INSTALL_ROOT"
echo "  compose:   $COMPOSE_FILE"
echo "  env:       $ENV_FILE (0600)"
echo "  gateway:   http://localhost:${APP_PORT}/healthz"
echo "  日志:      docker compose -f $COMPOSE_FILE logs -f"
echo "  停机:      bash scripts/local-docker-down.sh"
echo ""
echo "守护: Docker Engine restart policy (restart: unless-stopped)"
echo "      非人工 stop 期间容器不会停。"