#!/usr/bin/env bash
# ============================================================================
# scripts/setup-local-nginx.sh — 本地 Nginx 反向代理层初始化
#
# 用于支持本地蓝绿部署的 Nginx 代理层搭建。
# 这个脚本会：
#   1. 检查 Nginx 是否已安装
#   2. 创建 Nginx 配置目录结构
#   3. 生成主配置和 upstream 切换配置
#   4. 启动 Nginx 并验证
#
# 用法:
#   bash scripts/setup-local-nginx.sh              # 初始化并启动
#   bash scripts/setup-local-nginx.sh --check      # 仅检查状态
#   bash scripts/setup-local-nginx.sh --restart    # 重启 Nginx
#   bash scripts/setup-local-nginx.sh --stop       # 停止 Nginx
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=local-host-layout-helper.sh
source "$SCRIPT_DIR/local-host-layout-helper.sh"

# ── Colors ───────────────────────────────────────────────────────────────
RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'
BLUE=$'\033[0;34m'; CYAN=$'\033[0;36m'; NC=$'\033[0m'
log()   { echo -e "${BLUE}[nginx-setup]${NC} $*"; }
ok()    { echo -e "${GREEN}  ✓${NC} $*"; }
warn()  { echo -e "${YELLOW}  ⚠${NC} $*"; }
err()   { echo -e "${RED}  ✗${NC} $*" >&2; }

# ── Config ───────────────────────────────────────────────────────────────
lh_require_root >/dev/null
VARS=$(lh_layout_vars)
FILES_ROOT=$(echo "$VARS" | sed -n 's/^files_root=//p')
NGINX_ROOT="$FILES_ROOT/nginx"
NGINX_CONF="$NGINX_ROOT/nginx.conf"
NGINX_PID="$NGINX_ROOT/nginx.pid"
ACTIVE_PORT_CONF="$NGINX_ROOT/active-port.conf"
NGINX_PORT=8781
GATEWAY_PORT_BLUE=18781
GATEWAY_PORT_GREEN=18782

ACTION="${1:-install}"

# ── 检查 Nginx 安装 ──────────────────────────────────────────────────────
check_nginx_installed() {
  if command -v nginx >/dev/null 2>&1; then
    local version
    version=$(nginx -v 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
    ok "nginx installed: $version"
    return 0
  else
    err "nginx not installed"
    echo ""
    echo "请安装 Nginx:"
    echo "  macOS:   brew install nginx"
    echo "  Ubuntu:  sudo apt-get install nginx"
    echo "  CentOS:  sudo yum install nginx"
    return 1
  fi
}

# ── 创建配置目录 ──────────────────────────────────────────────────────────
setup_directories() {
  log "创建配置目录: $NGINX_ROOT"
  mkdir -p "$NGINX_ROOT/logs"
  mkdir -p "$NGINX_ROOT/conf.d"
  ok "目录结构就绪"
}

# ── 生成主配置 ────────────────────────────────────────────────────────────
generate_main_config() {
  log "生成主配置: $NGINX_CONF"
  
  # 获取当前用户（macOS 需要设置正确的 user）
  local nginx_user
  if [[ "$(uname)" == "Darwin" ]]; then
    nginx_user="$(whoami) staff"
  else
    nginx_user="nobody"
  fi
  
  cat > "$NGINX_CONF" <<'NGINXCONF'
# LLM Gateway 本地蓝绿部署 Nginx 配置
# Auto-generated by scripts/setup-local-nginx.sh

# 注意: macOS 上需要设置为当前用户，否则会有权限问题
# user  _USERNAME_ _GROUP_;
worker_processes  2;

# PID 文件放在项目目录，避免需要 root 权限
pid        _NGINX_ROOT_/nginx.pid;
error_log  _NGINX_ROOT_/logs/error.log warn;

events {
    worker_connections  1024;
}

http {
    include       /usr/local/etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  _NGINX_ROOT_/logs/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    # 蓝绿 upstream（动态加载活跃端口）
    upstream gateway_backend {
        # 这个 include 是原子切换的关键点
        # 文件内容格式: server 127.0.0.1:18781 max_fails=3 fail_timeout=10s;
        include _NGINX_ROOT_/active-port.conf;
        
        # 连接池复用
        keepalive 32;
        keepalive_requests 100;
        keepalive_timeout 60s;
    }

    server {
        listen       _NGINX_PORT_;
        server_name  localhost;

        # 健康检查端点（直通后端）
        location /healthz {
            proxy_pass http://gateway_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            
            # 快速失败
            proxy_connect_timeout 2s;
            proxy_send_timeout 5s;
            proxy_read_timeout 5s;
        }

        # 就绪检查端点
        location /readyz {
            proxy_pass http://gateway_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            
            proxy_connect_timeout 2s;
            proxy_send_timeout 5s;
            proxy_read_timeout 5s;
        }

        # 版本信息端点
        location /version {
            proxy_pass http://gateway_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }

        # OpenAI API 端点
        location ~ ^/v1/(chat/completions|completions|embeddings|models|audio/transcriptions|audio/translations|images/generations) {
            proxy_pass http://gateway_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # 长超时（流式响应）
            proxy_connect_timeout 30s;
            proxy_send_timeout 300s;
            proxy_read_timeout 300s;
            
            # 支持流式传输
            proxy_buffering off;
            proxy_cache off;
        }

        # Admin API
        location ~ ^/api/(admin|system|users|applications|credentials|providers|models|queues|analytics) {
            proxy_pass http://gateway_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # 正常超时
            proxy_connect_timeout 30s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }

        # SPA 静态资源
        location ~ ^/(assets|static)/ {
            proxy_pass http://gateway_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            
            # 缓存静态资源
            proxy_cache_valid 200 1h;
            proxy_cache_valid 404 1m;
        }

        # 默认路由（SPA 入口）
        location / {
            proxy_pass http://gateway_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            proxy_connect_timeout 30s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }

        # 错误页面
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            return 503 '{"error": {"message": "Gateway temporarily unavailable", "type": "service_unavailable"}}';
            add_header Content-Type application/json;
        }
    }
}
NGINXCONF

  # 替换占位符
  sed -i.bak "s|_NGINX_ROOT_|$NGINX_ROOT|g" "$NGINX_CONF"
  sed -i.bak "s|_NGINX_PORT_|$NGINX_PORT|g" "$NGINX_CONF"
  sed -i.bak "s|# user  _USERNAME_ _GROUP_;|user  $nginx_user;|g" "$NGINX_CONF"
  rm -f "$NGINX_CONF.bak"
  
  ok "主配置已生成"
}

# ── 生成初始 upstream 配置 ───────────────────────────────────────────────
generate_upstream_config() {
  log "生成初始 upstream 配置: $ACTIVE_PORT_CONF"
  
  # 默认指向 blue 端口
  cat > "$ACTIVE_PORT_CONF" <<EOF
server 127.0.0.1:$GATEWAY_PORT_BLUE max_fails=3 fail_timeout=10s;
EOF
  
  ok "upstream 配置已生成 (默认: $GATEWAY_PORT_BLUE)"
}

# ── 验证配置 ──────────────────────────────────────────────────────────────
validate_config() {
  log "验证 Nginx 配置..."
  if nginx -t -c "$NGINX_CONF" 2>&1 | grep -q "successful"; then
    ok "配置验证通过"
    return 0
  else
    err "配置验证失败"
    nginx -t -c "$NGINX_CONF" 2>&1
    return 1
  fi
}

# ── 启动 Nginx ────────────────────────────────────────────────────────────
start_nginx() {
  if [[ -f "$NGINX_PID" ]] && kill -0 "$(cat "$NGINX_PID")" 2>/dev/null; then
    warn "Nginx 已在运行 (PID: $(cat "$NGINX_PID"))"
    return 0
  fi
  
  log "启动 Nginx..."
  nginx -c "$NGINX_CONF"
  
  # 等待启动
  for i in {1..10}; do
    if [[ -f "$NGINX_PID" ]] && kill -0 "$(cat "$NGINX_PID")" 2>/dev/null; then
      ok "Nginx 已启动 (PID: $(cat "$NGINX_PID"))"
      return 0
    fi
    sleep 1
  done
  
  err "Nginx 启动失败"
  return 1
}

# ── 停止 Nginx ────────────────────────────────────────────────────────────
stop_nginx() {
  if [[ ! -f "$NGINX_PID" ]]; then
    warn "Nginx 未运行"
    return 0
  fi
  
  local pid
  pid=$(cat "$NGINX_PID")
  
  if ! kill -0 "$pid" 2>/dev/null; then
    warn "PID 文件存在但进程不在 (PID: $pid)"
    rm -f "$NGINX_PID"
    return 0
  fi
  
  log "停止 Nginx (PID: $pid)..."
  nginx -s stop -c "$NGINX_CONF" || kill "$pid"
  
  # 等待停止
  for i in {1..10}; do
    if ! kill -0 "$pid" 2>/dev/null; then
      rm -f "$NGINX_PID"
      ok "Nginx 已停止"
      return 0
    fi
    sleep 1
  done
  
  warn "Nginx 未在 10s 内停止，强制 SIGKILL"
  kill -9 "$pid" 2>/dev/null || true
  rm -f "$NGINX_PID"
  ok "Nginx 已强制停止"
}

# ── 重启 Nginx ────────────────────────────────────────────────────────────
restart_nginx() {
  stop_nginx
  sleep 1
  start_nginx
}

# ── 检查状态 ──────────────────────────────────────────────────────────────
check_status() {
  echo ""
  echo "═══ Nginx 状态 ═══"
  
  if [[ -f "$NGINX_PID" ]] && kill -0 "$(cat "$NGINX_PID")" 2>/dev/null; then
    local pid
    pid=$(cat "$NGINX_PID")
    ok "运行中 (PID: $pid)"
    
    # 检查端口监听
    if lsof -Pi :$NGINX_PORT -sTCP:LISTEN -t >/dev/null 2>&1; then
      ok "监听端口: $NGINX_PORT"
    else
      warn "未监听端口 $NGINX_PORT"
    fi
    
    # 检查 upstream 配置
    if [[ -f "$ACTIVE_PORT_CONF" ]]; then
      local active_port
      active_port=$(grep -oE '[0-9]{5}' "$ACTIVE_PORT_CONF" | head -1)
      ok "当前 upstream: 127.0.0.1:$active_port"
    fi
    
    # 测试健康检查
    echo ""
    echo "  测试健康检查:"
    if curl -fsS --max-time 2 "http://127.0.0.1:$NGINX_PORT/healthz" >/dev/null 2>&1; then
      ok "  http://127.0.0.1:$NGINX_PORT/healthz → 200 OK"
    else
      warn "  http://127.0.0.1:$NGINX_PORT/healthz → 不可达"
      warn "  后端 gateway (端口 $active_port) 可能未启动"
    fi
  else
    err "未运行"
  fi
  
  echo ""
}

# ── 完整安装 ──────────────────────────────────────────────────────────────
do_install() {
  echo ""
  echo "═══ LLM Gateway 本地 Nginx 蓝绿代理层初始化 ═══"
  echo ""
  
  check_nginx_installed || exit 1
  setup_directories
  generate_main_config
  generate_upstream_config
  validate_config || exit 1
  start_nginx
  
  echo ""
  ok "安装完成!"
  echo ""
  echo "下一步:"
  echo "  1. 启动 gateway: bash scripts/local-host-deploy.sh deploy --mode bluegreen"
  echo "  2. 访问代理层: curl http://localhost:$NGINX_PORT/healthz"
  echo "  3. 查看状态: bash scripts/setup-local-nginx.sh --check"
  echo ""
}

# ── 主逻辑 ────────────────────────────────────────────────────────────────
case "$ACTION" in
  install)
    do_install
    ;;
  --check|check|status)
    check_nginx_installed || exit 1
    check_status
    ;;
  --start|start)
    check_nginx_installed || exit 1
    start_nginx
    ;;
  --stop|stop)
    check_nginx_installed || exit 1
    stop_nginx
    ;;
  --restart|restart)
    check_nginx_installed || exit 1
    restart_nginx
    ;;
  -h|--help)
    sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 0
    ;;
  *)
    err "未知操作: $ACTION"
    echo "用法: $0 [install|check|start|stop|restart]"
    exit 1
    ;;
esac
