#!/usr/bin/env bash
# ============================================================================
# sync-kaixuan1-schema.sh — Apply 252's llm-gateway structure to kaixuan-1
#
# This script imports the pre-generated schema + data dumps into kaixuan-1's
# PostgreSQL. Run this at the company when kaixuan-1 is reachable.
#
# Prerequisites:
#   - Schema dump: backups/lgw_schema_252.dump (from 252's pg_dump --schema-only)
#   - Data dump:   backups/lgw_data_252.dump   (from 252's pg_dump --data-only)
#   - Both files were generated by pg-table-copy.sh from 252
#
# Usage:
#   ./scripts/sync-kaixuan1-schema.sh
#   ./scripts/sync-kaixuan1-schema.sh --target-host 192.168.31.8 --target-port 30432
#   ./scripts/sync-kaixuan1-schema.sh --schema-only  # Only import schema, skip data
# ============================================================================

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────
G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; B='\033[0;34m'; N='\033[0m'
ok()    { echo -e "${G}✓${N} $*"; }
info()  { echo -e "${Y}▶${N} $*"; }
err()   { echo -e "${R}✗${N} $*" >&2; }
phase() { echo -e "\n${B}════════════════════════════════════════════════════════════${N}"; echo -e "${B}  $*${N}"; echo -e "${B}════════════════════════════════════════════════════════════${N}"; }

# ── Config ────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
BACKUP_DIR="$REPO_DIR/backups"

# Default: kaixuan-1 internal (run at company)
TARGET_HOST="${TARGET_HOST:-192.168.31.8}"
TARGET_PORT="${TARGET_PORT:-30432}"
TARGET_USER="${TARGET_USER:-llm_gateway}"
TARGET_PASS="${TARGET_PASS:-4Q92cFTaYY8Z3AO07XTBBH-1g7kceaxg}"
TARGET_DB="${TARGET_DB:-llm_gateway}"

SCHEMA_ONLY=false

# ── Parse args ────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --target-host)   TARGET_HOST="$2"; shift 2 ;;
    --target-port)   TARGET_PORT="$2"; shift 2 ;;
    --target-user)   TARGET_USER="$2"; shift 2 ;;
    --target-pass)   TARGET_PASS="$2"; shift 2 ;;
    --target-db)     TARGET_DB="$2"; shift 2 ;;
    --schema-only)   SCHEMA_ONLY=true; shift ;;
    -h|--help)
      echo "Usage: $0 [--target-host h] [--target-port p] [--target-user u] [--target-pass pw] [--target-db db] [--schema-only]"
      echo ""
      echo "Default: kaixuan-1 internal (192.168.31.8:30432, llm_gateway user)"
      echo ""
      echo "Options:"
      echo "  --target-host   Target PG host (default: 192.168.31.8)"
      echo "  --target-port   Target PG port (default: 30432)"
      echo "  --target-user   Target PG user (default: llm_gateway)"
      echo "  --target-pass   Target PG password"
      echo "  --target-db     Target database name (default: llm_gateway)"
      echo "  --schema-only   Only import schema, skip data"
      exit 0
      ;;
    *) err "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Verify dumps exist ────────────────────────────────────────────────────
SCHEMA_DUMP="$BACKUP_DIR/lgw_schema_252.dump"
DATA_DUMP="$BACKUP_DIR/lgw_data_252.dump"

if [[ ! -f "$SCHEMA_DUMP" ]]; then
  err "Schema dump not found: $SCHEMA_DUMP"
  err "Generate it first: ./scripts/pg-table-copy.sh --source-host ... --source-port ... --schema-only"
  exit 1
fi

if [[ ! "$SCHEMA_ONLY" && ! -f "$DATA_DUMP" ]]; then
  err "Data dump not found: $DATA_DUMP"
  err "Generate it first: ./scripts/pg-table-copy.sh --source-host ... --source-port ... --data-only"
  exit 1
fi

# ── Test connection ────────────────────────────────────────────────────────
phase "PHASE 1: TEST CONNECTION"

info "Connecting to ${TARGET_USER}@${TARGET_HOST}:${TARGET_PORT}/${TARGET_DB}"
if PGPASSWORD="$TARGET_PASS" psql -h "$TARGET_HOST" -p "$TARGET_PORT" -U "$TARGET_USER" -d "$TARGET_DB" -c "SELECT 1" &>/dev/null; then
  ok "Connection OK"
else
  err "Cannot connect to target database"
  err "Make sure you're at the company and kaixuan-1's PG is reachable"
  exit 1
fi

# ── Import schema ──────────────────────────────────────────────────────────
phase "PHASE 2: IMPORT SCHEMA"

info "Importing schema from $SCHEMA_DUMP ($(du -h "$SCHEMA_DUMP" | cut -f1))..."
PGPASSWORD="$TARGET_PASS" psql -h "$TARGET_HOST" -p "$TARGET_PORT" -U "$TARGET_USER" -d "$TARGET_DB" \
  -f "$SCHEMA_DUMP" 2>&1 | tail -5

ok "Schema imported"

# ── Import data ────────────────────────────────────────────────────────────
if ! $SCHEMA_ONLY; then
  phase "PHASE 3: IMPORT DATA"
  
  info "Importing data from $DATA_DUMP ($(du -h "$DATA_DUMP" | cut -f1))..."
  PGPASSWORD="$TARGET_PASS" psql -h "$TARGET_HOST" -p "$TARGET_PORT" -U "$TARGET_USER" -d "$TARGET_DB" \
    -f "$DATA_DUMP" 2>&1 | tail -5
  
  ok "Data imported"
fi

# ── Verify ────────────────────────────────────────────────────────────────
phase "PHASE 4: VERIFY"

info "Target DB size:"
PGPASSWORD="$TARGET_PASS" psql -h "$TARGET_HOST" -p "$TARGET_PORT" -U "$TARGET_USER" -d "$TARGET_DB" \
  -c "SELECT pg_size_pretty(pg_database_size('$TARGET_DB'));"

info "Table count:"
PGPASSWORD="$TARGET_PASS" psql -h "$TARGET_HOST" -p "$TARGET_PORT" -U "$TARGET_USER" -d "$TARGET_DB" \
  -c "SELECT count(*) FROM information_schema.tables WHERE table_schema NOT IN ('pg_catalog','information_schema','columnar_internal');"

ok "sync-kaixuan1-schema complete!"
