// Package compliance — embedded report templates (B4-1).
//
// These are the Markdown templates used by Render(). They are versioned via
// TemplateVersion (in report.go); bumping the version forces existing report
// links to be re-generated if the auditor's reproducibility tool compares them.
//
// Template language: Go text/template (see https://pkg.go.dev/text/template).
// Available funcs: statusIcon (emoji), lower.
//
// Design rationale: templates are embedded as Go const strings, NOT loaded
// from disk, so:
//  1. The binary is self-contained (no .md files to ship).
//  2. Tests can assert on exact template text.
//  3. A future PR to add a new framework adds ONE entry to the templates
//     map and ONE new template const — easy to review.
package compliance

// templates maps each supported Framework to its Markdown template string.
var templates = map[Framework]string{
	// ── 等保 2.0 (China Multi-Level Protection Scheme 2.0) ────────────
	// The 10 control families correspond roughly to GB/T 22239-2019.
	// Reports cover the most-assessed subset; full coverage comes from
	// admin-supplied Evidence slices.
	FrameworkDJCP: `# {{.Title}}

> **报告类型**：等保 2.0 合规报告
> **租户**：{{.TenantID}}
> **审计周期**：{{.Period}}
> **生成时间**：{{.GeneratedAt.Format "2006-01-02T15:04:05Z07:00"}}
> **模板版本**：{{.TemplateVer}}

---

## 摘要

{{.Summary}}

### 控制项统计

| 状态 | 数量 | 图标 |
|------|------|------|
{{- $counts := countByStatus .Evidence}}
{{- range $status, $n := $counts}}
| {{$status | statusIcon}} {{$status}} | {{$n}} | {{$status | statusIcon}} |
{{- end}}

## 控制项证据

{{range .Evidence}}
### {{.ControlID}} {{.Title}}

**状态**：{{statusIcon .Status}} {{.Status}}

**证据**：

{{.Detail}}

{{end}}

---

*本报告由 llm-gateway-go {{lower .TemplateVer}} 自动生成，未经法务审查。*
*正式发布前需经安全部门 + 法务联合签字（参考 docs/compliance/legal-review.md 占位）。*
`,

	// ── GDPR Article 32 (security of processing) ─────────────────────
	FrameworkGDPR: `# {{.Title}}

> **Regulation**: GDPR (EU 2016/679)
> **Data Controller Tenant**: {{.TenantID}}
> **Period**: {{.Period}}
> **Generated**: {{.GeneratedAt.Format "2006-01-02T15:04:05Z07:00"}}
> **Template Version**: {{.TemplateVer}}

---

## Executive Summary

{{.Summary}}

### Control Statistics

| Status | Count | Icon |
|--------|-------|------|
{{- $counts := countByStatus .Evidence}}
{{- range $status, $n := $counts}}
| {{$status | statusIcon}} {{$status}} | {{$n}} | {{$status | statusIcon}} |
{{- end}}

## Article 32 Evidence

{{range .Evidence}}
### {{.ControlID}} — {{.Title}}

**Status**: {{statusIcon .Status}} {{.Status}}

**Evidence**:

{{.Detail}}

{{end}}

---

*This report was auto-generated by llm-gateway-go {{lower .TemplateVer}}.*
*POPIA / GDPR Article 30 record-of-processing entries remain the controller's responsibility.*
`,
}
