--
-- Name: routing_decision_log_with_current_month; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.routing_decision_log_with_current_month AS
 SELECT routing_decision_log_hot.ts,
    routing_decision_log_hot.request_id,
    routing_decision_log_hot.idempotency_key,
    routing_decision_log_hot.tenant_id,
    routing_decision_log_hot.api_key_id,
    routing_decision_log_hot.model,
    routing_decision_log_hot.chosen_credential_id,
    routing_decision_log_hot.chosen_provider_id,
    routing_decision_log_hot.tier,
    routing_decision_log_hot.candidates_tried,
    routing_decision_log_hot.latency_ms,
    routing_decision_log_hot.success,
    routing_decision_log_hot.error_class,
    routing_decision_log_hot.prompt_tokens,
    routing_decision_log_hot.completion_tokens,
    routing_decision_log_hot.cost_usd,
    routing_decision_log_hot.request_bytes,
    routing_decision_log_hot.response_bytes,
    routing_decision_log_hot.client_model,
    routing_decision_log_hot.resolved_raw_model,
    routing_decision_log_hot.sticky_hit,
    routing_decision_log_hot.client_profile,
    routing_decision_log_hot.outbound_model,
    routing_decision_log_hot.request_mode,
    routing_decision_log_hot.identity_hash,
    routing_decision_log_hot.transform_rule_id,
    routing_decision_log_hot.egress_protocol,
    routing_decision_log_hot.failure_stage,
    routing_decision_log_hot.failure_detail_code,
    routing_decision_log_hot.virtual_client_id,
    routing_decision_log_hot.virtual_ip,
    routing_decision_log_hot.virtual_mac,
    routing_decision_log_hot.resolution_path,
    routing_decision_log_hot.canonical_model,
    routing_decision_log_hot.resolution_raw_models,
    routing_decision_log_hot.decision_trace
   FROM public.routing_decision_log_hot
UNION ALL
 SELECT routing_decision_log.ts,
    routing_decision_log.request_id,
    routing_decision_log.idempotency_key,
    routing_decision_log.tenant_id,
    routing_decision_log.api_key_id,
    routing_decision_log.model,
    routing_decision_log.chosen_credential_id,
    routing_decision_log.chosen_provider_id,
    routing_decision_log.tier,
    routing_decision_log.candidates_tried,
    routing_decision_log.latency_ms,
    routing_decision_log.success,
    routing_decision_log.error_class,
    routing_decision_log.prompt_tokens,
    routing_decision_log.completion_tokens,
    routing_decision_log.cost_usd,
    routing_decision_log.request_bytes,
    routing_decision_log.response_bytes,
    routing_decision_log.client_model,
    routing_decision_log.resolved_raw_model,
    routing_decision_log.sticky_hit,
    routing_decision_log.client_profile,
    routing_decision_log.outbound_model,
    routing_decision_log.request_mode,
    routing_decision_log.identity_hash,
    routing_decision_log.transform_rule_id,
    routing_decision_log.egress_protocol,
    routing_decision_log.failure_stage,
    routing_decision_log.failure_detail_code,
    routing_decision_log.virtual_client_id,
    routing_decision_log.virtual_ip,
    routing_decision_log.virtual_mac,
    routing_decision_log.resolution_path,
    routing_decision_log.canonical_model,
    routing_decision_log.resolution_raw_models,
    routing_decision_log.decision_trace
   FROM public.routing_decision_log;

