package ratelimit

import (
	"net/http"
	"strings"
)

// GatewayRateLimitScopeHeader identifies rate-limit responses generated by
// this gateway's API-key admission controls. It is a reserved response header:
// upstream response-copy paths must never forward a provider-supplied value.
const GatewayRateLimitScopeHeader = "X-LLM-Gateway-RateLimit-Scope"

// GatewayRateLimitScopeSharedKey means the caller API key itself was rejected
// by local gateway admission. Credential self-check requests all use the same
// worker API key, so this scope is shared across credentials.
const GatewayRateLimitScopeSharedKey = "shared_key"

// MarkGatewaySharedKeyRateLimit marks a response rejected by this gateway's
// API-key admission controls. Self-check workers share one API key across
// credential probes, so this signal has worker-wide scope.
func MarkGatewaySharedKeyRateLimit(w http.ResponseWriter) {
	if w != nil {
		w.Header().Set(GatewayRateLimitScopeHeader, GatewayRateLimitScopeSharedKey)
	}
}

// IsGatewayRateLimitScopeHeader identifies the reserved response header.
// Upstream error-header forwarding must drop it so a provider cannot forge a
// worker-wide cooldown signal.
func IsGatewayRateLimitScopeHeader(name string) bool {
	return strings.EqualFold(name, GatewayRateLimitScopeHeader)
}
