-- ============================================================================
-- llm-gateway-go 提供商初始化数据
-- ============================================================================
-- 注意：此文件包含提供商的基本配置信息，不包含凭据数据
-- 凭据数据（credentials）需要单独配置，不在初始化脚本中
-- ============================================================================

INSERT INTO public.providers (
    code, name, catalog_code, kind, category, protocol, base_url,
    egress_profile, domestic, discount_rate, enabled, quality_fix_mode
) VALUES
    ('xiaomi', '小米大模型', 'xiaomi', 'cloud', 'official', 'openai-completions',
     'https://token-plan-cn.xiaomimimo.com/v1', 'direct', true, 1.0, true, 'off'),
    ('anthropic', 'Anthropic', 'anthropic', 'cloud', 'official', 'anthropic-messages',
     'https://api.anthropic.com', 'proxy', false, 1.0, true, 'off'),
    ('azure-openai', 'Azure OpenAI', 'azure-openai', 'cloud', 'official', 'openai-completions',
     'https://{resource}.openai.azure.com/openai/deployments/{deployment}', 'proxy', false, 1.0, true, 'off'),
    ('baichuan', '百川 AI', 'baichuan', 'cloud', 'official', 'openai-completions',
     'https://api.baichuan-ai.com/v1', 'direct', true, 1.0, true, 'off'),
    ('cohere', 'Cohere', 'cohere', 'cloud', 'official', 'openai-completions',
     'https://api.cohere.com/compatibility/v1', 'proxy', false, 1.0, true, 'off'),
    ('deepseek', 'DeepSeek', 'deepseek', 'cloud', 'official', 'openai-completions',
     'https://api.deepseek.com/v1', 'direct', true, 1.0, true, 'off'),
    ('doubao', '豆包（字节跳动）', 'doubao', 'cloud', 'official', 'openai-completions',
     'https://ark.cn-beijing.volces.com/api/coding/v3', 'direct', true, 1.0, true, 'off'),
    ('fireworks', 'Fireworks AI', 'fireworks', 'cloud', 'aggregator', 'openai-completions',
     'https://api.fireworks.ai/inference/v1', 'proxy', false, 1.0, true, 'off'),
    ('github-copilot', 'GitHub Copilot', 'github-copilot', 'cloud', 'official_proxy', 'openai-completions',
     'https://api.githubcopilot.com', 'proxy', false, 1.0, true, 'off'),
    ('google-gemini', 'Google Gemini', 'google-gemini', 'cloud', 'official', 'openai-completions',
     'https://generativelanguage.googleapis.com/v1beta/openai', 'proxy', false, 1.0, true, 'off'),
    ('groq', 'Groq', 'groq', 'cloud', 'official', 'openai-completions',
     'https://api.groq.com/openai/v1', 'proxy', false, 1.0, true, 'off'),
    ('llamacpp', 'llama.cpp Server', 'llamacpp', 'local', 'self_host', 'openai-completions',
     'http://{host}:{port}/v1', 'direct', true, 1.0, true, 'off'),
    ('lmstudio', 'LM Studio', 'lmstudio', 'local', 'self_host', 'openai-completions',
     'http://{host}:{port}/v1', 'direct', true, 1.0, true, 'off'),
    ('minimax', 'MiniMax', 'minimax', 'cloud', 'official', 'openai-completions',
     'https://api.minimaxi.com/v1', 'direct', true, 1.0, true, 'off'),
    ('mistral', 'Mistral AI', 'mistral', 'cloud', 'official', 'openai-completions',
     'https://api.mistral.ai/v1', 'proxy', false, 1.0, true, 'off'),
    ('mlx', 'Apple MLX Server', 'mlx', 'local', 'self_host', 'openai-completions',
     'http://{host}:{port}/v1', 'direct', true, 1.0, true, 'off'),
    ('moonshot', 'Moonshot / Kimi', 'moonshot', 'cloud', 'official', 'openai-completions',
     'https://api.moonshot.cn/v1', 'direct', true, 1.0, true, 'off'),
    ('nvidia', 'NVIDIA NIM', 'nvidia', 'cloud', 'aggregator', 'openai-completions',
     'https://integrate.api.nvidia.com/v1', 'proxy', false, 1.0, true, 'off'),
    ('ollama', 'Ollama', 'ollama', 'local', 'self_host', 'openai-completions',
     'http://{host}:{port}/v1', 'direct', true, 1.0, true, 'off'),
    ('openai', 'OpenAI', 'openai', 'cloud', 'official', 'openai-completions',
     'https://api.openai.com/v1', 'proxy', false, 1.0, true, 'off'),
    ('openrouter', 'OpenRouter', 'openrouter', 'cloud', 'third_party_relay', 'openai-completions',
     'https://openrouter.ai/api/v1', 'proxy', false, 1.0, true, 'off'),
    ('perplexity', 'Perplexity AI', 'perplexity', 'cloud', 'official', 'openai-completions',
     'https://api.perplexity.ai', 'proxy', false, 1.0, true, 'off'),
    ('qwen', '阿里百炼（通义千问）', 'qwen', 'cloud', 'official', 'openai-completions',
     'https://dashscope.aliyuncs.com/compatible-mode/v1', 'direct', true, 1.0, true, 'off'),
    ('sensenova', '商汤 SenseNova', 'sensenova', 'cloud', 'official', 'openai-completions',
     'https://api.sensenova.cn/compatible-mode/v1', 'direct', true, 1.0, true, 'off'),
    ('siliconflow', '硅基流动', 'siliconflow', 'cloud', 'aggregator', 'openai-completions',
     'https://api.siliconflow.cn/v1', 'direct', true, 1.0, true, 'off'),
    ('stepfun', '阶跃星辰', 'stepfun', 'cloud', 'official', 'openai-completions',
     'https://api.stepfun.com/v1', 'direct', true, 1.0, true, 'off'),
    ('together', 'Together AI', 'together', 'cloud', 'aggregator', 'openai-completions',
     'https://api.together.xyz/v1', 'proxy', false, 1.0, true, 'off'),
    ('vllm', 'vLLM Server', 'vllm', 'local', 'self_host', 'openai-completions',
     'http://{host}:{port}/v1', 'direct', true, 1.0, true, 'off'),
    ('volcengine-coding', '火山方舟 Coding', 'volcengine-coding', 'cloud', 'aggregator', 'openai-completions',
     'https://ark.cn-beijing.volces.com/api/coding/v3', 'direct', true, 1.0, true, 'off'),
    ('xai', 'xAI (Grok)', 'xai', 'cloud', 'official', 'openai-completions',
     'https://api.x.ai/v1', 'proxy', false, 1.0, true, 'off'),
    ('yi', '零一万物', 'yi', 'cloud', 'official', 'openai-completions',
     'https://api.lingyiwanwu.com/v1', 'direct', true, 1.0, true, 'off'),
    ('zhipu', '智谱AI', 'zhipu', 'cloud', 'official', 'openai-completions',
     'https://open.bigmodel.cn/api/coding/paas/v4', 'direct', true, 1.0, true, 'off')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    base_url = EXCLUDED.base_url,
    enabled = EXCLUDED.enabled,
    updated_at = NOW();